// generated from gentext.pl Messages.xlsx
#ifndef __STRING_TABLE_RESOURCE_H__
#define __STRING_TABLE_RESOURCE_H__
#define IDS_TJS_INTERNAL_ERROR                                                    10000
#define IDS_TJS_WARNING                                                           10001
#define IDS_TJS_WARN_EVAL_OPERATOR                                                10002
#define IDS_TJS_NARROW_TO_WIDE_CONVERSION_ERROR                                   10003
#define IDS_TJS_VARIANT_CONVERT_ERROR                                             10004
#define IDS_TJS_VARIANT_CONVERT_ERROR_TO_OBJECT                                   10005
#define IDS_TJS_IDEXPECTED                                                        10006
#define IDS_TJS_SUBSTITUTION_IN_BOOLEAN_CONTEXT                                   10007
#define IDS_TJS_CANNOT_MODIFY_LHS                                                 10008
#define IDS_TJS_INSUFFICIENT_MEM                                                  10009
#define IDS_TJS_CANNOT_GET_RESULT                                                 10010
#define IDS_TJS_NULL_ACCESS                                                       10011
#define IDS_TJS_MEMBER_NOT_FOUND                                                  10012
#define IDS_TJS_MEMBER_NOT_FOUND_NO_NAME_GIVEN                                    10013
#define IDS_TJS_NOT_IMPLEMENTED                                                   10014
#define IDS_TJS_INVALID_PARAM                                                     10015
#define IDS_TJS_BAD_PARAM_COUNT                                                   10016
#define IDS_TJS_INVALID_TYPE                                                      10017
#define IDS_TJS_SPECIFY_DIC_OR_ARRAY                                              10018
#define IDS_TJS_SPECIFY_ARRAY                                                     10019
#define IDS_TJS_STRING_DEALLOC_ERROR                                              10020
#define IDS_TJS_STRING_ALLOC_ERROR                                                10021
#define IDS_TJS_MISPLACED_BREAK_CONTINUE                                          10022
#define IDS_TJS_MISPLACED_CASE                                                    10023
#define IDS_TJS_MISPLACED_RETURN                                                  10024
#define IDS_TJS_STRING_PARSE_ERROR                                                10025
#define IDS_TJS_NUMBER_ERROR                                                      10026
#define IDS_TJS_UNCLOSED_COMMENT                                                  10027
#define IDS_TJS_INVALID_CHAR                                                      10028
#define IDS_TJS_EXPECTED                                                          10029
#define IDS_TJS_SYNTAX_ERROR                                                      10030
#define IDS_TJS_PPERROR                                                           10031
#define IDS_TJS_CANNOT_GET_SUPER                                                  10032
#define IDS_TJS_INVALID_OPECODE                                                   10033
#define IDS_TJS_RANGE_ERROR                                                       10034
#define IDS_TJS_ACCESS_DENYED                                                     10035
#define IDS_TJS_NATIVE_CLASS_CRASH                                                10036
#define IDS_TJS_INVALID_OBJECT                                                    10037
#define IDS_TJS_CANNOT_OMIT                                                       10038
#define IDS_TJS_CANNOT_PARSE_DATE                                                 10039
#define IDS_TJS_INVALID_VALUE_FOR_TIMESTAMP                                       10040
#define IDS_TJS_EXCEPTION_NOT_FOUND                                               10041
#define IDS_TJS_INVALID_FORMAT_STRING                                             10042
#define IDS_TJS_DIVIDE_BY_ZERO                                                    10043
#define IDS_TJS_NOT_RECONSTRUCTIVE_RANDOMIZE_DATA                                 10044
#define IDS_TJS_SYMBOL                                                            10045
#define IDS_TJS_CALL_HISTORY_IS_FROM_OUT_OF_TJS2SCRIPT                            10046
#define IDS_TJS_NOBJECTS_WAS_NOT_FREED                                            10047
#define IDS_TJS_OBJECT_CREATION_HISTORY_DELIMITER_CRLF                            10048
#define IDS_TJS_OBJECT_CREATION_HISTORY_DELIMITER                                 10049
#define IDS_TJS_OBJECT_WAS_NOT_FREED_CRLF                                         10050
#define IDS_TJS_OBJECT_WAS_NOT_FREED                                              10051
#define IDS_TJS_GROUP_BY_OBJECT_TYPE_AND_HISTORY                                  10052
#define IDS_TJS_GROUP_BY_OBJECT_TYPE                                              10053
#define IDS_TJS_OBJECT_COUNTING_MESSAGE_GROUP_BY_OBJECT_TYPE_AND_HISTORY_CRLF     10054
#define IDS_TJS_OBJECT_COUNTING_MESSAGE_GROUP_BY_OBJECT_TYPE_AND_HISTORY          10055
#define IDS_TJS_OBJECT_COUNTING_MESSAGE_TJSGROUP_BY_OBJECT_TYPE                   10056
#define IDS_TJS_WARN_RUNNING_CODE_ON_DELETING_OBJECT_CRLF                         10057
#define IDS_TJS_WARN_RUNNING_CODE_ON_DELETING_OBJECT                              10058
#define IDS_TJS_WRITE_ERROR                                                       10059
#define IDS_TJS_READ_ERROR                                                        10060
#define IDS_TJS_SEEK_ERROR                                                        10061
#define IDS_TJS_BYTE_CODE_BROKEN                                                  10062
#define IDS_TJS_OBJECT_HASH_MAP_LOG_VERSION_MISMATCH                              10063
#define IDS_TJS_CURRUPTED_OBJECT_HASH_MAP_LOG                                     10064
#define IDS_TJS_UNKNOWN_FAILURE                                                   10065
#define IDS_TJS_UNKNOWN_PACK_UNPACK_TEMPLATE_CHARCTER                             10066
#define IDS_TJS_UNKNOWN_BIT_STRING_CHARACTER                                      10067
#define IDS_TJS_UNKNOWN_HEX_STRING_CHARACTER                                      10068
#define IDS_TJS_NOT_SUPPORTED_UUENCODE                                            10069
#define IDS_TJS_NOT_SUPPORTED_BER                                                 10070
#define IDS_TJS_NOT_SUPPORTED_UNPACK_LP                                           10071
#define IDS_TJS_NOT_SUPPORTED_UNPACK_P                                            10072
#define IDS_TVP_VERSION_INFORMATION                                               10073
#define IDS_TVP_VERSION_INFORMATION2                                              10074
#define IDS_TVP_DOWNLOAD_PAGE_URL                                                 10075
#define IDS_TVP_INTERNAL_ERROR                                                    10076
#define IDS_TVP_INVALID_PARAM                                                     10077
#define IDS_TVP_WARN_DEBUG_OPTION_ENABLED                                         10078
#define IDS_TVP_COMMAND_LINE_PARAM_IGNORED_AND_DEFAULT_USED                       10079
#define IDS_TVP_INVALID_COMMAND_LINE_PARAM                                        10080
#define IDS_TVP_NOT_IMPLEMENTED                                                   10081
#define IDS_TVP_CANNOT_OPEN_STORAGE                                               10082
#define IDS_TVP_CANNOT_FIND_STORAGE                                               10083
#define IDS_TVP_CANNOT_OPEN_STORAGE_FOR_WRITE                                     10084
#define IDS_TVP_STORAGE_IN_ARCHIVE_NOT_FOUND                                      10085
#define IDS_TVP_INVALID_PATH_NAME                                                 10086
#define IDS_TVP_UNSUPPORTED_MEDIA_NAME                                            10087
#define IDS_TVP_CANNOT_UNBIND_XP3EXE                                              10088
#define IDS_TVP_CANNOT_FIND_XP3MARK                                               10089
#define IDS_TVP_MISSING_PATH_DELIMITER_AT_LAST                                    10090
#define IDS_TVP_FILENAME_CONTAINS_SHARP_WARN                                      10091
#define IDS_TVP_CANNOT_GET_LOCAL_NAME                                             10092
#define IDS_TVP_READ_ERROR                                                        10093
#define IDS_TVP_WRITE_ERROR                                                       10094
#define IDS_TVP_SEEK_ERROR                                                        10095
#define IDS_TVP_TRUNCATE_ERROR                                                    10096
#define IDS_TVP_INSUFFICIENT_MEMORY                                               10097
#define IDS_TVP_UNCOMPRESSION_FAILED                                              10098
#define IDS_TVP_COMPRESSION_FAILED                                                10099
#define IDS_TVP_CANNOT_WRITE_TO_ARCHIVE                                           10100
#define IDS_TVP_UNSUPPORTED_CIPHER_MODE                                           10101
#define IDS_TVP_UNSUPPORTED_ENCODING                                              10102
#define IDS_TVP_UNSUPPORTED_MODE_STRING                                           10103
#define IDS_TVP_UNKNOWN_GRAPHIC_FORMAT                                            10104
#define IDS_TVP_CANNOT_SUGGEST_GRAPHIC_EXTENSION                                  10105
#define IDS_TVP_MASK_SIZE_MISMATCH                                                10106
#define IDS_TVP_PROVINCE_SIZE_MISMATCH                                            10107
#define IDS_TVP_IMAGE_LOAD_ERROR                                                  10108
#define IDS_TVP_JPEGLOAD_ERROR                                                    10109
#define IDS_TVP_PNGLOAD_ERROR                                                     10110
#define IDS_TVP_ERILOAD_ERROR                                                     10111
#define IDS_TVP_TLGLOAD_ERROR                                                     10112
#define IDS_TVP_INVALID_IMAGE_SAVE_TYPE                                           10113
#define IDS_TVP_INVALID_OPERATION_FOR8BPP                                         10114
#define IDS_TVP_INVALID_OPERATION_FOR32BPP                                        10115
#define IDS_TVP_SPECIFY_WINDOW                                                    10116
#define IDS_TVP_SPECIFY_LAYER                                                     10117
#define IDS_TVP_SPECIFY_LAYER_OR_BITMAP                                           10118
#define IDS_TVP_CANNOT_ACCEPT_MODE_AUTO                                           10119
#define IDS_TVP_CANNOT_CREATE_EMPTY_LAYER_IMAGE                                   10120
#define IDS_TVP_CANNOT_SET_PRIMARY_INVISIBLE                                      10121
#define IDS_TVP_CANNOT_MOVE_PRIMARY                                               10122
#define IDS_TVP_CANNOT_SET_PARENT_SELF                                            10123
#define IDS_TVP_CANNOT_MOVE_NEXT_TO_SELF_OR_NOT_SIBLINGS                          10124
#define IDS_TVP_CANNOT_MOVE_PRIMARY_OR_SIBLINGLESS                                10125
#define IDS_TVP_CANNOT_MOVE_TO_UNDER_OTHER_PRIMARY_LAYER                          10126
#define IDS_TVP_INVALID_IMAGE_POSITION                                            10127
#define IDS_TVP_CANNOT_SET_MODE_TO_DISABLED_OR_MODAL                              10128
#define IDS_TVP_NOT_DRAWABLE_LAYER_TYPE                                           10129
#define IDS_TVP_SOURCE_LAYER_HAS_NO_IMAGE                                         10130
#define IDS_TVP_UNSUPPORTED_LAYER_TYPE                                            10131
#define IDS_TVP_NOT_DRAWABLE_FACE_TYPE                                            10132
#define IDS_TVP_CANNOT_CONVERT_LAYER_TYPE_USING_GIVEN_DIRECTION                   10133
#define IDS_TVP_NEGATIVE_OPACITY_NOT_SUPPORTED_ON_THIS_FACE                       10134
#define IDS_TVP_SRC_RECT_OUT_OF_BITMAP                                            10135
#define IDS_TVP_BOX_BLUR_AREA_MUST_CONTAIN_CENTER_PIXEL                           10136
#define IDS_TVP_BOX_BLUR_AREA_MUST_BE_SMALLER_THAN16MILLION                       10137
#define IDS_TVP_CANNOT_CHANGE_FOCUS_IN_PROCESSING_FOCUS                           10138
#define IDS_TVP_WINDOW_HAS_NO_LAYER                                               10139
#define IDS_TVP_WINDOW_HAS_ALREADY_PRIMARY_LAYER                                  10140
#define IDS_TVP_SPECIFIED_EVENT_NEEDS_PARAMETER                                   10141
#define IDS_TVP_SPECIFIED_EVENT_NEEDS_PARAMETER2                                  10142
#define IDS_TVP_SPECIFIED_EVENT_NAME_IS_UNKNOWN                                   10143
#define IDS_TVP_OUT_OF_RECTANGLE                                                  10144
#define IDS_TVP_INVALID_METHOD_IN_UPDATING                                        10145
#define IDS_TVP_CANNOT_CREATE_INSTANCE                                            10146
#define IDS_TVP_UNKNOWN_WAVE_FORMAT                                               10147
#define IDS_TVP_CURRENT_TRANSITION_MUST_BE_STOPPING                               10148
#define IDS_TVP_TRANS_HANDLER_ERROR                                               10149
#define IDS_TVP_TRANS_ALREADY_REGISTERED                                          10150
#define IDS_TVP_CANNOT_FIND_TRANS_HANDER                                          10151
#define IDS_TVP_SPECIFY_TRANSITION_SOURCE                                         10152
#define IDS_TVP_LAYER_CANNOT_HAVE_IMAGE                                           10153
#define IDS_TVP_TRANSITION_SOURCE_AND_DESTINATION_MUST_HAVE_IMAGE                 10154
#define IDS_TVP_CANNOT_LOAD_RULE_GRAPHIC                                          10155
#define IDS_TVP_SPECIFY_OPTION                                                    10156
#define IDS_TVP_TRANSITION_LAYER_SIZE_MISMATCH                                    10157
#define IDS_TVP_TRANSITION_MUTUAL_SOURCE                                          10158
#define IDS_TVP_HOLD_DESTINATION_ALPHA_PARAMETER_IS_NOW_DEPRECATED                10159
#define IDS_TVP_CANNOT_CONNECT_MULTIPLE_WAVE_SOUND_BUFFER_AT_ONCE                 10160
#define IDS_TVP_INVALID_WINDOW_SIZE_MUST_BE_IN64TO32768                           10161
#define IDS_TVP_INVALID_OVERLAP_COUNT_MUST_BE_IN2TO32                             10162
#define IDS_TVP_CURRENTLY_ASYNC_LOAD_BITMAP                                       10163
#define IDS_TVP_FAILD_CLIPBOARD_COPY                                              10164
#define IDS_TVP_INVALID_UTF16TO_UTF8                                              10165
#define IDS_TVP_INFO_LOADING_STARTUP_SCRIPT                                       10166
#define IDS_TVP_INFO_STARTUP_SCRIPT_ENDED                                         10167
#define IDS_TVP_TJS_CHAR_MUST_BE_TWO_OR_FOUR                                      10168
#define IDS_TVP_MEDIA_NAME_HAD_ALREADY_BEEN_REGISTERED                            10169
#define IDS_TVP_MEDIA_NAME_IS_NOT_REGISTERED                                      10170
#define IDS_TVP_INFO_REBUILDING_AUTO_PATH                                         10171
#define IDS_TVP_INFO_TOTAL_FILE_FOUND_AND_ACTIVATED                               10172
#define IDS_TVP_ERROR_IN_RETRIEVING_SYSTEM_ON_ACTIVATE_ON_DEACTIVATE              10173
#define IDS_TVP_THE_HOST_IS_NOT_A16BIT_UNICODE_SYSTEM                             10174
#define IDS_TVP_INFO_TRYING_TO_READ_XP3VIRTUAL_FILE_SYSTEM_INFORMATION_FROM       10175
#define IDS_TVP_SPECIFIED_STORAGE_HAD_BEEN_PROTECTED                              10176
#define IDS_TVP_INFO_FAILED                                                       10177
#define IDS_TVP_INFO_DONE_WITH_CONTAINS                                           10178
#define IDS_TVP_SEPARATOR_CRLF                                                    10179
#define IDS_TVP_SEPARATOR_CR                                                      10180
#define IDS_TVP_DEFAULT_FONT_NAME                                                 10181
#define IDS_TVP_CANNOT_OPEN_FONT_FILE                                             10182
#define IDS_TVP_FONT_CANNOT_BE_USED                                               10183
#define IDS_TVP_FONT_RASTERIZE_ERROR                                              10184
#define IDS_TVP_BIT_FIELDS_NOT_SUPPORTED                                          10185
#define IDS_TVP_COMPRESSED_BMP_NOT_SUPPORTED                                      10186
#define IDS_TVP_UNSUPPORTED_COLOR_MODE_FOR_PALETT_IMAGE                           10187
#define IDS_TVP_NOT_WINDOWS_BMP                                                   10188
#define IDS_TVP_UNSUPPORTED_HEADER_VERSION                                        10189
#define IDS_TVP_INFO_TOUCHING                                                     10190
#define IDS_TVP_ABORTED_TIME_OUT                                                  10191
#define IDS_TVP_ABORTED_LIMIT_BYTE                                                10192
#define IDS_TVP_FAILD_GLYPH_FOR_DRAW_GLYPH                                        10193
#define IDS_TVP_LAYER_OBJECT_IS_NOT_PROPERLY_CONSTRUCTED                          10194
#define IDS_TVP_UNKNOWN_UPDATE_TYPE                                               10195
#define IDS_TVP_UNKNOWN_TRANSITION_TYPE                                           10196
#define IDS_TVP_UNSUPPORTED_UPDATE_TYPE_TUT_GIVE_UPDATE                           10197
#define IDS_TVP_ERROR_CODE                                                        10198
#define IDS_TVP_UNSUPPORTED_JPEG_PALETTE                                          10199
#define IDS_TVP_LIBPNG_ERROR                                                      10200
#define IDS_TVP_UNSUPPORTED_COLOR_TYPE_PALETTE                                    10201
#define IDS_TVP_UNSUPPORTED_COLOR_TYPE                                            10202
#define IDS_TVP_TOO_LARGE_IMAGE                                                   10203
#define IDS_TVP_PNG_SAVE_ERROR                                                    10204
#define IDS_TVP_TLG_UNSUPPORTED_UNIVERSAL_TRANSITION_RULE                         10205
#define IDS_TVP_UNSUPPORTED_COLOR_COUNT                                           10206
#define IDS_TVP_DATA_FLAG_MUST_BE_ZERO                                            10207
#define IDS_TVP_UNSUPPORTED_COLOR_TYPE_COLON                                      10208
#define IDS_TVP_UNSUPPORTED_EXTERNAL_GOLOMB_BIT_LENGTH_TABLE                      10209
#define IDS_TVP_UNSUPPORTED_ENTROPY_CODING_METHOD                                 10210
#define IDS_TVP_INVALID_TLG_HEADER_OR_VERSION                                     10211
#define IDS_TVP_TLG_MALFORMED_TAG_MISSION_COLON_AFTER_NAME_LENGTH                 10212
#define IDS_TVP_TLG_MALFORMED_TAG_MISSION_EQUALS_AFTER_NAME                       10213
#define IDS_TVP_TLG_MALFORMED_TAG_MISSION_COLON_AFTER_VAUE_LENGTH                 10214
#define IDS_TVP_TLG_MALFORMED_TAG_MISSION_COMMA_AFTER_TAG                         10215
#define IDS_TVP_FILE_SIZE_IS_ZERO                                                 10216
#define IDS_TVP_MEMORY_ALLOCATION_ERROR                                           10217
#define IDS_TVP_FILE_READ_ERROR                                                   10218
#define IDS_TVP_INVALID_PRERENDERED_FONT_FILE                                     10219
#define IDS_TVP_NOT16BIT_UNICODE_FONT_FILE                                        10220
#define IDS_TVP_INVALID_HEADER_VERSION                                            10221
#define IDS_TVP_TLG_INSUFFICIENT_MEMORY                                           10222
#define IDS_TVP_TLG_TOO_LARGE_BIT_LENGTH                                          10223
#define IDS_TVP_CANNOT_RETRIVE_INTERFACE_FROM_DRAW_DEVICE                         10224
#define IDS_TVP_SCRIPT_EXCEPTION_RAISED                                           10225
#define IDS_TVP_HARDWARE_EXCEPTION_RAISED                                         10226
#define IDS_TVP_MAIN_CDPNAME                                                      10227
#define IDS_TVP_EXCEPTION_CDPNAME                                                 10228
#define IDS_TVP_CANNNOT_LOCATE_UIDLLFOR_FOLDER_SELECTION                          10229
#define IDS_TVP_INVALID_UIDLL                                                     10230
#define IDS_TVP_INVALID_BPP                                                       10231
#define IDS_TVP_CANNOT_LOAD_PLUGIN                                                10232
#define IDS_TVP_NOT_VALID_PLUGIN                                                  10233
#define IDS_TVP_PLUGIN_UNINIT_FAILED                                              10234
#define IDS_TVP_CANNNOT_LINK_PLUGIN_WHILE_PLUGIN_LINKING                          10235
#define IDS_TVP_NOT_SUSIE_PLUGIN                                                  10236
#define IDS_TVP_SUSIE_PLUGIN_ERROR                                                10237
#define IDS_TVP_CANNOT_RELEASE_PLUGIN                                             10238
#define IDS_TVP_NOT_LOADED_PLUGIN                                                 10239
#define IDS_TVP_CANNOT_ALLOCATE_BITMAP_BITS                                       10240
#define IDS_TVP_SCAN_LINE_RANGE_OVER                                              10241
#define IDS_TVP_PLUGIN_ERROR                                                      10242
#define IDS_TVP_INVALID_CDDADRIVE                                                 10243
#define IDS_TVP_CDDADRIVE_NOT_FOUND                                               10244
#define IDS_TVP_MCIERROR                                                          10245
#define IDS_TVP_INVALID_SMF                                                       10246
#define IDS_TVP_MALFORMED_MIDIMESSAGE                                             10247
#define IDS_TVP_CANNOT_INIT_DIRECT_SOUND                                          10248
#define IDS_TVP_CANNOT_CREATE_DSSECONDARY_BUFFER                                  10249
#define IDS_TVP_INVALID_LOOP_INFORMATION                                          10250
#define IDS_TVP_NOT_CHILD_MENU_ITEM                                               10251
#define IDS_TVP_CANNOT_INIT_DIRECT3D                                              10252
#define IDS_TVP_CANNOT_FIND_DISPLAY_MODE                                          10253
#define IDS_TVP_CANNOT_SWITCH_TO_FULL_SCREEN                                      10254
#define IDS_TVP_INVALID_PROPERTY_IN_FULL_SCREEN                                   10255
#define IDS_TVP_INVALID_METHOD_IN_FULL_SCREEN                                     10256
#define IDS_TVP_CANNOT_LOAD_CURSOR                                                10257
#define IDS_TVP_CANNOT_LOAD_KR_MOVIE_DLL                                          10258
#define IDS_TVP_INVALID_KR_MOVIE_DLL                                              10259
#define IDS_TVP_ERROR_IN_KR_MOVIE_DLL                                             10260
#define IDS_TVP_WINDOW_ALREADY_MISSING                                            10261
#define IDS_TVP_PRERENDERED_FONT_MAPPING_FAILED                                   10262
#define IDS_TVP_CONFIG_FAIL_ORIGINAL_FILE_CANNOT_BE_REWRITTEN                     10263
#define IDS_TVP_CONFIG_FAIL_TEMP_EXE_NOT_ERASED                                   10264
#define IDS_TVP_EXECUTION_FAIL                                                    10265
#define IDS_TVP_PLUGIN_UNBOUND_FUNCTION_ERROR                                     10266
#define IDS_TVP_EXCEPTION_HAD_BEEN_OCCURED                                        10267
#define IDS_TVP_CONSOLE_RESULT                                                    10268
#define IDS_TVP_INFO_LISTING_FILES                                                10269
#define IDS_TVP_INFO_TOTAL_PHYSICAL_MEMORY                                        10270
#define IDS_TVP_INFO_SELECTED_PROJECT_DIRECTORY                                   10271
#define IDS_TVP_TOO_SMALL_EXECUTABLE_SIZE                                         10272
#define IDS_TVP_INFO_LOADING_EXECUTABLE_EMBEDDED_OPTIONS_FAILED                   10273
#define IDS_TVP_INFO_LOADING_EXECUTABLE_EMBEDDED_OPTIONS_SUCCEEDED                10274
#define IDS_TVP_FILE_NOT_FOUND                                                    10275
#define IDS_TVP_INFO_LOADING_CONFIGURATION_FILE_FAILED                            10276
#define IDS_TVP_INFO_LOADING_CONFIGURATION_FILE_SUCCEEDED                         10277
#define IDS_TVP_INFO_DATA_PATH_DOES_NOT_EXIST_TRYING_TO_MAKE_IT                   10278
#define IDS_TVP_OK                                                                10279
#define IDS_TVP_FAILD                                                             10280
#define IDS_TVP_INFO_DATA_PATH                                                    10281
#define IDS_TVP_INFO_SPECIFIED_OPTION_EARLIER_ITEM_HAS_MORE_PRIORITY              10282
#define IDS_TVP_NONE                                                              10283
#define IDS_TVP_INFO_CPU_CLOCK_ROUGHLY                                            10284
#define IDS_TVP_PROGRAM_STARTED_ON                                                10285
#define IDS_TVP_KIRIKIRI                                                          10286
#define IDS_TVP_UNKNOWN_ERROR                                                     10287
#define IDS_TVP_EXIT_CODE                                                         10288
#define IDS_TVP_FATAL_ERROR                                                       10289
#define IDS_TVP_ENABLE_DIGITIZER                                                  10290
#define IDS_TVP_TOUCH_INTEGRATED_TOUCH                                            10291
#define IDS_TVP_TOUCH_EXTERNAL_TOUCH                                              10292
#define IDS_TVP_TOUCH_INTEGRATED_PEN                                              10293
#define IDS_TVP_TOUCH_EXTERNAL_PEN                                                10294
#define IDS_TVP_TOUCH_MULTI_INPUT                                                 10295
#define IDS_TVP_TOUCH_READY                                                       10296
#define IDS_TVP_CPU_CHECK_FAILURE                                                 10297
#define IDS_TVP_CPU_CHECK_FAILURE_CPU_FAMILY_OR_LESSER_IS_NOT_SUPPORTED           10298
#define IDS_TVP_INFO_CPU_NUMBER                                                   10299
#define IDS_TVP_CPU_CHECK_FAILURE_NOT_SUPPRTED_CPU                                10300
#define IDS_TVP_INFO_FINALLY_DETECTED_CPU_FEATURES                                10301
#define IDS_TVP_CPU_CHECK_FAILURE_NOT_SUPPORTED_CPU                               10302
#define IDS_TVP_INFO_CPU_CLOCK                                                    10303
#define IDS_TVP_LAYER_BITMAP_BUFFER_UNDERRUN_DETECTED_CHECK_YOUR_DRAWING_CODE     10304
#define IDS_TVP_LAYER_BITMAP_BUFFER_OVERRUN_DETECTED_CHECK_YOUR_DRAWING_CODE      10305
#define IDS_TVP_FAILD_TO_CREATE_DIRECT3D                                          10306
#define IDS_TVP_FAILD_TO_DECIDE_BACKBUFFER_FORMAT                                 10307
#define IDS_TVP_FAILD_TO_CREATE_DIRECT3DDEVICE                                    10308
#define IDS_TVP_FAILD_TO_SET_VIEWPORT                                             10309
#define IDS_TVP_FAILD_TO_SET_RENDER_STATE                                         10310
#define IDS_TVP_WARNING_IMAGE_SIZE_TOO_LARGE_MAY_BE_CANNOT_CREATE_TEXTURE         10311
#define IDS_TVP_USE_POWER_OF_TWO_SURFACE                                          10312
#define IDS_TVP_CANNOT_ALLOCATE_D3DOFF_SCREEN_SURFACE                             10313
#define IDS_TVP_BASIC_DRAW_DEVICE_FAILED_TO_CREATE_DIRECT3DDEVICES                10314
#define IDS_TVP_BASIC_DRAW_DEVICE_FAILED_TO_CREATE_DIRECT3DDEVICES_UNKNOWN_REASON 10315
#define IDS_TVP_BASIC_DRAW_DEVICE_TEXTURE_HAS_ALREADY_BEEN_LOCKED                 10316
#define IDS_TVP_INTERNAL_ERROR_RESULT                                             10317
#define IDS_TVP_BASIC_DRAW_DEVICE_INF_POLYGON_DRAWING_FAILED                      10318
#define IDS_TVP_BASIC_DRAW_DEVICE_INF_DIRECT3DDEVICE_PRESENT_FAILED               10319
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_RESTART                10320
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_BAD_FLAGS              10321
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_BAD_PARAM              10322
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_FAILED                 10323
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_BAD_MODE               10324
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_DISP_CHANGE_NOT_UPDATED            10325
#define IDS_TVP_CHANGE_DISPLAY_SETTINGS_FAILED_UNKNOWN_REASON                     10326
#define IDS_TVP_FAILED_TO_CREATE_SCREEN_DC                                        10327
#define IDS_TVP_FAILED_TO_CREATE_OFFSCREEN_BITMAP                                 10328
#define IDS_TVP_FAILED_TO_CREATE_OFFSCREEN_DC                                     10329
#define IDS_TVP_INFO_SUSIE_PLUGIN_INFO                                            10330
#define IDS_TVP_SUSIE_PLUGIN_UNSUPPORTED_BITMAP_HEADER                            10331
#define IDS_TVP_BASIC_DRAW_DEVICE_FAILED_TO_CREATE_DIRECT3DDEVICE                 10332
#define IDS_TVP_BASIC_DRAW_DEVICE_FAILED_TO_CREATE_DIRECT3DDEVICE_UNKNOWN_REASON  10333
#define IDS_TVP_COULD_NOT_CREATE_ANY_DRAW_DEVICE                                  10334
#define IDS_TVP_BASIC_DRAW_DEVICE_DOES_NOT_SUPPORTE_LAYER_MANAGER_MORE_THAN_ONE   10335
#define IDS_TVP_INVALID_VIDEO_SIZE                                                10336
#define IDS_TVP_ROUGH_VSYNC_INTERVAL_READ_FROM_API                                10337
#define IDS_TVP_ROUGH_VSYNC_INTERVAL_STILL_SEEMS_WRONG                            10338
#define IDS_TVP_INFO_FOUND_DIRECT3DINTERFACE                                      10339
#define IDS_TVP_INFO_FAILD                                                        10340
#define IDS_TVP_INFO_DIRECT3D                                                     10341
#define IDS_TVP_CANNOT_LOAD_D3DDLL                                                10342
#define IDS_TVP_NOT_FOUND_DIRECT3DCREATE                                          10343
#define IDS_TVP_INFO_ENVIRONMENT_USING                                            10344
#define IDS_TVP_INFO_SEARCH_BEST_FULLSCREEN_RESOLUTION                            10345
#define IDS_TVP_INFO_CONDITION_PREFERRED_SCREEN_MODE                              10346
#define IDS_TVP_INFO_CONDITION_MODE                                               10347
#define IDS_TVP_INFO_CONDITION_ZOOM_MODE                                          10348
#define IDS_TVP_INFO_ENVIRONMENT_DEFAULT_SCREEN_MODE                              10349
#define IDS_TVP_INFO_ENVIRONMENT_DEFAULT_SCREEN_ASPECT_RATIO                      10350
#define IDS_TVP_INFO_ENVIRONMENT_AVAILABLE_DISPLAY_MODES                          10351
#define IDS_TVP_INFO_NOT_FOUND_SCREEN_MODE_FROM_DRIVER                            10352
#define IDS_TVP_INFO_RESULT_CANDIDATES                                            10353
#define IDS_TVP_INFO_TRY_SCREEN_MODE                                              10354
#define IDS_TVP_ALL_SCREEN_MODE_ERROR                                             10355
#define IDS_TVP_INFO_CHANGE_SCREEN_MODE_SUCCESS                                   10356
#define IDS_TVP_SELECT_XP3FILE_OR_FOLDER                                          10357
#define IDS_TVP_D3D_ERR_DEVICE_LOST                                               10358
#define IDS_TVP_D3D_ERR_DRIVER_IINTERNAL_ERROR                                    10359
#define IDS_TVP_D3D_ERR_INVALID_CALL                                              10360
#define IDS_TVP_D3D_ERR_OUT_OF_VIDEO_MEMORY                                       10361
#define IDS_TVP_D3D_ERR_OUT_OF_MEMORY                                             10362
#define IDS_TVP_D3D_ERR_WRONG_TEXTURE_FORMAT                                      10363
#define IDS_TVP_D3D_ERR_UNSUPORTED_COLOR_OPERATION                                10364
#define IDS_TVP_D3D_ERR_UNSUPORTED_COLOR_ARG                                      10365
#define IDS_TVP_D3D_ERR_UNSUPORTED_AALPHT_OPERATION                               10366
#define IDS_TVP_D3D_ERR_UNSUPORTED_ALPHA_ARG                                      10367
#define IDS_TVP_D3D_ERR_TOO_MANY_OPERATIONS                                       10368
#define IDS_TVP_D3D_ERR_CONFLICTIONING_TEXTURE_FILTER                             10369
#define IDS_TVP_D3D_ERR_UNSUPORTED_FACTOR_VALUE                                   10370
#define IDS_TVP_D3D_ERR_CONFLICTIONING_RENDER_STATE                               10371
#define IDS_TVP_D3D_ERR_UNSUPPORTED_TEXTURE_FILTER                                10372
#define IDS_TVP_D3D_ERR_CONFLICTIONING_TEXTURE_PALETTE                            10373
#define IDS_TVP_D3D_ERR_NOT_FOUND                                                 10374
#define IDS_TVP_D3D_ERR_MORE_DATA                                                 10375
#define IDS_TVP_D3D_ERR_DEVICE_NOT_RESET                                          10376
#define IDS_TVP_D3D_ERR_NOT_AVAILABLE                                             10377
#define IDS_TVP_D3D_ERR_INVALID_DEVICE                                            10378
#define IDS_TVP_D3D_ERR_DRIVER_INVALID_CALL                                       10379
#define IDS_TVP_D3D_ERR_WAS_STILL_DRAWING                                         10380
#define IDS_TVP_D3D_ERR_DEVICE_HUNG                                               10381
#define IDS_TVP_D3D_ERR_UNSUPPORTED_OVERLAY                                       10382
#define IDS_TVP_D3D_ERR_UNSUPPORTED_OVERLAY_FORMAT                                10383
#define IDS_TVP_D3D_ERR_CANNOT_PROTECT_CONTENT                                    10384
#define IDS_TVP_D3D_ERR_UNSUPPORTED_CRYPTO                                        10385
#define IDS_TVP_D3D_ERR_PRESENT_STATISTICS_DIS_JOINT                              10386
#define IDS_TVP_D3D_ERR_DEVICE_REMOVED                                            10387
#define IDS_TVP_D3D_OK_NO_AUTO_GEN                                                10388
#define IDS_TVP_D3D_ERR_FAIL                                                      10389
#define IDS_TVP_D3D_ERR_INVALID_ARG                                               10390
#define IDS_TVP_D3D_UNKNOWN_ERROR                                                 10391
#define IDS_TVP_EXCEPTION_ACCESS_VIOLATION                                        10392
#define IDS_TVP_EXCEPTION_BREAKPOINT                                              10393
#define IDS_TVP_EXCEPTION_DATATYPE_MISALIGNMENT                                   10394
#define IDS_TVP_EXCEPTION_SINGLE_STEP                                             10395
#define IDS_TVP_EXCEPTION_ARRAY_BOUNDS_EXCEEDED                                   10396
#define IDS_TVP_EXCEPTION_FLT_DENORMAL_OPERAND                                    10397
#define IDS_TVP_EXCEPTION_FLT_DIVIDE_BY_ZERO                                      10398
#define IDS_TVP_EXCEPTION_FLT_INEXACT_RESULT                                      10399
#define IDS_TVP_EXCEPTION_FLT_INVALID_OPERATION                                   10400
#define IDS_TVP_EXCEPTION_FLT_OVERFLOW                                            10401
#define IDS_TVP_EXCEPTION_FLT_STACK_CHECK                                         10402
#define IDS_TVP_EXCEPTION_FLT_UNDERFLOW                                           10403
#define IDS_TVP_EXCEPTION_INT_DIVIDE_BY_ZERO                                      10404
#define IDS_TVP_EXCEPTION_INT_OVERFLOW                                            10405
#define IDS_TVP_EXCEPTION_PRIV_INSTRUCTION                                        10406
#define IDS_TVP_EXCEPTION_NONCONTINUABLE_EXCEPTION                                10407
#define IDS_TVP_EXCEPTION_GUARD_PAGE                                              10408
#define IDS_TVP_EXCEPTION_ILLEGAL_INSTRUCTION                                     10409
#define IDS_TVP_EXCEPTION_IN_PAGE_ERROR                                           10410
#define IDS_TVP_EXCEPTION_INVALID_DISPOSITION                                     10411
#define IDS_TVP_EXCEPTION_INVALID_HANDLE                                          10412
#define IDS_TVP_EXCEPTION_STACK_OVERFLOW                                          10413
#define IDS_TVP_EXCEPTION_UNWIND_CCONSOLIDATE                                     10414
#define IDS_TVP_CANNOT_SHOW_MODAL_AREADY_SHOWED                                   10415
#define IDS_TVP_CANNOT_SHOW_MODAL_SINGLE_WINDOW                                   10416
#endif
