(const) %[
  "hash" => "d56b71cbb84a9e184832b49bc998e61d",
  "name" => "s205.txt",
  "outlines" => (const) [],
  "scenes" => (const) [
    (const) %[
      "firstLine" => 0,
      "label" => "*start",
      "lines" => (const) [
        (const) [
          1,
          (const) %[
            "data" => (const) [],
            "env" => (const) %[
              "action" => (const) [
                void,
                void
              ],
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          void,
          1,
          1
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) [
              "init",
              0
            ],
            (const) %[
              "action" => (const) [
                void
              ],
              "name" => "env"
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              (const) %[
                "mode" => 0,
                "name" => "env"
              ]
            ]
          ]
        ],
        (const) [
          2,
          (const) %[
            "data" => (const) [],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          void,
          void,
          1
        ],
        (const) [
          "meswinload",
          "page",
          "both"
        ],
        (const) [
          3,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ],
                    (const) [
                      "xpos",
                      -2800
                    ],
                    (const) [
                      "zoomy",
                      300
                    ],
                    (const) [
                      "ypos",
                      500
                    ],
                    (const) [
                      "zoomx",
                      300
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_美亜の部屋_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "美亜.stand",
                      "options" => (const) %[
                        "dress" => "夏服",
                        "face" => "困惑",
                        "pose" => "正面"
                      ]
                    ],
                    "posName" => "前"
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          void,
          void,
          1
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) [
              "new",
              "bg",
              "stage"
            ],
            (const) [
              "new",
              "美亜",
              "character"
            ],
            (const) %[
              "action" => (const) [
                (const) [
                  "leveloffset",
                  ""
                ],
                void,
                (const) [
                  "xpos",
                  0
                ],
                void,
                (const) [
                  "ypos",
                  0
                ],
                (const) [
                  "zpos",
                  0.000000
                ],
                (const) [
                  "order",
                  0
                ]
              ],
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "困惑",
                    "pose" => "正面"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 1,
              "type" => void
            ],
            (const) %[
              "action" => (const) [
                void,
                (const) [
                  "zpos",
                  233.333333
                ],
                void,
                (const) [
                  "leveloffset",
                  ""
                ],
                (const) [
                  "zoomx",
                  300
                ],
                (const) [
                  "zoomy",
                  300
                ],
                (const) [
                  "xpos",
                  -2800
                ],
                (const) [
                  "ypos",
                  500
                ]
              ],
              "class" => "stage",
              "link" => void,
              "name" => "bg",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "館_美亜の部屋_消灯",
                  "redraw" => (const) [
                    (const) [
                      "doBoxBlur",
                      0,
                      0
                    ],
                    (const) [
                      "doBoxBlur",
                      0,
                      0
                    ]
                  ]
                ],
                "posName" => void
              ],
              "showmode" => 1,
              "type" => void
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              void,
              (const) %[
                "mode" => 0,
                "name" => "env"
              ]
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 250
          ]
        ],
        "cg_美亜.stand",
        (const) [
          4,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ],
                    (const) [
                      "xpos",
                      -2800
                    ],
                    (const) [
                      "zoomy",
                      300
                    ],
                    (const) [
                      "ypos",
                      500
                    ],
                    (const) [
                      "zoomx",
                      300
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_美亜の部屋_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "美亜.stand",
                      "options" => (const) %[
                        "dress" => "夏服",
                        "face" => "困惑",
                        "pose" => "正面"
                      ]
                    ],
                    "posName" => "前"
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          1,
          void,
          15,
          80
        ],
        (const) [
          "quake",
          "time",
          "500",
          "hmax",
          "5",
          "vmax",
          "5"
        ],
        1,
        (const) [
          5,
          1,
          2,
          void,
          22,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "美亜",
              "showmode" => 2
            ],
            (const) %[
              "action" => (const) [
                (const) [
                  "zoomx",
                  100
                ],
                (const) [
                  "zoomy",
                  100
                ],
                (const) [
                  "xpos",
                  0
                ],
                (const) [
                  "ypos",
                  0
                ]
              ],
              "name" => "bg",
              "showmode" => 3
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "rule" => "map18b",
            "time" => 500,
            "vague" => "300"
          ]
        ],
        2,
        (const) [
          6,
          2,
          3,
          void,
          25,
          64
        ],
        3,
        (const) [
          7,
          3,
          void,
          void,
          25
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "zpos",
                  0.000000
                ],
                (const) [
                  "originy",
                  300
                ],
                (const) [
                  "originx",
                  -450
                ],
                void,
                (const) [
                  "zpos",
                  0
                ],
                (const) [
                  "xpos",
                  -75.000000
                ],
                (const) [
                  "ypos",
                  -2.000000
                ],
                (const) [
                  "zoomx",
                  45
                ],
                (const) [
                  "zoomy",
                  45
                ],
                (const) [
                  "visvalue",
                  0
                ],
                (const) [
                  "visvalue",
                  (const) [
                    (const) %[
                      "delay" => void,
                      "handler" => "MoveAction",
                      "start" => 0,
                      "time" => 250,
                      "value" => 100
                    ]
                  ]
                ]
              ],
              "class" => "msgwin",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "clip" => (const) %[
                  "image" => "facemask"
                ],
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "困惑",
                    "pose" => "正面"
                  ]
                ],
                "posName" => "顔"
              ],
              "showmode" => 1,
              "trans" => (const) %[
                "method" => "",
                "sync" => 1,
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              (const) %[
                "mode" => 1,
                "name" => "美亜"
              ]
            ]
          ]
        ],
        (const) [
          8,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_美亜の部屋_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "originy",
                      300
                    ],
                    (const) [
                      "xpos",
                      -75.000000
                    ],
                    (const) [
                      "zoomy",
                      45
                    ],
                    (const) [
                      "ypos",
                      -2.000000
                    ],
                    (const) [
                      "zoomx",
                      45
                    ],
                    (const) [
                      "originx",
                      -450
                    ]
                  ],
                  "class" => "msgwin",
                  "name" => "美亜",
                  "redraw" => (const) %[
                    "clip" => (const) %[
                      "image" => "facemask"
                    ],
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "美亜.stand",
                      "options" => (const) %[
                        "dress" => "夏服",
                        "face" => "困惑",
                        "pose" => "正面"
                      ]
                    ],
                    "posName" => "顔"
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          4,
          void,
          31,
          64
        ],
        4,
        (const) [
          9,
          4,
          5,
          void,
          33,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "hideact" => (const) [
                (const) [
                  "visvalue",
                  (const) [
                    (const) %[
                      "delay" => void,
                      "handler" => "MoveAction",
                      "time" => 250,
                      "value" => 0
                    ]
                  ]
                ]
              ],
              "name" => "美亜",
              "showmode" => 2,
              "trans" => (const) %[
                "method" => "",
                "sync" => 1,
                "time" => 250
              ]
            ]
          ]
        ],
        5,
        (const) [
          10,
          5,
          6,
          void,
          36,
          64
        ],
        6,
        (const) [
          11,
          6,
          7,
          void,
          46,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "originy",
                  300
                ],
                (const) [
                  "xpos",
                  -75.000000
                ],
                (const) [
                  "zoomy",
                  45
                ],
                (const) [
                  "ypos",
                  -2.000000
                ],
                (const) [
                  "zoomx",
                  45
                ],
                (const) [
                  "originx",
                  -450
                ],
                (const) [
                  "xpos",
                  0
                ],
                (const) [
                  "originy",
                  0
                ],
                (const) [
                  "originx",
                  0
                ],
                void,
                (const) [
                  "zoomx",
                  100
                ],
                (const) [
                  "zoomy",
                  100
                ],
                (const) [
                  "ypos",
                  0
                ],
                (const) [
                  "zpos",
                  0.000000
                ],
                (const) [
                  "order",
                  0
                ]
              ],
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "悲しみ２",
                    "pose" => "基本"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 1,
              "type" => void
            ],
            (const) %[
              "action" => (const) [
                (const) [
                  "zoomx",
                  300
                ],
                (const) [
                  "zoomy",
                  300
                ],
                (const) [
                  "xpos",
                  -2800
                ],
                (const) [
                  "ypos",
                  500
                ]
              ],
              "name" => "bg",
              "showmode" => 3
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "rule" => "map18",
            "time" => 500,
            "vague" => "300"
          ]
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) [
              "new",
              "bgm",
              "bgm"
            ],
            (const) %[
              "name" => "bgm",
              "replay" => (const) %[
                "filename" => "bgm04",
                "loop" => 1,
                "start" => void,
                "state" => 1,
                "volume" => 100.000000
              ],
              "trans" => (const) %[
                "method" => "",
                "time" => 0
              ]
            ]
          ]
        ],
        "bgm_BGM04",
        7,
        (const) [
          12,
          7,
          8,
          void,
          48,
          64
        ],
        8,
        (const) [
          13,
          8,
          9,
          void,
          51,
          64
        ],
        9,
        (const) [
          14,
          9,
          10,
          void,
          57,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "悲しみ",
                    "pose" => "正面"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 3,
              "trans" => (const) %[
                "method" => "crossfade",
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 250
          ]
        ],
        10,
        (const) [
          15,
          10,
          void,
          void,
          57
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) [
              "new",
              "se",
              "se"
            ],
            (const) %[
              "name" => "se",
              "replay" => (const) %[
                "filename" => "se095",
                "start" => void,
                "time" => 0,
                "volume" => 100.000000
              ]
            ]
          ]
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "hideact" => (const) [
                (const) [
                  "top",
                  (const) [
                    (const) %[
                      "handler" => "MoveAction",
                      "time" => 0,
                      "value" => "@"
                    ],
                    (const) %[
                      "accel" => "acdec",
                      "handler" => "MoveAction",
                      "time" => 1000,
                      "value" => "@+100"
                    ]
                  ]
                ],
                (const) [
                  "visvalue",
                  (const) [
                    (const) %[
                      "handler" => "MoveAction",
                      "time" => 0,
                      "value" => "100"
                    ],
                    (const) %[
                      "accel" => "acdec",
                      "handler" => "MoveAction",
                      "time" => 1000,
                      "value" => "0"
                    ]
                  ]
                ]
              ],
              "name" => "美亜",
              "showmode" => 2,
              "trans" => (const) %[
                "time" => 1000
              ]
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              (const) %[
                "mode" => 0,
                "name" => "美亜"
              ]
            ],
            "wait" => 250
          ]
        ],
        (const) [
          16,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ],
                    (const) [
                      "xpos",
                      -2800
                    ],
                    (const) [
                      "zoomy",
                      300
                    ],
                    (const) [
                      "ypos",
                      500
                    ],
                    (const) [
                      "zoomx",
                      300
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_美亜の部屋_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          void,
          void,
          58
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "zoomx",
                  150
                ],
                (const) [
                  "zoomy",
                  150
                ],
                (const) [
                  "xpos",
                  640
                ],
                (const) [
                  "xpos",
                  (const) [
                    (const) %[
                      "accel" => "-1",
                      "handler" => "MoveAction",
                      "nowait" => "true",
                      "time" => 20000,
                      "value" => -640
                    ]
                  ]
                ]
              ],
              "name" => "bg",
              "showmode" => 3
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              void,
              (const) %[
                "mode" => 0,
                "name" => "env"
              ]
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 1000
          ]
        ],
        (const) [
          17,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ],
                    (const) [
                      "xpos",
                      -640
                    ],
                    (const) [
                      "zoomy",
                      150
                    ],
                    (const) [
                      "ypos",
                      500
                    ],
                    (const) [
                      "zoomx",
                      150
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_美亜の部屋_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          11,
          void,
          69,
          64
        ],
        11,
        (const) [
          18,
          11,
          12,
          void,
          71,
          64
        ],
        12,
        (const) [
          19,
          12,
          void,
          void,
          71
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "zpos",
                  0.000000
                ],
                (const) [
                  "originy",
                  300
                ],
                (const) [
                  "originx",
                  -450
                ],
                void,
                (const) [
                  "zpos",
                  0
                ],
                (const) [
                  "xpos",
                  -70.000000
                ],
                (const) [
                  "ypos",
                  -2.000000
                ],
                (const) [
                  "zoomx",
                  45
                ],
                (const) [
                  "zoomy",
                  45
                ],
                (const) [
                  "visvalue",
                  0
                ],
                (const) [
                  "visvalue",
                  (const) [
                    (const) %[
                      "delay" => void,
                      "handler" => "MoveAction",
                      "start" => 0,
                      "time" => 250,
                      "value" => 100
                    ]
                  ]
                ]
              ],
              "class" => "msgwin",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "clip" => (const) %[
                  "image" => "facemask"
                ],
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "通常",
                    "pose" => "基本"
                  ]
                ],
                "posName" => "顔"
              ],
              "showmode" => 1,
              "trans" => (const) %[
                "method" => "",
                "sync" => 1,
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              (const) %[
                "mode" => 1,
                "name" => "美亜"
              ]
            ]
          ]
        ],
        (const) [
          20,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ],
                    (const) [
                      "xpos",
                      -640
                    ],
                    (const) [
                      "zoomy",
                      150
                    ],
                    (const) [
                      "ypos",
                      500
                    ],
                    (const) [
                      "zoomx",
                      150
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_美亜の部屋_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "originy",
                      300
                    ],
                    (const) [
                      "xpos",
                      -70.000000
                    ],
                    (const) [
                      "zoomy",
                      45
                    ],
                    (const) [
                      "ypos",
                      -2.000000
                    ],
                    (const) [
                      "zoomx",
                      45
                    ],
                    (const) [
                      "originx",
                      -450
                    ]
                  ],
                  "class" => "msgwin",
                  "name" => "美亜",
                  "redraw" => (const) %[
                    "clip" => (const) %[
                      "image" => "facemask"
                    ],
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "美亜.stand",
                      "options" => (const) %[
                        "dress" => "夏服",
                        "face" => "通常",
                        "pose" => "基本"
                      ]
                    ],
                    "posName" => "顔"
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          13,
          void,
          77,
          64
        ],
        13,
        (const) [
          21,
          13,
          14,
          void,
          80,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "hideact" => (const) [
                (const) [
                  "visvalue",
                  (const) [
                    (const) %[
                      "delay" => void,
                      "handler" => "MoveAction",
                      "time" => 250,
                      "value" => 0
                    ]
                  ]
                ]
              ],
              "name" => "美亜",
              "showmode" => 2,
              "trans" => (const) %[
                "method" => "",
                "sync" => 1,
                "time" => 250
              ]
            ]
          ]
        ],
        14,
        (const) [
          22,
          14,
          15,
          void,
          83,
          64
        ],
        15,
        (const) [
          23,
          15,
          16,
          void,
          85,
          64
        ],
        16,
        (const) [
          24,
          16,
          void,
          void,
          85
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "originy",
                  300
                ],
                (const) [
                  "xpos",
                  -70.000000
                ],
                (const) [
                  "zoomy",
                  45
                ],
                (const) [
                  "ypos",
                  -2.000000
                ],
                (const) [
                  "zoomx",
                  45
                ],
                (const) [
                  "originx",
                  -450
                ],
                (const) [
                  "visvalue",
                  0
                ],
                (const) [
                  "visvalue",
                  (const) [
                    (const) %[
                      "delay" => void,
                      "handler" => "MoveAction",
                      "start" => 0,
                      "time" => 250,
                      "value" => 100
                    ]
                  ]
                ]
              ],
              "class" => "msgwin",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "clip" => (const) %[
                  "image" => "facemask"
                ],
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "悲しみ",
                    "pose" => "基本"
                  ]
                ],
                "posName" => "顔"
              ],
              "showmode" => 1,
              "trans" => (const) %[
                "method" => "",
                "sync" => 1,
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              (const) %[
                "mode" => 1,
                "name" => "美亜"
              ]
            ]
          ]
        ],
        (const) [
          25,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ],
                    (const) [
                      "xpos",
                      -640
                    ],
                    (const) [
                      "zoomy",
                      150
                    ],
                    (const) [
                      "ypos",
                      500
                    ],
                    (const) [
                      "zoomx",
                      150
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_美亜の部屋_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "originy",
                      300
                    ],
                    (const) [
                      "xpos",
                      -70.000000
                    ],
                    (const) [
                      "zoomy",
                      45
                    ],
                    (const) [
                      "ypos",
                      -2.000000
                    ],
                    (const) [
                      "zoomx",
                      45
                    ],
                    (const) [
                      "originx",
                      -450
                    ]
                  ],
                  "class" => "msgwin",
                  "name" => "美亜",
                  "redraw" => (const) %[
                    "clip" => (const) %[
                      "image" => "facemask"
                    ],
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "美亜.stand",
                      "options" => (const) %[
                        "dress" => "夏服",
                        "face" => "悲しみ",
                        "pose" => "基本"
                      ]
                    ],
                    "posName" => "顔"
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          17,
          void,
          91,
          64
        ],
        17,
        (const) [
          26,
          17,
          18,
          void,
          94,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "hideact" => (const) [
                (const) [
                  "visvalue",
                  (const) [
                    (const) %[
                      "delay" => void,
                      "handler" => "MoveAction",
                      "time" => 250,
                      "value" => 0
                    ]
                  ]
                ]
              ],
              "name" => "美亜",
              "showmode" => 2,
              "trans" => (const) %[
                "method" => "",
                "sync" => 1,
                "time" => 250
              ]
            ]
          ]
        ],
        18,
        (const) [
          27,
          18,
          19,
          void,
          97,
          64
        ],
        19,
        (const) [
          28,
          19,
          20,
          void,
          108,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "originy",
                  300
                ],
                (const) [
                  "xpos",
                  -70.000000
                ],
                (const) [
                  "zoomy",
                  45
                ],
                (const) [
                  "ypos",
                  -2.000000
                ],
                (const) [
                  "zoomx",
                  45
                ],
                (const) [
                  "originx",
                  -450
                ],
                (const) [
                  "xpos",
                  0
                ],
                (const) [
                  "originy",
                  0
                ],
                (const) [
                  "originx",
                  0
                ],
                void,
                (const) [
                  "zoomx",
                  100
                ],
                (const) [
                  "zoomy",
                  100
                ],
                (const) [
                  "ypos",
                  0
                ],
                (const) [
                  "zpos",
                  0.000000
                ],
                (const) [
                  "order",
                  0
                ]
              ],
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "悲しみ",
                    "pose" => "基本"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 1,
              "type" => void
            ],
            (const) %[
              "action" => (const) [
                (const) [
                  "zoomx",
                  300
                ],
                (const) [
                  "zoomy",
                  300
                ],
                (const) [
                  "xpos",
                  -2800
                ]
              ],
              "name" => "bg",
              "showmode" => 3
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "rule" => "map18",
            "time" => 500,
            "vague" => "300"
          ]
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "ypos",
                  (const) [
                    (const) %[
                      "accel" => 1,
                      "handler" => "MoveAction",
                      "time" => 500,
                      "value" => "@-10"
                    ],
                    (const) %[
                      "accel" => -1,
                      "handler" => "MoveAction",
                      "time" => 300,
                      "value" => "@-5"
                    ]
                  ]
                ]
              ],
              "name" => "美亜",
              "showmode" => 3
            ]
          ]
        ],
        20,
        (const) [
          29,
          20,
          21,
          void,
          110,
          64
        ],
        21,
        (const) [
          30,
          21,
          22,
          void,
          113,
          64
        ],
        22,
        (const) [
          31,
          22,
          23,
          void,
          116,
          64
        ],
        23,
        (const) [
          32,
          23,
          24,
          void,
          122,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "悲しみ２",
                    "pose" => "基本"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 3,
              "trans" => (const) %[
                "method" => "crossfade",
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 250
          ]
        ],
        24,
        (const) [
          33,
          24,
          25,
          void,
          124,
          64
        ],
        25,
        (const) [
          34,
          25,
          26,
          void,
          127,
          64
        ],
        26,
        (const) [
          35,
          26,
          27,
          void,
          133,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "苦しみ",
                    "pose" => "正面"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 3,
              "trans" => (const) %[
                "method" => "crossfade",
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 250
          ]
        ],
        27,
        (const) [
          36,
          27,
          28,
          void,
          135,
          64
        ],
        28,
        (const) [
          37,
          28,
          29,
          void,
          138,
          64
        ],
        29,
        (const) [
          38,
          29,
          30,
          void,
          141,
          64
        ],
        30,
        (const) [
          39,
          30,
          31,
          void,
          148,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "ypos",
                  (const) [
                    (const) %[
                      "accel" => 1,
                      "handler" => "MoveAction",
                      "time" => 500,
                      "value" => "@-10"
                    ],
                    (const) %[
                      "accel" => -1,
                      "handler" => "MoveAction",
                      "time" => 300,
                      "value" => "@-5"
                    ]
                  ]
                ]
              ],
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "悲しみ",
                    "pose" => "後ろ"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 3,
              "trans" => (const) %[
                "method" => "crossfade",
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 250
          ]
        ],
        31,
        (const) [
          40,
          31,
          32,
          void,
          151,
          64
        ],
        32,
        (const) [
          41,
          32,
          33,
          void,
          158,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "美亜",
              "showmode" => 2
            ],
            (const) %[
              "action" => (const) [
                (const) [
                  "zoomx",
                  100
                ],
                (const) [
                  "zoomy",
                  100
                ],
                (const) [
                  "xpos",
                  0
                ],
                (const) [
                  "ypos",
                  0
                ]
              ],
              "name" => "bg",
              "showmode" => 3
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "rule" => "map18b",
            "time" => 500,
            "vague" => "300"
          ]
        ],
        33,
        (const) [
          42,
          33,
          void,
          void,
          158
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "se",
              "replay" => (const) %[
                "filename" => "se051",
                "start" => void,
                "time" => 0,
                "volume" => 100.000000
              ]
            ]
          ]
        ],
        (const) [
          43,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "showmode" => 0,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "ypos",
                      -10
                    ],
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          void,
          void,
          163
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "bg",
              "showmode" => 2
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              void,
              (const) %[
                "mode" => 0,
                "name" => "env"
              ]
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "msgoff" => "true",
            "rule" => "map036",
            "time" => "1000",
            "vague" => "100"
          ],
          "msgoff",
          1
        ],
        (const) [
          44,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "showmode" => 0,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "ypos",
                      -10
                    ],
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          34,
          void,
          171,
          80
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "zpos",
                  233.333333
                ],
                void,
                (const) [
                  "leveloffset",
                  ""
                ]
              ],
              "class" => "stage",
              "link" => void,
              "name" => "bg",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "館_廊下_消灯",
                  "redraw" => (const) [
                    (const) [
                      "doBoxBlur",
                      0,
                      0
                    ],
                    (const) [
                      "doBoxBlur",
                      0,
                      0
                    ]
                  ]
                ],
                "posName" => void
              ],
              "showmode" => 1,
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "rule" => "map036",
            "time" => 1000,
            "vague" => "100"
          ]
        ],
        34,
        (const) [
          45,
          34,
          35,
          void,
          174,
          64
        ],
        35,
        (const) [
          46,
          35,
          void,
          void,
          174
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "se",
              "stop" => 1
            ]
          ]
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) [
              "new",
              "lse",
              "loopse"
            ],
            (const) %[
              "name" => "lse",
              "replay" => (const) %[
                "filename" => "se074",
                "loop" => 1,
                "start" => void,
                "state" => 1,
                "volume" => 100.000000
              ],
              "trans" => (const) %[
                "method" => "",
                "time" => 0
              ]
            ]
          ]
        ],
        (const) [
          47,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "showmode" => 0,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "ypos",
                      -10
                    ],
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          void,
          void,
          181
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "bg",
              "showmode" => 2
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              void,
              (const) %[
                "mode" => 0,
                "name" => "env"
              ]
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "msgoff" => "true",
            "rule" => "map036",
            "time" => "1000",
            "vague" => "100"
          ],
          "msgoff",
          1
        ],
        (const) [
          48,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "showmode" => 0,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "ypos",
                      -10
                    ],
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          void,
          void,
          181
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "lse",
              "replay" => (const) %[
                "filename" => "se074",
                "loop" => 1,
                "start" => void,
                "state" => 0,
                "volume" => 100.000000
              ]
            ],
            (const) %[
              "name" => "se",
              "stop" => 1
            ],
            (const) %[
              "action" => (const) [
                (const) [
                  "zpos",
                  233.333333
                ],
                void,
                (const) [
                  "leveloffset",
                  ""
                ]
              ],
              "class" => "stage",
              "link" => void,
              "name" => "bg",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "館_ホール_消灯",
                  "redraw" => (const) [
                    (const) [
                      "doBoxBlur",
                      0,
                      0
                    ],
                    (const) [
                      "doBoxBlur",
                      0,
                      0
                    ]
                  ]
                ],
                "posName" => void
              ],
              "showmode" => 1,
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "rule" => "map036",
            "time" => 1000,
            "vague" => "100"
          ]
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "se",
              "replay" => (const) %[
                "filename" => "se088",
                "start" => void,
                "time" => 0,
                "volume" => 100.000000
              ]
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              (const) %[
                "mode" => 1,
                "name" => "se"
              ]
            ],
            "wait" => 1
          ]
        ],
        (const) [
          49,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_ホール_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "ypos",
                      -10
                    ],
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          36,
          void,
          194,
          80
        ],
        36,
        (const) [
          50,
          36,
          37,
          void,
          197,
          64
        ],
        37,
        (const) [
          51,
          37,
          38,
          void,
          199,
          64
        ],
        38,
        (const) [
          52,
          38,
          void,
          void,
          199
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "se",
              "stop" => 1
            ]
          ]
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "se",
              "replay" => (const) %[
                "filename" => "se051",
                "start" => void,
                "time" => 0,
                "volume" => 100.000000
              ]
            ]
          ]
        ],
        (const) [
          53,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "showmode" => 0,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "ypos",
                      -10
                    ],
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          void,
          void,
          206
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "bg",
              "showmode" => 2
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              void,
              (const) %[
                "mode" => 0,
                "name" => "env"
              ]
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "msgoff" => "true",
            "rule" => "map036",
            "time" => "1000",
            "vague" => "100"
          ],
          "msgoff",
          1
        ],
        (const) [
          54,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "showmode" => 0,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "ypos",
                      -10
                    ],
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          39,
          void,
          214,
          80
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "zpos",
                  233.333333
                ],
                void,
                (const) [
                  "leveloffset",
                  ""
                ]
              ],
              "class" => "stage",
              "link" => void,
              "name" => "bg",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "館_厨房_消灯",
                  "redraw" => (const) [
                    (const) [
                      "doBoxBlur",
                      0,
                      0
                    ],
                    (const) [
                      "doBoxBlur",
                      0,
                      0
                    ]
                  ]
                ],
                "posName" => void
              ],
              "showmode" => 1,
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "rule" => "map036",
            "time" => 1000,
            "vague" => "100"
          ]
        ],
        39,
        (const) [
          55,
          39,
          40,
          void,
          217,
          64
        ],
        40,
        (const) [
          56,
          40,
          void,
          void,
          217
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "se",
              "stop" => 1
            ]
          ]
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "se",
              "replay" => (const) %[
                "filename" => "se092",
                "start" => void,
                "time" => 0,
                "volume" => 100.000000
              ]
            ]
          ]
        ],
        (const) [
          57,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ],
                    (const) [
                      "xpos",
                      -3600
                    ],
                    (const) [
                      "zoomy",
                      300
                    ],
                    (const) [
                      "ypos",
                      500
                    ],
                    (const) [
                      "zoomx",
                      300
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_厨房_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "ypos",
                      -10
                    ],
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          41,
          void,
          227,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "zoomx",
                  300
                ],
                (const) [
                  "zoomy",
                  300
                ],
                (const) [
                  "xpos",
                  -3600
                ],
                (const) [
                  "ypos",
                  500
                ]
              ],
              "name" => "bg",
              "showmode" => 3
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "rule" => "map18",
            "time" => 500,
            "vague" => "300"
          ]
        ],
        41,
        (const) [
          58,
          41,
          42,
          void,
          229,
          64
        ],
        42,
        (const) [
          59,
          42,
          43,
          void,
          231,
          64
        ],
        43,
        (const) [
          60,
          43,
          44,
          void,
          233,
          64
        ],
        44,
        (const) [
          61,
          44,
          45,
          void,
          235,
          64
        ],
        45,
        (const) [
          62,
          45,
          void,
          void,
          235
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "ypos",
                  -10
                ],
                (const) [
                  "zpos",
                  0.000000
                ],
                (const) [
                  "xpos",
                  0
                ],
                void,
                (const) [
                  "ypos",
                  0
                ],
                (const) [
                  "zpos",
                  0.000000
                ],
                (const) [
                  "order",
                  0
                ],
                (const) [
                  "xpos",
                  (const) [
                    (const) %[
                      "accel" => -1,
                      "handler" => "MoveAction",
                      "start" => "@-30",
                      "time" => 300,
                      "value" => "@"
                    ]
                  ]
                ],
                (const) [
                  "visvalue",
                  0
                ],
                (const) [
                  "visvalue",
                  (const) [
                    (const) %[
                      "delay" => void,
                      "handler" => "MoveAction",
                      "start" => 0,
                      "time" => 300,
                      "value" => 100
                    ]
                  ]
                ]
              ],
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "拗ね",
                    "pose" => "正面"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 1,
              "trans" => (const) %[
                "time" => 300
              ],
              "type" => void
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              (const) %[
                "mode" => 1,
                "name" => "美亜"
              ]
            ]
          ]
        ],
        (const) [
          63,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ],
                    (const) [
                      "xpos",
                      -3600
                    ],
                    (const) [
                      "zoomy",
                      300
                    ],
                    (const) [
                      "ypos",
                      500
                    ],
                    (const) [
                      "zoomx",
                      300
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_厨房_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "美亜.stand",
                      "options" => (const) %[
                        "dress" => "夏服",
                        "face" => "拗ね",
                        "pose" => "正面"
                      ]
                    ],
                    "posName" => "前"
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          46,
          void,
          241,
          64
        ],
        46,
        (const) [
          64,
          46,
          47,
          void,
          243,
          64
        ],
        47,
        (const) [
          65,
          47,
          48,
          void,
          246,
          64
        ],
        48,
        (const) [
          66,
          48,
          49,
          void,
          249,
          64
        ],
        49,
        (const) [
          67,
          49,
          50,
          void,
          256,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "通常",
                    "pose" => "正面"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 3,
              "trans" => (const) %[
                "method" => "crossfade",
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 250
          ]
        ],
        (const) [
          "delayrun",
          "vl1",
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "xpos",
                  (const) [
                    (const) %[
                      "handler" => "wait"
                    ]
                  ]
                ],
                (const) [
                  "ypos",
                  (const) [
                    (const) %[
                      "angvel" => void,
                      "cycle" => 1200,
                      "delay" => void,
                      "handler" => "SinAction",
                      "time" => 600.000000,
                      "vibration" => -10
                    ]
                  ]
                ]
              ],
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "笑顔３",
                    "pose" => "正面"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 3,
              "trans" => (const) %[
                "method" => "crossfade",
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 250
          ]
        ],
        50,
        (const) [
          68,
          50,
          51,
          void,
          258,
          64
        ],
        51,
        (const) [
          69,
          51,
          52,
          void,
          260,
          64
        ],
        52,
        (const) [
          70,
          52,
          53,
          void,
          263,
          64
        ],
        53,
        (const) [
          71,
          53,
          54,
          void,
          271,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "悲しみ２",
                    "pose" => "基本"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 3,
              "trans" => (const) %[
                "method" => "crossfade",
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 250
          ]
        ],
        (const) [
          "delayrun",
          "vl1",
          "envupdate",
          "update",
          (const) [
            (const) %[
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "苦しみ",
                    "pose" => "正面"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 3,
              "trans" => (const) %[
                "method" => "crossfade",
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 250
          ]
        ],
        54,
        (const) [
          72,
          54,
          55,
          void,
          273,
          64
        ],
        55,
        (const) [
          73,
          55,
          56,
          void,
          275,
          64
        ],
        56,
        (const) [
          74,
          56,
          57,
          void,
          278,
          64
        ],
        57,
        (const) [
          75,
          57,
          58,
          void,
          284,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "悲しみ",
                    "pose" => "後ろ"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 3,
              "trans" => (const) %[
                "method" => "crossfade",
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 250
          ]
        ],
        58,
        (const) [
          76,
          58,
          59,
          void,
          290,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "驚き",
                    "pose" => "基本"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 3,
              "trans" => (const) %[
                "method" => "crossfade",
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 250
          ]
        ],
        59,
        (const) [
          77,
          59,
          60,
          void,
          292,
          64
        ],
        60,
        (const) [
          78,
          60,
          61,
          void,
          295,
          64
        ],
        61,
        (const) [
          79,
          61,
          62,
          void,
          303,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "美亜",
              "showmode" => 2
            ],
            (const) %[
              "action" => (const) [
                (const) [
                  "zoomx",
                  100
                ],
                (const) [
                  "zoomy",
                  100
                ],
                (const) [
                  "xpos",
                  0
                ],
                (const) [
                  "ypos",
                  0
                ]
              ],
              "name" => "bg",
              "showmode" => 3
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "rule" => "map18b",
            "time" => 500,
            "vague" => "300"
          ]
        ],
        62,
        (const) [
          80,
          62,
          void,
          void,
          303
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "zpos",
                  0.000000
                ],
                (const) [
                  "xpos",
                  0
                ],
                void,
                (const) [
                  "ypos",
                  0
                ],
                (const) [
                  "zpos",
                  0.000000
                ],
                (const) [
                  "order",
                  0
                ],
                (const) [
                  "xpos",
                  (const) [
                    (const) %[
                      "accel" => -1,
                      "handler" => "MoveAction",
                      "start" => "@+30",
                      "time" => 800,
                      "value" => "@"
                    ]
                  ]
                ],
                (const) [
                  "visvalue",
                  0
                ],
                (const) [
                  "visvalue",
                  (const) [
                    (const) %[
                      "delay" => void,
                      "handler" => "MoveAction",
                      "start" => 0,
                      "time" => 800,
                      "value" => 100
                    ]
                  ]
                ]
              ],
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "通常",
                    "pose" => "基本"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 1,
              "trans" => (const) %[
                "time" => 800
              ],
              "type" => void
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              (const) %[
                "mode" => 1,
                "name" => "美亜"
              ]
            ]
          ]
        ],
        (const) [
          81,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_厨房_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "美亜.stand",
                      "options" => (const) %[
                        "dress" => "夏服",
                        "face" => "通常",
                        "pose" => "基本"
                      ]
                    ],
                    "posName" => "前"
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          63,
          void,
          310,
          64
        ],
        63,
        (const) [
          82,
          63,
          64,
          void,
          317,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "通常",
                    "pose" => "正面"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 3,
              "trans" => (const) %[
                "method" => "crossfade",
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 250
          ]
        ],
        64,
        (const) [
          83,
          64,
          void,
          void,
          317
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "bgm",
              "replay" => (const) %[
                "filename" => "bgm04",
                "loop" => 1,
                "start" => void,
                "state" => 0,
                "volume" => 100.000000
              ],
              "trans" => (const) %[
                "method" => "",
                "time" => "1500"
              ]
            ]
          ]
        ],
        (const) [
          84,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "showmode" => 0,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          void,
          void,
          319
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "美亜",
              "showmode" => 2
            ],
            (const) %[
              "name" => "bg",
              "showmode" => 2
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              void,
              (const) %[
                "mode" => 0,
                "name" => "env"
              ]
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "msgoff" => "true",
            "rule" => "map036",
            "time" => "1000",
            "vague" => "100"
          ],
          "msgoff",
          1
        ],
        (const) [
          85,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "showmode" => 0,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm04",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          void,
          void,
          319
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "se",
              "replay" => (const) %[
                "filename" => "se051",
                "start" => void,
                "time" => 0,
                "volume" => 100.000000
              ]
            ]
          ]
        ],
        (const) [
          86,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_廊下_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm05",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          65,
          void,
          332,
          80
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "zpos",
                  233.333333
                ],
                void,
                (const) [
                  "leveloffset",
                  ""
                ]
              ],
              "class" => "stage",
              "link" => void,
              "name" => "bg",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "館_廊下_消灯",
                  "redraw" => (const) [
                    (const) [
                      "doBoxBlur",
                      0,
                      0
                    ],
                    (const) [
                      "doBoxBlur",
                      0,
                      0
                    ]
                  ]
                ],
                "posName" => void
              ],
              "showmode" => 1,
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "rule" => "map036",
            "time" => 1000,
            "vague" => "100"
          ]
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "bgm",
              "replay" => (const) %[
                "filename" => "bgm05",
                "loop" => 1,
                "start" => void,
                "state" => 1,
                "volume" => 100.000000
              ],
              "trans" => (const) %[
                "method" => "",
                "time" => 0
              ]
            ]
          ]
        ],
        "bgm_BGM05",
        65,
        (const) [
          87,
          65,
          66,
          void,
          335,
          64
        ],
        66,
        (const) [
          88,
          66,
          void,
          void,
          335
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "se",
              "replay" => (const) %[
                "filename" => "se070",
                "start" => void,
                "time" => 0,
                "volume" => 100.000000
              ]
            ]
          ]
        ],
        (const) [
          89,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "showmode" => 0,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm05",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          void,
          void,
          340
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "bg",
              "showmode" => 2
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              void,
              (const) %[
                "mode" => 0,
                "name" => "env"
              ]
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "msgoff" => "true",
            "rule" => "map036",
            "time" => "1000",
            "vague" => "100"
          ],
          "msgoff",
          1
        ],
        (const) [
          90,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "showmode" => 0,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm05",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          67,
          void,
          349,
          80
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "zpos",
                  233.333333
                ],
                void,
                (const) [
                  "leveloffset",
                  ""
                ]
              ],
              "class" => "stage",
              "link" => void,
              "name" => "bg",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "館_ホール_消灯",
                  "redraw" => (const) [
                    (const) [
                      "doBoxBlur",
                      0,
                      0
                    ],
                    (const) [
                      "doBoxBlur",
                      0,
                      0
                    ]
                  ]
                ],
                "posName" => void
              ],
              "showmode" => 1,
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "rule" => "map036",
            "time" => 1000,
            "vague" => "100"
          ]
        ],
        67,
        (const) [
          91,
          67,
          68,
          void,
          351,
          64
        ],
        68,
        (const) [
          92,
          68,
          69,
          void,
          353,
          64
        ],
        69,
        (const) [
          93,
          69,
          void,
          void,
          353
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "se",
              "stop" => 1
            ]
          ]
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "se",
              "replay" => (const) %[
                "filename" => "se088",
                "start" => void,
                "time" => 0,
                "volume" => 100.000000
              ]
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              (const) %[
                "mode" => 1,
                "name" => "se"
              ]
            ],
            "wait" => 1
          ]
        ],
        (const) [
          94,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_ホール_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm05",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          void,
          void,
          355
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "bg",
              "showmode" => 2
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              void,
              (const) %[
                "mode" => 0,
                "name" => "env"
              ]
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "msgoff" => "true",
            "rule" => "map036",
            "time" => "1000",
            "vague" => "100"
          ],
          "msgoff",
          1
        ],
        (const) [
          95,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "showmode" => 0,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm05",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "showmode" => 0,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          70,
          void,
          371,
          80
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "zpos",
                  233.333333
                ],
                void,
                (const) [
                  "leveloffset",
                  ""
                ]
              ],
              "class" => "stage",
              "link" => void,
              "name" => "bg",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "館_廊下_消灯",
                  "redraw" => (const) [
                    (const) [
                      "doBoxBlur",
                      0,
                      0
                    ],
                    (const) [
                      "doBoxBlur",
                      0,
                      0
                    ]
                  ]
                ],
                "posName" => void
              ],
              "showmode" => 1,
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "rule" => "map036",
            "time" => 1000,
            "vague" => "100"
          ]
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "se",
              "replay" => (const) %[
                "filename" => "se088",
                "start" => void,
                "time" => 0,
                "volume" => 100.000000
              ]
            ]
          ]
        ],
        70,
        (const) [
          96,
          70,
          71,
          void,
          373,
          64
        ],
        71,
        (const) [
          97,
          71,
          void,
          void,
          373
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "zpos",
                  0.000000
                ],
                (const) [
                  "xpos",
                  0
                ],
                void,
                (const) [
                  "ypos",
                  0
                ],
                (const) [
                  "zpos",
                  0.000000
                ],
                (const) [
                  "order",
                  0
                ],
                (const) [
                  "xpos",
                  (const) [
                    (const) %[
                      "accel" => -1,
                      "handler" => "MoveAction",
                      "start" => "@+30",
                      "time" => 800,
                      "value" => "@"
                    ]
                  ]
                ],
                (const) [
                  "visvalue",
                  0
                ],
                (const) [
                  "visvalue",
                  (const) [
                    (const) %[
                      "delay" => void,
                      "handler" => "MoveAction",
                      "start" => 0,
                      "time" => 800,
                      "value" => 100
                    ]
                  ]
                ]
              ],
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "驚き",
                    "pose" => "基本"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 1,
              "trans" => (const) %[
                "time" => 800
              ],
              "type" => void
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              (const) %[
                "mode" => 1,
                "name" => "美亜"
              ]
            ]
          ]
        ],
        (const) [
          98,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_廊下_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm05",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "美亜.stand",
                      "options" => (const) %[
                        "dress" => "夏服",
                        "face" => "驚き",
                        "pose" => "基本"
                      ]
                    ],
                    "posName" => "前"
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          72,
          void,
          379,
          64
        ],
        72,
        (const) [
          99,
          72,
          73,
          void,
          381,
          64
        ],
        73,
        (const) [
          100,
          73,
          74,
          void,
          384,
          64
        ],
        74,
        (const) [
          101,
          74,
          void,
          void,
          384
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "悲しみ",
                    "pose" => "後ろ"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 3,
              "trans" => (const) %[
                "method" => "crossfade",
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "wait",
          (const) %[
            "list" => (const) [
              void,
              (const) %[
                "mode" => 1,
                "name" => "美亜"
              ]
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 250
          ]
        ],
        (const) [
          102,
          (const) %[
            "data" => (const) [
              (const) [
                "bg",
                "stage",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      233.333333
                    ]
                  ],
                  "class" => "stage",
                  "name" => "bg",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "館_廊下_消灯",
                      "redraw" => (const) [
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ],
                        (const) [
                          "doBoxBlur",
                          0,
                          0
                        ]
                      ]
                    ],
                    "posName" => void
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ],
              (const) [
                "bgm",
                "bgm",
                (const) %[
                  "name" => "bgm",
                  "replay" => (const) %[
                    "filename" => "bgm05",
                    "loop" => 1,
                    "start" => void,
                    "state" => 1,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 1
                  ]
                ]
              ],
              (const) [
                "lse",
                "loopse",
                (const) %[
                  "name" => "lse",
                  "replay" => (const) %[
                    "filename" => "se074",
                    "loop" => 1,
                    "start" => void,
                    "state" => 0,
                    "volume" => 100.000000
                  ],
                  "update" => (const) %[
                    "state" => 0
                  ]
                ]
              ],
              (const) [
                "se",
                "se",
                (const) %[
                  "name" => "se"
                ]
              ],
              (const) [
                "美亜",
                "character",
                (const) %[
                  "action" => (const) [
                    (const) [
                      "zpos",
                      0.000000
                    ]
                  ],
                  "class" => "character",
                  "name" => "美亜",
                  "redraw" => (const) %[
                    "disp" => 2,
                    "imageFile" => (const) %[
                      "file" => "美亜.stand",
                      "options" => (const) %[
                        "dress" => "夏服",
                        "face" => "悲しみ",
                        "pose" => "後ろ"
                      ]
                    ],
                    "posName" => "前"
                  ],
                  "showmode" => 3,
                  "type" => void
                ]
              ]
            ],
            "env" => (const) %[
              "name" => "env"
            ],
            "ezsave" => (const) %[
              "visible" => 0
            ]
          ],
          75,
          void,
          389,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "xpos",
                  (const) [
                    (const) %[
                      "delay" => void,
                      "handler" => "RandomAction",
                      "time" => 300,
                      "vibration" => 0.500000,
                      "waittime" => 40
                    ]
                  ]
                ],
                (const) [
                  "ypos",
                  (const) [
                    (const) %[
                      "delay" => void,
                      "handler" => "RandomAction",
                      "time" => 300,
                      "vibration" => 0.500000,
                      "waittime" => 40
                    ]
                  ]
                ]
              ],
              "name" => "美亜",
              "showmode" => 3
            ]
          ]
        ],
        75,
        (const) [
          103,
          75,
          76,
          void,
          395,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => (const) [
                (const) [
                  "xpos",
                  0
                ],
                void,
                (const) [
                  "ypos",
                  0
                ],
                (const) [
                  "zpos",
                  0.000000
                ],
                (const) [
                  "order",
                  0
                ]
              ],
              "class" => "character",
              "link" => void,
              "name" => "美亜",
              "redraw" => (const) %[
                "disp" => 2,
                "imageFile" => (const) %[
                  "file" => "美亜.stand",
                  "options" => (const) %[
                    "dress" => "夏服",
                    "face" => "通常",
                    "pose" => "正面"
                  ]
                ],
                "posName" => "前"
              ],
              "showmode" => 3,
              "trans" => (const) %[
                "method" => "crossfade",
                "time" => 250
              ],
              "type" => void
            ]
          ],
          "trans",
          (const) %[
            "method" => "crossfade",
            "time" => 250
          ]
        ],
        76,
        (const) [
          104,
          76,
          77,
          void,
          402,
          64
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "美亜",
              "showmode" => 2
            ],
            (const) %[
              "action" => (const) [
                (const) [
                  "zoomx",
                  300
                ],
                (const) [
                  "zoomy",
                  300
                ],
                (const) [
                  "xpos",
                  -1200
                ],
                (const) [
                  "ypos",
                  500
                ]
              ],
              "name" => "bg",
              "showmode" => 3
            ]
          ],
          "trans",
          (const) %[
            "method" => "universal",
            "rule" => "map18",
            "time" => 500,
            "vague" => "300"
          ]
        ],
        77,
        (const) [
          105,
          77,
          78,
          void,
          405,
          64
        ],
        78,
        (const) [
          106,
          78,
          79,
          void,
          409,
          64
        ],
        79,
        (const) [
          107,
          79,
          void,
          void,
          409
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "name" => "se",
              "stop" => 1
            ]
          ]
        ],
        (const) [
          "envupdate",
          "update",
          (const) [
            (const) %[
              "action" => 0