/*

	TVP2 ( T Visual Presenter 2 )  A script authoring tool
	Copyright (C) 2000-2009 W.Dee <dee@kikyou.info> and contributors

	See details of license at "license.txt"
*/
/* This file is always generated by makestub.pl . */
/* Modification by hand will be lost. */

#include <windows.h>
#include "tp_stub.h"

#define TVP_IN_PLUGIN_STUB

tjs_int TVPPluginGlobalRefCount = 0;

//---------------------------------------------------------------------------
// stubs
//---------------------------------------------------------------------------
//---------------------------------------------------------------------------
// Stub library setup
//---------------------------------------------------------------------------

static iTVPFunctionExporter * TVPFunctionExporter = NULL;

void * TVPGetImportFuncPtr(const char *name)
{
	void *ptr;
	if(TVPFunctionExporter->QueryFunctionsByNarrowString(&name, &ptr, 1))
	{
		// succeeded
	}
	else
	{
		// failed
		static const char *funcname = "void ::TVPThrowPluginUnboundFunctionError(const char *)";
		if(!TVPFunctionExporter->QueryFunctionsByNarrowString(&funcname, &ptr, 1))
		{
			*(int*)0 = 0; // causes an error
		}
		typedef void (__stdcall * __functype)(const char *);
		((__functype)(ptr))(name);
	}
	return ptr;
}

/* TVPInitImportStub : stub initialization */
bool TVPInitImportStub(iTVPFunctionExporter * exporter)
{
	// set TVPFunctionExporter
	TVPFunctionExporter = exporter;
	return true;
}

/* TVPUninitImportStub : stub uninitialization */
void TVPUninitImportStub()
{
}



void * TVPImportFuncPtr3d4b725f0b4234d79524822e7c34486b = NULL;
void * TVPImportFuncPtr3fc0c32ee41ea0c515f8fbb681e37982 = NULL;
void * TVPImportFuncPtre8dbd4fe012262d9da831e0735aa33b3 = NULL;
void * TVPImportFuncPtrace6cce1353865d7376caca1f2124216 = NULL;
void * TVPImportFuncPtr5055344aa8055bc238b79e5f88fc3300 = NULL;
void * TVPImportFuncPtr8238c542b814acf1a83c00cced57ba26 = NULL;
void * TVPImportFuncPtrbd2a14ca8c345fd7f151b08d1792fb60 = NULL;
void * TVPImportFuncPtr16d432f9f86738a7688cbfc9b12441ec = NULL;
void * TVPImportFuncPtr6dac00582b8ba529e548ef058c4e869e = NULL;
void * TVPImportFuncPtr9193ae470b5efdfe617b5e94cd8f5da6 = NULL;
void * TVPImportFuncPtrec455b6ef0f5da178063db3875973260 = NULL;
void * TVPImportFuncPtra56aaf685bd171b63b0ef3c894d80ecf = NULL;
void * TVPImportFuncPtr9a5fe199cebb9841f94ac0bb7a4a3b6a = NULL;
void * TVPImportFuncPtr2acb76a1f86e34afc5fe934d406c6c4c = NULL;
void * TVPImportFuncPtr3a4d914ca7d24989c236ad223c002d49 = NULL;
void * TVPImportFuncPtr8fca7d3a123df1eacf228ba89f6a02ff = NULL;
void * TVPImportFuncPtr58be195f96a36c158d638e3b0c79308b = NULL;
void * TVPImportFuncPtreaa4d5b1d186a807a63311ab6d5e16e4 = NULL;
void * TVPImportFuncPtr246f30d208c1d3a4e2b558090f403734 = NULL;
void * TVPImportFuncPtr3206ef9b7a8013d6572decdea49e7e2e = NULL;
void * TVPImportFuncPtrc5a30d297c3a121879b1392bc6c604ef = NULL;
void * TVPImportFuncPtre398f5aef0ab92bc1323f3b094722fb1 = NULL;
void * TVPImportFuncPtr0733b0ac80880897d327dc6f3b04ea9e = NULL;
void * TVPImportFuncPtr4cb055ed9d8ef71d1af10898965c940c = NULL;
void * TVPImportFuncPtref8d198596b7d3143d02ed4450ccefa1 = NULL;
void * TVPImportFuncPtrd48ea419e040ffe8c20c1e86d80c9a5f = NULL;
void * TVPImportFuncPtr679b215ff76a269871d5f325b981e561 = NULL;
void * TVPImportFuncPtr1039eff4a4443f9238438485a35a93a7 = NULL;
void * TVPImportFuncPtr2f873b0ee1c6591ba28bc4b9c0e4c954 = NULL;
void * TVPImportFuncPtra583ffb56cdb2ede691e15053a8a165a = NULL;
void * TVPImportFuncPtre09ed277802c1b117e1908421448886d = NULL;
void * TVPImportFuncPtre76dfb9e00f4a9d491117d815f30db7f = NULL;
void * TVPImportFuncPtrb000dd8934508d8ec6d6ef976a6ff49b = NULL;
void * TVPImportFuncPtrd98ab5c968ebfde4e924901d09190774 = NULL;
void * TVPImportFuncPtr661e8c10d5d477e6823a840244937cd8 = NULL;
void * TVPImportFuncPtr6b39e70ea89c4f883689f51289029b69 = NULL;
void * TVPImportFuncPtr4a18b1c0afe37b84e2b35a7fc07c4e0f = NULL;
void * TVPImportFuncPtr48b85c8774d91ca40b2992f0e452f19e = NULL;
void * TVPImportFuncPtr5ea8db9a9193fe6bab53baf2bee06b6b = NULL;
void * TVPImportFuncPtr46b92626ff6894e993c4f193a129540b = NULL;
void * TVPImportFuncPtr6efc1d1f66f0e01a81faf767d7576816 = NULL;
void * TVPImportFuncPtr4ededf58eae77c320b4a6f5f701acafb = NULL;
void * TVPImportFuncPtr028d5fda2f4568f6ab14b49d89650a4d = NULL;
void * TVPImportFuncPtr11912984b8c094d2df26bf3c3677d096 = NULL;
void * TVPImportFuncPtr6c0df790c33142e286aea9af6993d931 = NULL;
void * TVPImportFuncPtrc27d85b695cd6e144210785bdfd446ce = NULL;
void * TVPImportFuncPtr8422ef7f42009be0ad58a09d64149051 = NULL;
void * TVPImportFuncPtree07e6522577952453206ede39cdf54c = NULL;
void * TVPImportFuncPtr786a65424247e711f6ca31f0a10603d7 = NULL;
void * TVPImportFuncPtr995a222f2038dd2007f2c1f6429bd19e = NULL;
void * TVPImportFuncPtrda8c6e750d6a9c0557a56ef7f7fd8e88 = NULL;
void * TVPImportFuncPtr9cf7b0f119bcf3fa4564837ae25429b3 = NULL;
void * TVPImportFuncPtr17cbcacad2ed350215d7d700c676ea40 = NULL;
void * TVPImportFuncPtr2bd375c0598e9148d88579a51b2f07a8 = NULL;
void * TVPImportFuncPtr4d2c157f8b0b49e57c3e9b5abc9deb0f = NULL;
void * TVPImportFuncPtr4b7eaccf64af0f3a4c4fe64f4e2dd3fd = NULL;
void * TVPImportFuncPtr3a4d2602c392a8d1f4c38d537a8c95e0 = NULL;
void * TVPImportFuncPtr8d915d35ef8e857f245c5d46798618e4 = NULL;
void * TVPImportFuncPtr1e463482afa8ca30f5fa7bea4fa5741d = NULL;
void * TVPImportFuncPtrfdf270e4080c986abd1649fa9fffdeab = NULL;
void * TVPImportFuncPtr972e0f9a6ec4648a9fb82bcf5d9095ff = NULL;
void * TVPImportFuncPtr9d76731c37c4664d654db026644c64b4 = NULL;
void * TVPImportFuncPtr4f1620cb699874b9c8cedf6e321c606e = NULL;
void * TVPImportFuncPtref1c6b2b601d1b0ff70272a4d447aa3c = NULL;
void * TVPImportFuncPtr9b7872860c95cfdafb056ab30318e99c = NULL;
void * TVPImportFuncPtr53360f194a04fc142ddae2b9a3ab4c92 = NULL;
void * TVPImportFuncPtrce1dcb05e5e7c4cafbc4ed37f63b256e = NULL;
void * TVPImportFuncPtr841ce4492b37321eea0c1b500de9b352 = NULL;
void * TVPImportFuncPtr61785de870894968cd9d95e17e88eafc = NULL;
void * TVPImportFuncPtrad3236e727398311c3b8e1ddd5f4b293 = NULL;
void * TVPImportFuncPtr80e0b7be488545ff9b8bc52c9ab5fba5 = NULL;
void * TVPImportFuncPtr4eaa3e4efb319707db6ef81db1c6f147 = NULL;
void * TVPImportFuncPtr693a0152f098caee7fc77f545dd3e954 = NULL;
void * TVPImportFuncPtr42840710f5fba9bb32b95290b1796a55 = NULL;
void * TVPImportFuncPtradec3f9ef429aa9a284081f0fc6a1b5b = NULL;
void * TVPImportFuncPtr674a7948152a1d7a49050b9d98796403 = NULL;
void * TVPImportFuncPtraa6f132b2031c83062f6149c90f2df5f = NULL;
void * TVPImportFuncPtrb52f446e22bb92d495f7e65ac71c9bf9 = NULL;
void * TVPImportFuncPtrd4899fd4a8beb06f192dcb1d300e3319 = NULL;
void * TVPImportFuncPtrd3f5ec78464d29ee6988a1f90c2e3e1b = NULL;
void * TVPImportFuncPtra463ad6a757c3f04e09a72e288737d06 = NULL;
void * TVPImportFuncPtr27857bb89d35113183b682c3917d6c7a = NULL;
void * TVPImportFuncPtra5f80951cfb882ac6a3e06c0b9a95807 = NULL;
void * TVPImportFuncPtr35aadb63079c8bd84ebc0389bae306e0 = NULL;
void * TVPImportFuncPtrfb6573df5887c2020ae58136f8342ed4 = NULL;
void * TVPImportFuncPtr86c67d2197c46824ab10f59e568ad13a = NULL;
void * TVPImportFuncPtr263a0c5b335b2c4d5bc1f55b51b8315e = NULL;
void * TVPImportFuncPtr975c1099e57ab67122ddef0f44fd7dd5 = NULL;
void * TVPImportFuncPtr04493e5237a7ca97afd391cb7e831ba0 = NULL;
void * TVPImportFuncPtr9996100acc7705cb2b0c904d6bad4401 = NULL;
void * TVPImportFuncPtr5d91cff3b2a26ff7c0543e0f6d737117 = NULL;
void * TVPImportFuncPtref1dedc2cb58dc4e1afc14238b6fc518 = NULL;
void * TVPImportFuncPtrf18397fe81c043ba2346e31b359f6a73 = NULL;
void * TVPImportFuncPtr2ee45ad60b0c06a8d0feebc3a6aad9e7 = NULL;
void * TVPImportFuncPtr44500491c57e17032951fe6ed268ff1d = NULL;
void * TVPImportFuncPtr056f5d278c75750df792bf8b081fbf7d = NULL;
void * TVPImportFuncPtr04233bc4f7d4df92c260d23110320afe = NULL;
void * TVPImportFuncPtrcdc475c4419e77c22508e337428c4074 = NULL;
void * TVPImportFuncPtr06bacb2910308a47bbe27ff7efa1226d = NULL;
void * TVPImportFuncPtr521e053199a4aeb4e0f24d9f4a6cc682 = NULL;
void * TVPImportFuncPtr02164e6fb4c925843ac774ec1e4c6e5d = NULL;
void * TVPImportFuncPtr5110cbbcddbd9688281ee5418e3f9023 = NULL;
void * TVPImportFuncPtr1db54b61f00bf931452218c4a39e79ef = NULL;
void * TVPImportFuncPtr9d0edd8f51f155767301017bd3d256da = NULL;
void * TVPImportFuncPtr8f744c5aa8df5471939b960bc759f12b = NULL;
void * TVPImportFuncPtrba7ff7b0b4192bd2cc7f49c7b688ad57 = NULL;
void * TVPImportFuncPtr7773ac921bb82c85de3be69ef86265fd = NULL;
void * TVPImportFuncPtr114a781ed71edace31abb352a2671f41 = NULL;
void * TVPImportFuncPtr2bc5f4a97decfa82c625430479ec512b = NULL;
void * TVPImportFuncPtr066fb79f94523d95d12480f23c58cc8e = NULL;
void * TVPImportFuncPtr803906b8de16ff825d4e69e1952d872f = NULL;
void * TVPImportFuncPtr34cc96a5118ee1e12b0750ea64d40b1f = NULL;
void * TVPImportFuncPtrdbe821fb8b651d42a9c8e730517c408c = NULL;
void * TVPImportFuncPtr8970ba46068ac74746c3e84299937d8f = NULL;
void * TVPImportFuncPtr438e27dcbb077284213eb4d7dcd43f8f = NULL;
void * TVPImportFuncPtra98d712ca19a49afe07d0a7c5d064cef = NULL;
void * TVPImportFuncPtr08aef69683bcfe2a5c63d4c7866de8e9 = NULL;
void * TVPImportFuncPtrdbc9bc2e27068c8426b1c6a7f89424e0 = NULL;
void * TVPImportFuncPtr5eeb98ca016123f57966457533bb639e = NULL;
void * TVPImportFuncPtr98fdc846d0b4a83412f3521f65bb98b4 = NULL;
void * TVPImportFuncPtr3309591d3c7f6f688e81588f169dba21 = NULL;
void * TVPImportFuncPtrd83a866389246d824efcc83303a04484 = NULL;
void * TVPImportFuncPtr6cf6f332a6a14a15e8dce62301f5c840 = NULL;
void * TVPImportFuncPtr566eeea3c5f009b0fc6fa123ba30f496 = NULL;
void * TVPImportFuncPtr88806e38e35c73b36acadd4061a4fe0b = NULL;
void * TVPImportFuncPtr3bb69d3886159aaecc333b6ff17287bf = NULL;
void * TVPImportFuncPtr3e36278551a9c8b29cb2e8017db6af0d = NULL;
void * TVPImportFuncPtr5de99d84f3dc902cb0812fb85a7d5c88 = NULL;
void * TVPImportFuncPtr31e85cbc73f8fbd4cea895a751480059 = NULL;
void * TVPImportFuncPtr6ae29e405ede762f1a89a9dd526cb36e = NULL;
void * TVPImportFuncPtrc95bd66d95c153cdac41b5243e555f5f = NULL;
void * TVPImportFuncPtr72a67e9c52fd27dbb66eded47efeea74 = NULL;
void * TVPImportFuncPtrfb13e41bda53e4e59403e3e14effccd6 = NULL;
void * TVPImportFuncPtr9a5c710e620e47f105752453ad5d6ab1 = NULL;
void * TVPImportFuncPtr18f1ad16c11429707cbf8ea4d1d4a21e = NULL;
void * TVPImportFuncPtr550f317b573a1256af00586890ae82f1 = NULL;
void * TVPImportFuncPtrcd50da721dfb63f36c1ebb1226830428 = NULL;
void * TVPImportFuncPtrfbba3dd6a087599d1277ae58f6cec18e = NULL;
void * TVPImportFuncPtr43cc5b5a61a6090af83333d115b5b868 = NULL;
void * TVPImportFuncPtr616fb5060d81eb5bab58647596582df4 = NULL;
void * TVPImportFuncPtr168cf4c1b9ef70b98f2e0ab3695a4f3b = NULL;
void * TVPImportFuncPtr314573cca30a7c2aecc9166fbf5400c9 = NULL;
void * TVPImportFuncPtr03da356426c038fad663c836c3e330ef = NULL;
void * TVPImportFuncPtr31dbebdedc08d75e34a2cd564ce60586 = NULL;
void * TVPImportFuncPtrd9224ad7a0de743a7eea15fdb2c5f934 = NULL;
void * TVPImportFuncPtrc01b0720b49ce4f792446d8965d2c31f = NULL;
void * TVPImportFuncPtr4af47e46a11e1357cb994f405289d13e = NULL;
void * TVPImportFuncPtr25b6dafa19bfa5bde1a8b519da248f82 = NULL;
void * TVPImportFuncPtr72425405819c900aec719491cbd90c6d = NULL;
void * TVPImportFuncPtra79942af73f33bff6e432c9fd808e469 = NULL;
void * TVPImportFuncPtrdf106470a4141ebc7eda22160859ffdc = NULL;
void * TVPImportFuncPtr469bc225b0ecd9561aae5a46b85ded42 = NULL;
void * TVPImportFuncPtra6663c078b3aa79b39ee2d09f3875765 = NULL;
void * TVPImportFuncPtrefbe634ce4f13633e220cae167cf63fb = NULL;
void * TVPImportFuncPtr57f4147bcc09e4e4442ffc9b0895727e = NULL;
void * TVPImportFuncPtr1fb2d2e44cf83aebef7b26fd6b20bc2b = NULL;
void * TVPImportFuncPtrbd6aa777bac947f5cffd891e9c724794 = NULL;
void * TVPImportFuncPtr83c662330b75d616cdc8a4e11d7ababa = NULL;
void * TVPImportFuncPtrbbde02fe30c8a6cadb7073174ea3a874 = NULL;
void * TVPImportFuncPtrcc1c14f63867f90bc883de03e9212cbc = NULL;
void * TVPImportFuncPtr236e007b32bc2631b5f6dc1eda6be0a9 = NULL;
void * TVPImportFuncPtrcfbb9809e0e6d954b2652856e935ced9 = NULL;
void * TVPImportFuncPtr60ee96ae4a7704340bef20fb35ba6ade = NULL;
void * TVPImportFuncPtr564b37278b50f4e5597dff6540868d49 = NULL;
void * TVPImportFuncPtr890b3a4831b824653e919b4a5197358d = NULL;
void * TVPImportFuncPtr2dfa6c77c5051d160b8a06f540e0d68b = NULL;
void * TVPImportFuncPtr05f88567d510fd84659ccbf493f647ed = NULL;
void * TVPImportFuncPtr7166b8f7bb9688c980e4fa172f06f30c = NULL;
void * TVPImportFuncPtrb9456ecba8b7898d80d2e5caa64035c9 = NULL;
void * TVPImportFuncPtrdd44464bd8430a5be5fef0cffcd97117 = NULL;
void * TVPImportFuncPtra57696ca0c157cd7d3cd4e58c1df957c = NULL;
void * TVPImportFuncPtr1aea9f8a38bbb875b6d052f330da9178 = NULL;
void * TVPImportFuncPtr2d3b3d6e22ee139cda9eee47dc031945 = NULL;
void * TVPImportFuncPtr8ff49e56c3c4c566561dcdd5c9ecc4db = NULL;
void * TVPImportFuncPtr490b547e93e40082d0b83312467104f9 = NULL;
void * TVPImportFuncPtr2c1ef06748df47df52b586ac0fbc6a34 = NULL;
void * TVPImportFuncPtrb6b2a03160b88239eccd18d89b1537d3 = NULL;
void * TVPImportFuncPtr8becefbd52c76c7ecb0ea7b7f50b7915 = NULL;
void * TVPImportFuncPtr74b9687a3bfd3b2c7abe226efc4225c1 = NULL;
void * TVPImportFuncPtr7cafc2bf5965b594e60830e3057bbd58 = NULL;
void * TVPImportFuncPtr80f111939c5694cbf43d07cf0ad1726c = NULL;
void * TVPImportFuncPtr8dc9cef84191f79b38403a2070952fd4 = NULL;
void * TVPImportFuncPtr1d42bd1e659b36886c20567497b7ee96 = NULL;
void * TVPImportFuncPtr0848fbdc7eeddb12c80bcd9c31383a64 = NULL;
void * TVPImportFuncPtr1f1123c906c28ab6d16b6bef3f7ae978 = NULL;
void * TVPImportFuncPtrb84394e20cc73a90349cf5be4e783111 = NULL;
void * TVPImportFuncPtr76e0db3797851fe8ff90cf84780c50ad = NULL;
void * TVPImportFuncPtr6616241156c22bced42cd9f2f647677e = NULL;
void * TVPImportFuncPtr1ace346a3dd546c66ad115a33d8cf693 = NULL;
void * TVPImportFuncPtr96fb9bbe33531d4268573355c658e165 = NULL;
void * TVPImportFuncPtrc90b5737134c76f9ed0bb5da7cfaad8c = NULL;
void * TVPImportFuncPtr070ed05259a265cabdd82bfedabdd638 = NULL;
void * TVPImportFuncPtr008b7e3a4c5bb23ee991f684a5064737 = NULL;
void * TVPImportFuncPtrb64741dc4544ed43c44ddb6d0eb838ea = NULL;
void * TVPImportFuncPtr5b83e28b2d9ab0f75d7c7f6f61b5ded6 = NULL;
void * TVPImportFuncPtrb948c9f43837efa489b0b91f3f675710 = NULL;
void * TVPImportFuncPtreb83216f6f718245468ef48b97ab4c2d = NULL;
void * TVPImportFuncPtrc66ab4868b743de9c0ba8b26c67b23da = NULL;
void * TVPImportFuncPtr586e16d502a6ad98b08161bdb090f8b6 = NULL;
void * TVPImportFuncPtrd8bc9c71c80b200c39b29167d795cad0 = NULL;
void * TVPImportFuncPtr85df4beb87f6503891e116ce046353c3 = NULL;
void * TVPImportFuncPtr35b6a7e1c73f257aae91e05fa9826e84 = NULL;
void * TVPImportFuncPtra25b46701e25030af1ed847e0df229eb = NULL;
void * TVPImportFuncPtrc8906bf1efa5e86f9fddfab55a01c8f6 = NULL;
void * TVPImportFuncPtr8141059f613820f694608af28e20cbad = NULL;
void * TVPImportFuncPtrcf2690e47099ac6378ed50df4a8a8e90 = NULL;
void * TVPImportFuncPtr810c7054e44f535cf250f00707105417 = NULL;
void * TVPImportFuncPtr52a9af7905ddc71d8b4e0ef7366eebdd = NULL;
void * TVPImportFuncPtr1635dbae2d91b338ddfd0430f8aa7f10 = NULL;
void * TVPImportFuncPtr30df0c29ad8f672f7fe0742b4b11cd7f = NULL;
void * TVPImportFuncPtr61c82dec644c58290a25f34a69478870 = NULL;
void * TVPImportFuncPtrf08e347d2d47dc5fc9a3cb59355b4fbb = NULL;
void * TVPImportFuncPtr5c62e59c2062f658d4c79d5257a9a586 = NULL;
void * TVPImportFuncPtr259c72d8bfed1210ca71c54f24cacc7a = NULL;
void * TVPImportFuncPtr801a92ace08eb7ed001406869a39a75f = NULL;
void * TVPImportFuncPtre22e647af4ded8e51b1e76c845b4c8e2 = NULL;
void * TVPImportFuncPtr12902221314df9bcf7f7cb74a5242fe0 = NULL;
void * TVPImportFuncPtrb10feea1619ba8ac11237c12002cdb3e = NULL;
void * TVPImportFuncPtr19755b50d241edcb477bdcac22663778 = NULL;
void * TVPImportFuncPtr040a0ecf46963e094ee8ec32ab3f1962 = NULL;
void * TVPImportFuncPtr525c529dc687b5d86424d775d00bdfce = NULL;
void * TVPImportFuncPtrc96107b91e2a215f560a2612c6e85931 = NULL;
void * TVPImportFuncPtrb8788eaa2ca495263c6ea2df264af5f5 = NULL;
void * TVPImportFuncPtr4c6494008c520d896d699f82aca30b25 = NULL;
void * TVPImportFuncPtr7d8f8d5e0832ecf248b19a89801ead0e = NULL;
void * TVPImportFuncPtr70849965060a6402f41b0b11ec2bb3a7 = NULL;
void * TVPImportFuncPtrc72efa6b4efaa6664ae637a03e98e866 = NULL;
void * TVPImportFuncPtra250e46575d0df1166e1542613218a5c = NULL;
void * TVPImportFuncPtra7bcff67b8d380c225b9d0d83921b3ae = NULL;
void * TVPImportFuncPtrfb68a3aa16bd2eb7d7550283170321bf = NULL;
void * TVPImportFuncPtr35b4299ede11f511b331b713ba9f38a8 = NULL;
void * TVPImportFuncPtrefe52691cff20b2dfaa16e8e16caac0a = NULL;
void * TVPImportFuncPtr38eed43ef69251c34dc45695b8cf35c0 = NULL;
void * TVPImportFuncPtr2058b65abdfb7598910f0d584d40a19d = NULL;
void * TVPImportFuncPtr1ebecaefe2ffdc811fccbac42e67e544 = NULL;
void * TVPImportFuncPtr09e0f0912f8d758d3736ece9478c2686 = NULL;
void * TVPImportFuncPtr23d61eda3959b087b618e348471e2c36 = NULL;
void * TVPImportFuncPtre99b22c79b5bf04f3382f959c7bb69ca = NULL;
void * TVPImportFuncPtr9c4bb9ebee4db0fcebeae11c34950f97 = NULL;
void * TVPImportFuncPtr505a9563aeb1b0255cfcc8197bee7d9e = NULL;
void * TVPImportFuncPtrf5ab80fc67ee04570330b9035144e760 = NULL;
void * TVPImportFuncPtraf50188bbaa019ee88b19ecd931f7cce = NULL;
void * TVPImportFuncPtr268c452e85a6ac75301a6132f4f5e38b = NULL;
void * TVPImportFuncPtr646770a19b1768b372c9991ef0d3de85 = NULL;
void * TVPImportFuncPtr5ec88e04fcb8e1877752281e172173ed = NULL;
void * TVPImportFuncPtr923f8161f2d2ba0e883bc4edc2901960 = NULL;
void * TVPImportFuncPtr6f70cdb7586cbe571204f286f43c9780 = NULL;
void * TVPImportFuncPtr9a4eaa6a627038799015c093609bdde7 = NULL;
void * TVPImportFuncPtrc8bb6590f4a7adc906d7b3e42d907267 = NULL;
void * TVPImportFuncPtr8323d57f26876d87271dbfa257b7f7e2 = NULL;
void * TVPImportFuncPtr4d6f148e8997e1ae0cc0006ec1bd9618 = NULL;
void * TVPImportFuncPtr7f03a4ddb254d0518642d15513eaea85 = NULL;
void * TVPImportFuncPtr4add3926c72ba9df9259be58b680de0d = NULL;
void * TVPImportFuncPtr075d42cff8dc0c1fbd99c7459a63e526 = NULL;
void * TVPImportFuncPtrb6bc45b28e194c7ac98bfdea88edee36 = NULL;
void * TVPImportFuncPtr6dff6abb075da1a304520e60c011ef7b = NULL;
void * TVPImportFuncPtr892ffbdb8375851fc557e4abe9589b77 = NULL;
void * TVPImportFuncPtrb2f3538284fc2adda2a43272ee654a96 = NULL;
void * TVPImportFuncPtre0ff899ea4a9cc49a0e3b38deaf93b45 = NULL;
void * TVPImportFuncPtr4b9c9ac2aafad07af4b16f34e9d4bba2 = NULL;
void * TVPImportFuncPtrc2e423356d9ca3f26f9c1d294ee9b742 = NULL;
void * TVPImportFuncPtrc07314686fdf5815ce9b058020da942b = NULL;
void * TVPImportFuncPtr4a197be1985d45ee86d5672d24134560 = NULL;
void * TVPImportFuncPtrdec720a9c3cd2b378f195cf71a9ff8b0 = NULL;
void * TVPImportFuncPtr5726a5c7af641ebaa504dc9ec8380938 = NULL;
void * TVPImportFuncPtr1c53bc96ac9dfd483c2227bc5fa44825 = NULL;
void * TVPImportFuncPtr1940c8fa03145aa029d0b7718ce0c809 = NULL;
void * TVPImportFuncPtrb37f047c0f9bd143b34a2fc87ce5f16e = NULL;
void * TVPImportFuncPtrdec35fbd2a24fc32e5c220174d864cf4 = NULL;
void * TVPImportFuncPtr86fd45a126296891aee413388597203e = NULL;
void * TVPImportFuncPtr603243e54f3508c37d993e8359b735dc = NULL;
void * TVPImportFuncPtrc3eadbd75b32dabe6faecebf492eb486 = NULL;
void * TVPImportFuncPtr725e49de1d970ef04b179776666f2c34 = NULL;
void * TVPImportFuncPtr55a9b73f877bfd4c6d8157e7b1c458df = NULL;
void * TVPImportFuncPtrd070209f152dd22087e6e996e02c85cf = NULL;
void * TVPImportFuncPtr308f905626bc51c7ef9b65b2c0ca34b2 = NULL;
void * TVPImportFuncPtr95aab2a1ac9491e8026f4977e0918760 = NULL;
void * TVPImportFuncPtre0ac94325eb783ca2fe7856a54444c90 = NULL;
void * TVPImportFuncPtr0c99a79e866f08b4df3914e83fc203dc = NULL;
void * TVPImportFuncPtrf2de531a016173057ff3540e47fed4e6 = NULL;
void * TVPImportFuncPtr4224a9066d8d13d6d7e12f1ace6a5beb = NULL;
void * TVPImportFuncPtr900476efbc2031e643c042ca8e63a3d7 = NULL;
void * TVPImportFuncPtr07dfce61d490cf671a2d5359d713d64a = NULL;
void * TVPImportFuncPtr52d30ac8479ef7e870b5aff076482799 = NULL;
void * TVPImportFuncPtr8e4d0392ed46e87f94e5fcf675a124a1 = NULL;
void * TVPImportFuncPtr73f46e08d17e707725f433b454f05a89 = NULL;
void * TVPImportFuncPtr80d60e682fa72973071e335db272a2a2 = NULL;
void * TVPImportFuncPtr6bd6262185fa0b9cf1750f6a525d893a = NULL;
void * TVPImportFuncPtrcf29f737d4eb450b26789d421d0ec69a = NULL;
void * TVPImportFuncPtr13c0e371c08fd1b9da2f0c103d01c59a = NULL;
void * TVPImportFuncPtr82693e38df8f033ea98f9b7969d66d7b = NULL;
void * TVPImportFuncPtr6e3f8a3b18f55dae6153a889f00a3e87 = NULL;
void * TVPImportFuncPtrefe14a197131b4813656d6669cc3475b = NULL;
void * TVPImportFuncPtrba4ecf60f872f757b69c84f457b3e941 = NULL;
void * TVPImportFuncPtrdffedabe32ce886e3b7e695b44ad3547 = NULL;
void * TVPImportFuncPtrf518c60b165658d19a0fadd8f69586aa = NULL;
void * TVPImportFuncPtr6fefcb1c2ca01a876c301ab41dbdab9f = NULL;
void * TVPImportFuncPtrdf55083347df0483b4ca6ba1e4f0b9a0 = NULL;
void * TVPImportFuncPtrd8d28310f702714733c4c5dc850058df = NULL;
void * TVPImportFuncPtr52d24c38b05be174bc5c4fdcf02e9b9f = NULL;
void * TVPImportFuncPtrf27f455c8f30cbaf1706faac3c7b8e02 = NULL;
void * TVPImportFuncPtr78ec453a50b2800bb01347e8ebbac000 = NULL;
void * TVPImportFuncPtr0936d0f6fc53339d255893e58bcc6699 = NULL;
void * TVPImportFuncPtrf4f7181b7fd679784c50b0cc7ba4c60e = NULL;
void * TVPImportFuncPtr79816d7e5741c2416fefe2c2a8baef00 = NULL;
void * TVPImportFuncPtr42a3d248fab928f16555abcceca62834 = NULL;
void * TVPImportFuncPtr926d6212b8b1b238e7bef9b17a3ee643 = NULL;
void * TVPImportFuncPtr236e3d626784d80ca2cc5b2fe14cd9c6 = NULL;
void * TVPImportFuncPtr1bfac11a5f95c842f97a8bb57d4019de = NULL;
void * TVPImportFuncPtr198ce21c54b0cea4c1bf5eeba35349ab = NULL;
void * TVPImportFuncPtr590a1ec7f64904eaa32b5c771bb5f8cd = NULL;
void * TVPImportFuncPtrdd13d4bc2b48540a92f047bf015b829b = NULL;
void * TVPImportFuncPtr0ff502d492598d2211405180bfb4d1e1 = NULL;
void * TVPImportFuncPtrcf5401746759bfe38918087aaab6c57b = NULL;
void * TVPImportFuncPtr04e84aa7d8cf0477d55c700164544b38 = NULL;
void * TVPImportFuncPtr449039d3afbfbd52a63130a3b227a490 = NULL;
void * TVPImportFuncPtr347a4fa85af84e223c4b61d33ead694a = NULL;
void * TVPImportFuncPtr4ad1dd24b3b4769ee10149eea006af7a = NULL;
void * TVPImportFuncPtrb246b17b62d273bdc04e9d9e827f5c74 = NULL;
void * TVPImportFuncPtr9974ebc6296f925cff55d8bcb2d52ce9 = NULL;
void * TVPImportFuncPtr0e0c9d9107d8c56b8bc4d4198ae9208a = NULL;
void * TVPImportFuncPtrc23ece207f6ec2dd7c76ef873047aee3 = NULL;
void * TVPImportFuncPtr81507020bc646be2f53ab95b9430ba27 = NULL;
void * TVPImportFuncPtracc0d3861d1b971abcbdda1c075dd681 = NULL;
void * TVPImportFuncPtrff2dccead1b31e3f34e8be3e2ba5bbf1 = NULL;
void * TVPImportFuncPtre17db0d4f69625c61aba7fffe540dded = NULL;
void * TVPImportFuncPtr5bbc872e7bba5b761c509d31116e4460 = NULL;
void * TVPImportFuncPtr4adf361303eae78829250c7b732a5722 = NULL;
void * TVPImportFuncPtrbf172364c57c1aa561b145fd5cacda0c = NULL;
void * TVPImportFuncPtrd7687aa80dac10f88deac7aa7e70538a = NULL;
void * TVPImportFuncPtrb18b7259f98029f745c75291d6855ab1 = NULL;
void * TVPImportFuncPtrb79e5d877116025576ca1f76af124009 = NULL;
void * TVPImportFuncPtr8aea098dfe8a36c705cc2a9e1a189b84 = NULL;
void * TVPImportFuncPtr4ccd3f6ab60d61be6dbfc59e8e3d1726 = NULL;
void * TVPImportFuncPtr3d70bb72a7d7765c7e8ea580079ab7e9 = NULL;
void * TVPImportFuncPtreba9b272d78a4b0cd7f9212e29a58607 = NULL;
void * TVPImportFuncPtrcfbe8ee9d43aa64ae4190eac91f7c55f = NULL;
void * TVPImportFuncPtra4308a386968ef5d23025ab8a9e8c6db = NULL;
void * TVPImportFuncPtr5a4fcbe1e398e3d9690d571acbbbae9f = NULL;
void * TVPImportFuncPtr5b62f504fe6d22428d7518d6c52d775d = NULL;
void * TVPImportFuncPtrfb3b405f8747b54f26c332b9e6af81cd = NULL;
void * TVPImportFuncPtrb7ccd11d130f186883c109d2ba17b598 = NULL;
void * TVPImportFuncPtrcf8ab6c24f25993ccc7663e572ac2991 = NULL;
void * TVPImportFuncPtrba40ffbca76695b54a02aa8c1f1e047b = NULL;
void * TVPImportFuncPtrc97720e639e95ba5130ce9dd78d30403 = NULL;
void * TVPImportFuncPtrc5557ac5391b1b831a22e64b65d1746c = NULL;
void * TVPImportFuncPtr3243a4c32d4f674f1bbc8d3895257568 = NULL;
void * TVPImportFuncPtr78390a3d08879903ee9558e9df68db4d = NULL;
void * TVPImportFuncPtr58e9454d7096a52808f9a83b9ce25ff0 = NULL;
void * TVPImportFuncPtrcdefadd0c3bf15b4639b2f0338a40585 = NULL;
void * TVPImportFuncPtr4bf80e9bac16b9e3f9bf385b2fbce657 = NULL;
void * TVPImportFuncPtr51aeacf2b6ef9deb01c3b3db201d6bf9 = NULL;
void * TVPImportFuncPtr9ed5432d73448da47991df9577ee97bc = NULL;
void * TVPImportFuncPtrcf1d02d1cc1aff0aae6c038c95dac80f = NULL;
void * TVPImportFuncPtrddb0e05c72c0692e78af885ac7ec82dc = NULL;
void * TVPImportFuncPtra3029db6292616cd16c228b91dc4af13 = NULL;
void * TVPImportFuncPtr2d90871c6bc15a9e8d97d24c29e78e3b = NULL;
void * TVPImportFuncPtr0af6744e35e38276d6a98c1f382b1519 = NULL;
void * TVPImportFuncPtrad40567a051208757642e5e087f3e741 = NULL;
void * TVPImportFuncPtr6a15185daab9b274963fe5ef46305775 = NULL;
void * TVPImportFuncPtr073a2332a8ab3ed31ab81daea3d3f2c4 = NULL;
void * TVPImportFuncPtr01216e91225e06c7422bef0c2febc0cc = NULL;
void * TVPImportFuncPtr16ce22ad500a5bdfd5d5743c847a28b6 = NULL;
void * TVPImportFuncPtr59251c4104f736fa2690c5f77fb0a908 = NULL;
void * TVPImportFuncPtrf923750e0fdb51a6fc6c304832cb3dd3 = NULL;
void * TVPImportFuncPtrbc77a1e312ff7827d90387fb92f0f5b0 = NULL;
void * TVPImportFuncPtr2090afd7ae8bcb021ec4d04947d0d845 = NULL;
void * TVPImportFuncPtr3a0f858bdf86199dc2d00b583a3b915f = NULL;
void * TVPImportFuncPtr0d316a141f7a502ff8d9ffe2d38d25a8 = NULL;
void * TVPImportFuncPtrb31ff64ae2d8f93dbf28161d5080b295 = NULL;
void * TVPImportFuncPtrd9b1c73516daea6a9c6564e2b731615a = NULL;
void * TVPImportFuncPtr003f9d3de568fcd71dd532f33d38839c = NULL;
void * TVPImportFuncPtr5da29a19bbe279a89be00e16c59d7641 = NULL;
void * TVPImportFuncPtrc1b52e8f3578d11f369552a887e13c5b = NULL;
void * TVPImportFuncPtr5b1fa785e397e643dd09cb43c2f2f4db = NULL;
void * TVPImportFuncPtr29af78765c764c566e6adc77e0ea7041 = NULL;
void * TVPImportFuncPtr9e0df54e4c24ee28d5517c1743faa3a3 = NULL;
void * TVPImportFuncPtrd3aaa55d66777d7308ffa7a348c84841 = NULL;
void * TVPImportFuncPtrb426fbfb6ccb4e89c252b6af566995b8 = NULL;
void * TVPImportFuncPtrc145419db7b63f7488ea05a2a8826c1d = NULL;
void * TVPImportFuncPtrd795cd5ebfb6ca6f1b91bafbe66d7a65 = NULL;
void * TVPImportFuncPtr4564a3ce5cf48cb47e63a3948cef03be = NULL;
void * TVPImportFuncPtrbee2775f2e4042043b7cb08056d2ae5c = NULL;
void * TVPImportFuncPtr5fd8dfd2816a2cfd4a51cab41053d575 = NULL;
void * TVPImportFuncPtr9982ebedc12d343cb098e2a7b25bdef1 = NULL;
void * TVPImportFuncPtr81eeacbed5ee6129bef4b370e28b5d10 = NULL;
void * TVPImportFuncPtr6ed1088905d99012d2fb5827ea19527e = NULL;
void * TVPImportFuncPtrb4d6c64cc0004ffaba804f0e8f02ab9b = NULL;
void * TVPImportFuncPtr2c3e08b8df93ec50451edd916c707030 = NULL;
void * TVPImportFuncPtreba070d1583ca5f5d02630ba33a5504b = NULL;
void * TVPImportFuncPtree474537852ce5eb165cb1761950faba = NULL;
void * TVPImportFuncPtreed221c603243522667e2f1c6ace3ba4 = NULL;
void * TVPImportFuncPtr1f973c5e3cfaf00fa752b7e22d7ba481 = NULL;
void * TVPImportFuncPtrb9d5260bba9edd7503f1adf882218979 = NULL;
void * TVPImportFuncPtraedbd2eda61145de808e295331884245 = NULL;
void * TVPImportFuncPtrce0f184e84752eb279e4f900d8b53c18 = NULL;
void * TVPImportFuncPtr0217d49393163b80897d044c1d93092f = NULL;
void * TVPImportFuncPtr5bbd9d5b364840e9615af35a62f69d7d = NULL;
void * TVPImportFuncPtr2b2837e81fcaeec35f61a2a3ecf2fb2d = NULL;
void * TVPImportFuncPtrbb0706a78e9066944bfbffd1406be2d4 = NULL;
void * TVPImportFuncPtr770e67c91215292980b88cc6efb9f2a5 = NULL;
void * TVPImportFuncPtr068ab11f05731f2c2e9ea8c5fdb16a9f = NULL;
void * TVPImportFuncPtrb9873a0ad2653952cb2948b817e786e4 = NULL;
void * TVPImportFuncPtr11d9804ae4db32d731af69c397769cbf = NULL;
void * TVPImportFuncPtr421f5aa6dbaaaf946f74942c77aac9bc = NULL;
void * TVPImportFuncPtr563ee9dcb14a2914fc246e64679f42b5 = NULL;
void * TVPImportFuncPtre23a54b6b80bd03111a40f669524724f = NULL;
void * TVPImportFuncPtrc90c8bbd18a7190636ae4269c36ad005 = NULL;
void * TVPImportFuncPtr03c54a8e8c86e171f868a624e490691f = NULL;
void * TVPImportFuncPtr30b63f3cc59b39f1a71829bbbdf6e45d = NULL;
void * TVPImportFuncPtr705bcc30a0561ec679c2267e1a573b23 = NULL;
void * TVPImportFuncPtr5c627d080007e455b0393a9b4457cd4d = NULL;
void * TVPImportFuncPtr72a64cecd44d80f95fc93faf0d239e32 = NULL;
void * TVPImportFuncPtref838904712bfdc614dbc689fbe7fb18 = NULL;
void * TVPImportFuncPtracc97936adc40656e824cfdf7a34e20c = NULL;
void * TVPImportFuncPtr5ea1ba3602f9d9fee344de6c3406d7a3 = NULL;
void * TVPImportFuncPtrd25f0771b8fc7715d69f01d950463a49 = NULL;
void * TVPImportFuncPtrf8ab11c930782ce058e517d0440ec87f = NULL;
void * TVPImportFuncPtrb8157e369d53c2d944b76494980ced7b = NULL;
void * TVPImportFuncPtraba94f656b4c1de827d11c72b36a5e9c = NULL;
void * TVPImportFuncPtr0656942f5a95783a4de73ca6e654d3b5 = NULL;
void * TVPImportFuncPtr5c2b7d12713dd5a94ef8e6eff1f79752 = NULL;
void * TVPImportFuncPtr6f1d30ac7e812cc5a059459c47638cd0 = NULL;
void * TVPImportFuncPtr1d51684322635e7848ef53f7f6be8a1e = NULL;
void * TVPImportFuncPtra1f2d56d138a4038fe1678328910a81d = NULL;
void * TVPImportFuncPtrc135ef491b533febfd49696d22a1dd3d = NULL;
void * TVPImportFuncPtr579117a873b466d78bf93e49c4a078da = NULL;
void * TVPImportFuncPtrec8fa08705639eb7ae5d44ab63dea5e8 = NULL;
void * TVPImportFuncPtrb49dc1cda6109256815dae7b4293725d = NULL;
void * TVPImportFuncPtr912a670f56707ac70f2fee13660c2af8 = NULL;
void * TVPImportFuncPtrd0159986645df76b8c66fdb662efffde = NULL;
void * TVPImportFuncPtrcd7a2e6f91bf8d2daa3e28139d7d9f5c = NULL;
void * TVPImportFuncPtr676004ca892b2bfee6859d0bb132fdd7 = NULL;
void * TVPImportFuncPtrd4b161d8a745baa5e2113669773a758f = NULL;
void * TVPImportFuncPtref7537293f6e3b6127480f6c5fd018a1 = NULL;
void * TVPImportFuncPtr6f6f73b75cffe40a28566d1832ae1224 = NULL;
void * TVPImportFuncPtr7adc5aad39e459e01543d07c239efe57 = NULL;
void * TVPImportFuncPtr3ff6b480097eec3f5fdb7bfad685fd2a = NULL;
void * TVPImportFuncPtrb2c50c3a1dfea7e9d05fed69818bafc3 = NULL;
void * TVPImportFuncPtr8024df9077e2c85b5b718ad2c87e57e7 = NULL;
void * TVPImportFuncPtr989769d4eb8e42e9c9bbe721b296406c = NULL;
void * TVPImportFuncPtrcc1ac928b5c31570dfba7ed8f565be4b = NULL;
void * TVPImportFuncPtr62931efed5729a332e60bd1f7c7cecdf = NULL;
void * TVPImportFuncPtr53c18160b157088f72a9afd79737b48b = NULL;
void * TVPImportFuncPtr48135697fd7f4df87402a7dd4d761555 = NULL;
void * TVPImportFuncPtre2c71cf04e876069eb7315c800a96898 = NULL;
void * TVPImportFuncPtr1f63c018cf805ca1168af192cf8a4b41 = NULL;
void * TVPImportFuncPtr704a9574dafd3669e10d546549948e03 = NULL;
void * TVPImportFuncPtr97905c510b9502c20c9322c9f5fb4188 = NULL;
void * TVPImportFuncPtrb23e84230c4736667279c7a71f4ca53e = NULL;
void * TVPImportFuncPtreb41fc900b0a6e3aba9d531f266137f1 = NULL;
void * TVPImportFuncPtr5bd02c627b74bbb22d5a525b8bcbbd27 = NULL;
void * TVPImportFuncPtrcc82e6a6b31ea743b9ebbdeed1ddedc3 = NULL;
void * TVPImportFuncPtr247b25d497e48bc0191fdb2ac530f4ca = NULL;
void * TVPImportFuncPtr6bbea3af36c35631641cc8356ff65475 = NULL;
void * TVPImportFuncPtrcac02dfd62ba94abf6a346bef0bf3ab9 = NULL;
void * TVPImportFuncPtr68eeb36d76d88ff00014f04b23454254 = NULL;
void * TVPImportFuncPtr65e03b1c849b6e9cb5c478024aa9a5b7 = NULL;
void * TVPImportFuncPtr7670c0c5630625ee6a73b7b9ee093650 = NULL;
void * TVPImportFuncPtr68a0abce6eefa08e74353ec48c4c87a8 = NULL;
void * TVPImportFuncPtrccb6e098b9a0791a0f20e9f1af55e341 = NULL;
void * TVPImportFuncPtr0f817efe47b451fd719c05a104c2b803 = NULL;
void * TVPImportFuncPtrefad1a3d774747bd2b5adb221ede2678 = NULL;
void * TVPImportFuncPtr563285ed004ddd2945f91db7b5347d3c = NULL;
void * TVPImportFuncPtr4c032260ef83d44bfe05fdc16843a8f9 = NULL;
void * TVPImportFuncPtr96fd614457f06499a430b0c6e0e8a941 = NULL;
void * TVPImportFuncPtrd6e36d304ff7253088ab4bc1aaf13a98 = NULL;
void * TVPImportFuncPtreddacf49735189e23d9d49831851ffdb = NULL;
void * TVPImportFuncPtr20275a5de4aef464b85d3f6db2800063 = NULL;
void * TVPImportFuncPtr872d1c626e6d4e3d5e86a257f0b14536 = NULL;
void * TVPImportFuncPtra7ebb70cdec339f26c2ea7fd9a471b88 = NULL;
void * TVPImportFuncPtrd748ffef5cde2a6a3333e75b7fa3fb49 = NULL;
void * TVPImportFuncPtr15e1fe0e6230e7b60e216e266f927f7b = NULL;
void * TVPImportFuncPtrf8179eafd0cbe8116874310519207dc0 = NULL;
void * TVPImportFuncPtraccbc3bed3223d552de2723366cfc2b6 = NULL;
void * TVPImportFuncPtre2c3e74d2a20a601c1f393348f58aeb2 = NULL;
void * TVPImportFuncPtre0163a6ca3397c2e71715132cccefa1d = NULL;
void * TVPImportFuncPtr2c3ea1ea88799dfde81025bf1959333a = NULL;
void * TVPImportFuncPtra6bb56b3f4b7a89fe78d63956a0f444c = NULL;
void * TVPImportFuncPtr09a81ac18a121d8fbb67285a081bf9c6 = NULL;
void * TVPImportFuncPtr46fdfe0f5369bf234c3ed60a43947d9d = NULL;
void * TVPImportFuncPtrd866cb6c8a47444bbac60eeffbfc6d96 = NULL;
void * TVPImportFuncPtr7b5718fc67458089c685dbb900126890 = NULL;
void * TVPImportFuncPtr5713dfe9525662357d3819229e0204c2 = NULL;
void * TVPImportFuncPtr8954a6b4a7f8b378c2af16a00d5059b0 = NULL;
void * TVPImportFuncPtr2ed4faa38db6f3dee0dea18ebe973d35 = NULL;
void * TVPImportFuncPtrd0338dedb0af532d22f2075a85373548 = NULL;
void * TVPImportFuncPtr583d57c3bb9491f8f9904c266d3f52e8 = NULL;
void * TVPImportFuncPtr8ac206da43e322eb8e34fce2b0959656 = NULL;
void * TVPImportFuncPtr14f5f97d90bd8da89b68d035367f4ba4 = NULL;
void * TVPImportFuncPtrac3b21181ef4c1be73cf5e0edb4e1a8f = NULL;
void * TVPImportFuncPtr1d7d97509292a4ca9269f2539dcc70fd = NULL;
void * TVPImportFuncPtrc4033f54a99517783b8d6ad23c90aeed = NULL;
void * TVPImportFuncPtrf19e38d48755c971fc35408ac65562fa = NULL;
void * TVPImportFuncPtre01204e226d8aa9520b3620b68da6196 = NULL;
void * TVPImportFuncPtrb50000da98f1257cf789fc63fb1fda02 = NULL;
void * TVPImportFuncPtrc55f38b1a7623646aa5cc45d4f4f479b = NULL;
void * TVPImportFuncPtr983d270549ec0e83e2a863b43e1e6f70 = NULL;
void * TVPImportFuncPtrb48d779dc6a881c67c5f8fa12655aa28 = NULL;
void * TVPImportFuncPtrd3967c6e24d0c4ad107a03c1cadd57b1 = NULL;
void * TVPImportFuncPtr6b6f416b5725a7cafb4774ffc3a00f10 = NULL;
void * TVPImportFuncPtrbc7fc5dfa228152a09d2230823c2fe71 = NULL;
void * TVPImportFuncPtra1cb941317b947beb88e29fa8d46a2be = NULL;
void * TVPImportFuncPtr8e185e82bb27a7fb40f0b08f560a57e9 = NULL;
void * TVPImportFuncPtr4b7b264b61ee0eea68213934217f5865 = NULL;
void * TVPImportFuncPtre872f12593d6853ebdffebbb5d003c10 = NULL;
void * TVPImportFuncPtre86fcf60fa658129d937de3728d3c432 = NULL;
void * TVPImportFuncPtr350741a7398a187628866f5b397c7a99 = NULL;
void * TVPImportFuncPtr3b5a3e187077b0b5eac9a040c99dd9e7 = NULL;
void * TVPImportFuncPtr2d9b2bb2cd57220048fe170f1e960cb7 = NULL;
void * TVPImportFuncPtr260624e275a20115e8861eb7b0383971 = NULL;
void * TVPImportFuncPtr15b31724287dbbecb775b2e46dc35fb9 = NULL;
void * TVPImportFuncPtrff652293eef07b5a7ec4f372e5504e2c = NULL;
void * TVPImportFuncPtr99b773033e9a2c631b483d4d0e3881f8 = NULL;
void * TVPImportFuncPtr3787960fc29b8545629d894ff46d4641 = NULL;
void * TVPImportFuncPtr3fc76257bb1639de4bfa0c0fcedf9c4a = NULL;
void * TVPImportFuncPtr292ee2eeb8131e34368ba9ee144b737a = NULL;
void * TVPImportFuncPtrec144655bc61bfa2c6e9505cc1a0a298 = NULL;
void * TVPImportFuncPtr230218bdabfc34178a8306a54276a3c8 = NULL;
void * TVPImportFuncPtr617dfb046aaf40078ee76715fa4756af = NULL;
void * TVPImportFuncPtr8116bb2b26dcafd9fefca76e9f1d9b24 = NULL;
void * TVPImportFuncPtr12962f857563cd39b3cb1f9894775cc7 = NULL;
void * TVPImportFuncPtr50c0d25cd9af311a5fb0aca78f691c3b = NULL;
void * TVPImportFuncPtr6c37a1ccda816c4fbab4f0117ca75e8a = NULL;
void * TVPImportFuncPtre21c21762dd0e36d6f7d2cedaac97383 = NULL;
void * TVPImportFuncPtr487ee86557f94113db9a981e08d29caa = NULL;
void * TVPImportFuncPtrdfdfe0e494845bf484612cc97145f85c = NULL;
void * TVPImportFuncPtre74dc11dbd56fb450eed1388a65d3102 = NULL;
void * TVPImportFuncPtr6981c02247de5799ea7dfbd79fdc208d = NULL;
void * TVPImportFuncPtr7c559043315f6ecd7a86ec7d8d820f6d = NULL;
void * TVPImportFuncPtr3a8b6aca73c83d6fc9ce813661ec734d = NULL;
void * TVPImportFuncPtr20d7ce65e240b745b10616bb5da1f897 = NULL;
void * TVPImportFuncPtrf4d1217249674ac9274d358c381afc0b = NULL;
void * TVPImportFuncPtrca77323bbe361f88f68536018fa94c50 = NULL;
void * TVPImportFuncPtr17983ecc7e7fe370bce664281a84c948 = NULL;
void * TVPImportFuncPtr61a2f61030362903d00ba21a3cebecdd = NULL;
void * TVPImportFuncPtre9f985403dbd18540d8230a2af6ed76b = NULL;
void * TVPImportFuncPtrbe0523c9a72ba26cb4bfa3cb188cacf6 = NULL;
void * TVPImportFuncPtr8ac7cf651223c8ba53df90cf4f3d3bbc = NULL;
void * TVPImportFuncPtr873e73aa35096ad4c684d394a10135a6 = NULL;
void * TVPImportFuncPtr3342548f105147c86019ae31ece01d4e = NULL;
void * TVPImportFuncPtr607ee0956cbb16b2afb7cb2227aa6267 = NULL;
void * TVPImportFuncPtr816d84c86e86d5e7c0018d551e741e4f = NULL;
void * TVPImportFuncPtr985fcda0141eb3b4c6bd8342e947f130 = NULL;
void * TVPImportFuncPtrd00e4f9e493334d2f65ea379ff03d717 = NULL;
void * TVPImportFuncPtr0c246e6c7c8798e4c10d2bbfc66326c9 = NULL;
void * TVPImportFuncPtr501015843a83368b3ff1c7c9ef5f3bcb = NULL;
void * TVPImportFuncPtr61d5fc5a060f346752a3a8b6886d17bc = NULL;
void * TVPImportFuncPtr0debe3e1caf0f57572a59917851676d3 = NULL;
void * TVPImportFuncPtree3a36682f48639166ba04a19fe1b332 = NULL;
void * TVPImportFuncPtr4d99b9e38121251b40a90cd2bd5fea63 = NULL;
void * TVPImportFuncPtrf1509827696ebf5627bee1a45d675fb8 = NULL;
void * TVPImportFuncPtrbbb625e23229350453161810c41419dd = NULL;
void * TVPImportFuncPtr489a6aae30de0feff5d3c5fbd42ae325 = NULL;
void * TVPImportFuncPtr6b9a349305f8c689dcfdbcea2566769c = NULL;
void * TVPImportFuncPtr6320d208ce1a570aca52c3cdf7421f7c = NULL;
void * TVPImportFuncPtr0f83f0459badd1cd352041b9243d712f = NULL;
void * TVPImportFuncPtr186a94b2fed609ed2d2a7ac1a2bed87f = NULL;
void * TVPImportFuncPtrbde8efb9971664f2b52fe912745e2791 = NULL;
void * TVPImportFuncPtr386d6fa5cb73e3519b62d20470e5414b = NULL;
void * TVPImportFuncPtrc61f97ec3d99bdbb23afe93870001bbf = NULL;
void * TVPImportFuncPtrf92821f2b23662c6f1256511a626cd3f = NULL;
void * TVPImportFuncPtr76b0732e3e2886897d5f26b4b0545dee = NULL;
void * TVPImportFuncPtr903ed11ef3863850e837bd4b3b1d61a1 = NULL;
void * TVPImportFuncPtr2661124b39595ffafe2fb0bfb7bd2efc = NULL;
void * TVPImportFuncPtrd0b7170e54398c2f9d27dcc513c4cf46 = NULL;
void * TVPImportFuncPtr31bdd2a1eed3785c1422fab5ea6b3ce7 = NULL;
void * TVPImportFuncPtrdbc300d1dadc1a60cb0dcadfb92f1aee = NULL;
void * TVPImportFuncPtr1d4d9f8bdf55bd4c78abd90656af0364 = NULL;
void * TVPImportFuncPtr5c7049e712e84b40ac05942421202de5 = NULL;
void * TVPImportFuncPtr5dca8992bb340d70ba65ddab65c28371 = NULL;
void * TVPImportFuncPtr85f1f38f783ebfcf638f3c443bc9b204 = NULL;
void * TVPImportFuncPtr7d61d143884bfa4b6c50dae11c2b659f = NULL;
void * TVPImportFuncPtr793a2ad7ad3411be3670576a8e6ddcf8 = NULL;
void * TVPImportFuncPtr68d8eec33254f1684e53bbc0aa8b2466 = NULL;
void * TVPImportFuncPtrb09652d2197b29f7d38aff0298c69f17 = NULL;
void * TVPImportFuncPtrbe7db03ddcf1886cb7233e58f19c8c77 = NULL;
void * TVPImportFuncPtrb4c8fedc1ffbe30d9703cb2b8d3c0e7b = NULL;
void * TVPImportFuncPtr77efef3b4ffc0cb577b76304e06e39f3 = NULL;
void * TVPImportFuncPtr0e55187bde599d6585eaabd2c4ac3f02 = NULL;
void * TVPImportFuncPtrf72e3fc3b97a9141b6f516f5e53bf9b8 = NULL;
void * TVPImportFuncPtre7a1ac237f00bb6320d0e0ac7e6d51c6 = NULL;
void * TVPImportFuncPtrd87682f6d691350878077bd101b7f0fc = NULL;
void * TVPImportFuncPtrd7ae155eaabd8e65d6b4d356fe4af496 = NULL;
void * TVPImportFuncPtrbe3a1844ea6af533bd4e7b0a76c826a1 = NULL;
void * TVPImportFuncPtraa531d2c3c87f456e48a14722faa1c1f = NULL;
void * TVPImportFuncPtr6889cd886e1c2e7faf541528636c16c3 = NULL;
void * TVPImportFuncPtr5d9266e6a8a154fe4ba80b0995e109ab = NULL;
void * TVPImportFuncPtra7dc19b023737979ad1ae1ae01d560d2 = NULL;
void * TVPImportFuncPtrd20444b7a6243d668a0d3956d95af510 = NULL;
void * TVPImportFuncPtr1458dec9eee36816c8002d4049840355 = NULL;
void * TVPImportFuncPtr21137ff5351245b1611852301b7f5796 = NULL;
void * TVPImportFuncPtrc07fc4e45fc2dc44d839c5e012d0be60 = NULL;
void * TVPImportFuncPtr6815b962a3122ae967284239932cc656 = NULL;
void * TVPImportFuncPtre96cccbe1f16b0fb74673f2ec3343ff8 = NULL;
void * TVPImportFuncPtre8cd7494f919b18a992cb8c2722b2bf0 = NULL;
void * TVPImportFuncPtr990fdefcafc0de5e8e1f502c1b341e44 = NULL;
void * TVPImportFuncPtrde5d83ba307e822825062377fb76c2ba = NULL;
void * TVPImportFuncPtr5e28bcc0f5ad6a038eb5a6535b56386c = NULL;
void * TVPImportFuncPtre33419e8ede4bb501ab1787cf17c7ca5 = NULL;
void * TVPImportFuncPtr1cd7cb9580c0cf723dea402b85a720b1 = NULL;
void * TVPImportFuncPtrd18ca17fad389ff60ce3caa769083798 = NULL;
void * TVPImportFuncPtr0a959a5ff02530a8eb122e7e1f8ceed3 = NULL;
void * TVPImportFuncPtra4774ea559e64b4667b3845f8540d207 = NULL;
void * TVPImportFuncPtr52eae3e8106494bfa604c15492ecb9f4 = NULL;
void * TVPImportFuncPtr882f458df5e05bb9ab2222e79f6c81cf = NULL;
void * TVPImportFuncPtr6069a18bf7d3f394c230cdcf2f574ef4 = NULL;
void * TVPImportFuncPtr75b60565caf44027cc52b2b5cf6b0ea3 = NULL;
void * TVPImportFuncPtr9d735149c3ad586363895f76645abf2e = NULL;
void * TVPImportFuncPtrea5168fae254acdd8c8db6f1f3d2da03 = NULL;
void * TVPImportFuncPtrf5a42bd5239e1a0be29f92eb838d2c8c = NULL;
void * TVPImportFuncPtr7cc8cd9f415b183b42c546635aeade7f = NULL;
void * TVPImportFuncPtrad2fefa53e05528f9c1fe29d27db0f37 = NULL;
void * TVPImportFuncPtrf3e06fed4c82a9bd1b53252abaf50847 = NULL;
void * TVPImportFuncPtr960db7ea36202bf7ec3bf6b767cc045e = NULL;
void * TVPImportFuncPtr7bf5d357eb52dd206a269b54c8136e0e = NULL;
void * TVPImportFuncPtrba1c9b771c5cdb725128de684af3c9ca = NULL;
void * TVPImportFuncPtr69cc6311196adc134fd153c4c5346bc5 = NULL;
void * TVPImportFuncPtr8ed68f8e79efe1c767f92e7d92eb8b54 = NULL;
void * TVPImportFuncPtr60da1e9ec15b251ff18ddcdf8a3e93e0 = NULL;
void * TVPImportFuncPtref47304bad87a036e38f0319b48c1f6e = NULL;
void * TVPImportFuncPtr182d19020e4e2d5cd1462d7c8ef24d1f = NULL;
void * TVPImportFuncPtr9e1fa429a92a5c99d397a06c20fd6705 = NULL;
void * TVPImportFuncPtr74ac7c291299eb928aa4c2899df5567e = NULL;
void * TVPImportFuncPtrfb645d9ec0ef3fd2aba2b762ef6b9a15 = NULL;
void * TVPImportFuncPtrf988626275257574050ac789f9060a3b = NULL;
void * TVPImportFuncPtr1831064ed23493cef407648763ba4d69 = NULL;
void * TVPImportFuncPtr305390c94750daa7124db3ff6e77931c = NULL;
void * TVPImportFuncPtr4fb384a391bfcf6a3a2932661d3051aa = NULL;
void * TVPImportFuncPtr305537c4820e23cf217a15efb56dba1c = NULL;
void * TVPImportFuncPtraacf83677ca7df75117f7bafa7a53791 = NULL;
void * TVPImportFuncPtrd14b922fefc6c07aa536b94762579fe5 = NULL;
void * TVPImportFuncPtr00fd650a79c603bdeb2f8e36f667a782 = NULL;
void * TVPImportFuncPtra36ee133c07c30185b0bbc6375954e88 = NULL;
void * TVPImportFuncPtrdc657ecacf8e578870314427216864d9 = NULL;
void * TVPImportFuncPtre79d02b58a8bfdee439bc0694d7edd6d = NULL;
void * TVPImportFuncPtr6b7537b66b71d27384bea45bc2bf24b4 = NULL;
void * TVPImportFuncPtrb3456dbad652b52f5bce1889b6f4d0ef = NULL;
void * TVPImportFuncPtr9a50803a03e1ccb60120dff8b92ecdcd = NULL;
void * TVPImportFuncPtr0f6b3940dc72e3e56cd15216b53b9126 = NULL;
void * TVPImportFuncPtr23b647f1c825e214a7465de3ebe9968d = NULL;
void * TVPImportFuncPtr8ec96bc7b777180f23e1a2e43bf9a413 = NULL;
void * TVPImportFuncPtrcffd45014652659638d59abe11daf3be = NULL;
void * TVPImportFuncPtra784285a35b1bc76bb367305b5099e35 = NULL;
void * TVPImportFuncPtr03773751329896facf2003ab79bbc475 = NULL;
void * TVPImportFuncPtr923884216edf134d07d8e70f8f57e827 = NULL;
void * TVPImportFuncPtre48798dc69498f80b6633bb405eda6eb = NULL;
void * TVPImportFuncPtr998a5e1aa5cd85689795348fc540a655 = NULL;
void * TVPImportFuncPtr5f6d263c0d48d03f6eb0dc44c9dd0be2 = NULL;

//---------------------------------------------------------------------------
// tTJSDispatch
//---------------------------------------------------------------------------
tTJSDispatch::tTJSDispatch()
{
	BeforeDestructionCalled = false;
	RefCount = 1;
#ifdef TVP_IN_PLUGIN_STUB // TVP plug-in support
	TVPPluginGlobalRefCount++;
#endif
}
//---------------------------------------------------------------------------
tTJSDispatch::~tTJSDispatch()
{
	if(!BeforeDestructionCalled)
	{
		BeforeDestructionCalled = true;
		BeforeDestruction();
	}
}
//---------------------------------------------------------------------------
tjs_uint TJS_INTF_METHOD  tTJSDispatch::AddRef(void)
{
#ifdef TVP_IN_PLUGIN_STUB // TVP plug-in support
	TVPPluginGlobalRefCount++;
#endif
	return ++RefCount;
}
//---------------------------------------------------------------------------
tjs_uint TJS_INTF_METHOD  tTJSDispatch::Release(void)
{
#ifdef TVP_IN_PLUGIN_STUB // TVP plug-in support
	TVPPluginGlobalRefCount--;
#endif
	if(RefCount == 1) // avoid to call "BeforeDestruction" with RefCount == 0
	{
		// object destruction
		if(!BeforeDestructionCalled)
		{
			BeforeDestructionCalled = true;
			BeforeDestruction();
		}

		if(RefCount == 1) // really ready to destruct ?
		{
			delete this;
			return 0;
		}
	}
	return --RefCount;
}
//---------------------------------------------------------------------------
tjs_error TJS_INTF_METHOD
	tTJSDispatch::FuncCallByNum(
		tjs_uint32 flag,
		tjs_int num,
		tTJSVariant *result,
		tjs_int numparams,
		tTJSVariant **param,
		iTJSDispatch2 *objthis
		)
{
	tjs_char buf[34];
	TJS_int_to_str(num, buf);
	return FuncCall(flag, buf, NULL, result, numparams, param, objthis);
}
//---------------------------------------------------------------------------
tjs_error TJS_INTF_METHOD
	tTJSDispatch::PropGetByNum(
		tjs_uint32 flag,
		tjs_int num,
		tTJSVariant *result,
		iTJSDispatch2 *objthis
		)
{
	tjs_char buf[34];
	TJS_int_to_str(num, buf);
	return PropGet(flag, buf, NULL, result, objthis);
}
//---------------------------------------------------------------------------
tjs_error TJS_INTF_METHOD
	tTJSDispatch::PropSetByNum(
		tjs_uint32 flag,
		tjs_int num,
		const tTJSVariant *param,
		iTJSDispatch2 *objthis
		)
{
	tjs_char buf[34];
	TJS_int_to_str(num, buf);
	return PropSet(flag, buf, NULL, param, objthis);
}
//---------------------------------------------------------------------------
tjs_error TJS_INTF_METHOD
	tTJSDispatch::GetCountByNum(
		tjs_int *result,
		tjs_int num,
		iTJSDispatch2 *objthis
		)
{
	tjs_char buf[34];
	TJS_int_to_str(num, buf);
	return GetCount(result, buf, NULL, objthis);
}
//---------------------------------------------------------------------------
tjs_error TJS_INTF_METHOD
	tTJSDispatch::DeleteMemberByNum(
		tjs_uint32 flag,
		tjs_int num,
		iTJSDispatch2 *objthis
		)
{
	tjs_char buf[34];
	TJS_int_to_str(num, buf);
	return DeleteMember(flag, buf, NULL, objthis);
}
//---------------------------------------------------------------------------
tjs_error TJS_INTF_METHOD
	tTJSDispatch::InvalidateByNum(
		tjs_uint32 flag,
		tjs_int num,
		iTJSDispatch2 *objthis
		)
{
	tjs_char buf[34];
	TJS_int_to_str(num, buf);
	return Invalidate(flag, buf, NULL, objthis);
}
//---------------------------------------------------------------------------
tjs_error TJS_INTF_METHOD
	tTJSDispatch::IsValidByNum(
		tjs_uint32 flag,
		tjs_int num,
		iTJSDispatch2 *objthis
		)
{
	tjs_char buf[34];
	TJS_int_to_str(num, buf);
	return IsValid(flag, buf, NULL, objthis);
}
//---------------------------------------------------------------------------
tjs_error TJS_INTF_METHOD
	tTJSDispatch::CreateNewByNum(
		tjs_uint32 flag,
		tjs_int num,
		iTJSDispatch2 **result,
		tjs_int numparams,
		tTJSVariant **param,
		iTJSDispatch2 *objthis
		)
{
	tjs_char buf[34];
	TJS_int_to_str(num, buf);
	return CreateNew(flag, buf, NULL, result, numparams, param, objthis);
}
//---------------------------------------------------------------------------
tjs_error TJS_INTF_METHOD
	tTJSDispatch::IsInstanceOfByNum(
		tjs_uint32 flag,
		tjs_int num,
		const tjs_char *classname,
		iTJSDispatch2 *objthis
		)
{
	tjs_char buf[34];
	TJS_int_to_str(num, buf);
	return IsInstanceOf(flag, buf, NULL, classname, objthis);
}
//---------------------------------------------------------------------------
tjs_error TJS_INTF_METHOD
	tTJSDispatch::OperationByNum(
		tjs_uint32 flag,
		tjs_int num,
		tTJSVariant *result,
		const tTJSVariant *param,
		iTJSDispatch2 *objthis
		)
{
	tjs_char buf[34];
	TJS_int_to_str(num, buf);
	return Operation(flag, buf, NULL, result, param, objthis);
}
//---------------------------------------------------------------------------
tjs_error TJS_INTF_METHOD
	tTJSDispatch::Operation(
		tjs_uint32 flag,
		const tjs_char *membername,
		tjs_uint32 *hint,
		tTJSVariant *result,
		const tTJSVariant *param,
		iTJSDispatch2 *objthis
	)
{
	tjs_uint32 op = flag & TJS_OP_MASK;

	if(op!=TJS_OP_INC && op!=TJS_OP_DEC && param == NULL)
		return TJS_E_INVALIDPARAM;

	if(op<TJS_OP_MIN || op>TJS_OP_MAX)
		return TJS_E_INVALIDPARAM;

	tTJSVariant tmp;
	tjs_error hr;
	hr = PropGet(0, membername, hint, &tmp, objthis);
	if(TJS_FAILED(hr)) return hr;

	TJSDoVariantOperation(op, tmp, param);

	hr = PropSet(0, membername, hint, &tmp, objthis);
	if(TJS_FAILED(hr)) return hr;

	if(result) result->CopyRef(tmp);

	return TJS_S_OK;
}
//---------------------------------------------------------------------------

//---------------------------------------------------------------------------
// exception protected function stub
//---------------------------------------------------------------------------


static bool TJS_USERENTRY _CatchFuncCall(void *data, const tTVPExceptionDesc & desc)
{
	throw desc;
}
struct t_iTJSDispatch2_AddRef
{
	tjs_uint _ret;
	iTJSDispatch2 * _this;
	t_iTJSDispatch2_AddRef(
			iTJSDispatch2 * _this_
			) :
		_this(_this_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_AddRef(void *data)
{
	t_iTJSDispatch2_AddRef * arg = (t_iTJSDispatch2_AddRef *)data;
	arg->_ret = 
	arg->_this->AddRef(
		
		);
}
tjs_uint Try_iTJSDispatch2_AddRef(iTJSDispatch2 * _this)
{
	t_iTJSDispatch2_AddRef arg(
		_this
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_AddRef, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_Release
{
	tjs_uint _ret;
	iTJSDispatch2 * _this;
	t_iTJSDispatch2_Release(
			iTJSDispatch2 * _this_
			) :
		_this(_this_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_Release(void *data)
{
	t_iTJSDispatch2_Release * arg = (t_iTJSDispatch2_Release *)data;
	arg->_ret = 
	arg->_this->Release(
		
		);
}
tjs_uint Try_iTJSDispatch2_Release(iTJSDispatch2 * _this)
{
	t_iTJSDispatch2_Release arg(
		_this
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_Release, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_FuncCall
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	const tjs_char * membername;
	tjs_uint32 *hint;
	tTJSVariant *result;
	tjs_int numparams;
	tTJSVariant **param;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_FuncCall(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			const tjs_char * membername_,
			tjs_uint32 *hint_,
			tTJSVariant *result_,
			tjs_int numparams_,
			tTJSVariant **param_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		membername(membername_),
		hint(hint_),
		result(result_),
		numparams(numparams_),
		param(param_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_FuncCall(void *data)
{
	t_iTJSDispatch2_FuncCall * arg = (t_iTJSDispatch2_FuncCall *)data;
	arg->_ret = 
	arg->_this->FuncCall(
		arg->flag,
		arg->membername,
		arg->hint,
		arg->result,
		arg->numparams,
		arg->param,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_FuncCall(iTJSDispatch2 * _this, tjs_uint32 flag, const tjs_char * membername, tjs_uint32 *hint, tTJSVariant *result, tjs_int numparams, tTJSVariant **param, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_FuncCall arg(
		_this,
		flag,
		membername,
		hint,
		result,
		numparams,
		param,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_FuncCall, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_FuncCallByNum
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	tjs_int num;
	tTJSVariant *result;
	tjs_int numparams;
	tTJSVariant **param;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_FuncCallByNum(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			tjs_int num_,
			tTJSVariant *result_,
			tjs_int numparams_,
			tTJSVariant **param_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		num(num_),
		result(result_),
		numparams(numparams_),
		param(param_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_FuncCallByNum(void *data)
{
	t_iTJSDispatch2_FuncCallByNum * arg = (t_iTJSDispatch2_FuncCallByNum *)data;
	arg->_ret = 
	arg->_this->FuncCallByNum(
		arg->flag,
		arg->num,
		arg->result,
		arg->numparams,
		arg->param,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_FuncCallByNum(iTJSDispatch2 * _this, tjs_uint32 flag, tjs_int num, tTJSVariant *result, tjs_int numparams, tTJSVariant **param, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_FuncCallByNum arg(
		_this,
		flag,
		num,
		result,
		numparams,
		param,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_FuncCallByNum, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_PropGet
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	const tjs_char * membername;
	tjs_uint32 *hint;
	tTJSVariant *result;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_PropGet(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			const tjs_char * membername_,
			tjs_uint32 *hint_,
			tTJSVariant *result_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		membername(membername_),
		hint(hint_),
		result(result_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_PropGet(void *data)
{
	t_iTJSDispatch2_PropGet * arg = (t_iTJSDispatch2_PropGet *)data;
	arg->_ret = 
	arg->_this->PropGet(
		arg->flag,
		arg->membername,
		arg->hint,
		arg->result,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_PropGet(iTJSDispatch2 * _this, tjs_uint32 flag, const tjs_char * membername, tjs_uint32 *hint, tTJSVariant *result, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_PropGet arg(
		_this,
		flag,
		membername,
		hint,
		result,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_PropGet, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_PropGetByNum
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	tjs_int num;
	tTJSVariant *result;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_PropGetByNum(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			tjs_int num_,
			tTJSVariant *result_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		num(num_),
		result(result_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_PropGetByNum(void *data)
{
	t_iTJSDispatch2_PropGetByNum * arg = (t_iTJSDispatch2_PropGetByNum *)data;
	arg->_ret = 
	arg->_this->PropGetByNum(
		arg->flag,
		arg->num,
		arg->result,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_PropGetByNum(iTJSDispatch2 * _this, tjs_uint32 flag, tjs_int num, tTJSVariant *result, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_PropGetByNum arg(
		_this,
		flag,
		num,
		result,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_PropGetByNum, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_PropSet
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	const tjs_char *membername;
	tjs_uint32 *hint;
	const tTJSVariant *param;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_PropSet(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			const tjs_char *membername_,
			tjs_uint32 *hint_,
			const tTJSVariant *param_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		membername(membername_),
		hint(hint_),
		param(param_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_PropSet(void *data)
{
	t_iTJSDispatch2_PropSet * arg = (t_iTJSDispatch2_PropSet *)data;
	arg->_ret = 
	arg->_this->PropSet(
		arg->flag,
		arg->membername,
		arg->hint,
		arg->param,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_PropSet(iTJSDispatch2 * _this, tjs_uint32 flag, const tjs_char *membername, tjs_uint32 *hint, const tTJSVariant *param, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_PropSet arg(
		_this,
		flag,
		membername,
		hint,
		param,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_PropSet, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_PropSetByNum
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	tjs_int num;
	const tTJSVariant *param;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_PropSetByNum(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			tjs_int num_,
			const tTJSVariant *param_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		num(num_),
		param(param_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_PropSetByNum(void *data)
{
	t_iTJSDispatch2_PropSetByNum * arg = (t_iTJSDispatch2_PropSetByNum *)data;
	arg->_ret = 
	arg->_this->PropSetByNum(
		arg->flag,
		arg->num,
		arg->param,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_PropSetByNum(iTJSDispatch2 * _this, tjs_uint32 flag, tjs_int num, const tTJSVariant *param, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_PropSetByNum arg(
		_this,
		flag,
		num,
		param,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_PropSetByNum, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_GetCount
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_int *result;
	const tjs_char *membername;
	tjs_uint32 *hint;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_GetCount(
			iTJSDispatch2 * _this_,
			tjs_int *result_,
			const tjs_char *membername_,
			tjs_uint32 *hint_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		result(result_),
		membername(membername_),
		hint(hint_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_GetCount(void *data)
{
	t_iTJSDispatch2_GetCount * arg = (t_iTJSDispatch2_GetCount *)data;
	arg->_ret = 
	arg->_this->GetCount(
		arg->result,
		arg->membername,
		arg->hint,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_GetCount(iTJSDispatch2 * _this, tjs_int *result, const tjs_char *membername, tjs_uint32 *hint, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_GetCount arg(
		_this,
		result,
		membername,
		hint,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_GetCount, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_GetCountByNum
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_int *result;
	tjs_int num;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_GetCountByNum(
			iTJSDispatch2 * _this_,
			tjs_int *result_,
			tjs_int num_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		result(result_),
		num(num_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_GetCountByNum(void *data)
{
	t_iTJSDispatch2_GetCountByNum * arg = (t_iTJSDispatch2_GetCountByNum *)data;
	arg->_ret = 
	arg->_this->GetCountByNum(
		arg->result,
		arg->num,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_GetCountByNum(iTJSDispatch2 * _this, tjs_int *result, tjs_int num, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_GetCountByNum arg(
		_this,
		result,
		num,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_GetCountByNum, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_PropSetByVS
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	tTJSVariantString *membername;
	const tTJSVariant *param;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_PropSetByVS(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			tTJSVariantString *membername_,
			const tTJSVariant *param_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		membername(membername_),
		param(param_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_PropSetByVS(void *data)
{
	t_iTJSDispatch2_PropSetByVS * arg = (t_iTJSDispatch2_PropSetByVS *)data;
	arg->_ret = 
	arg->_this->PropSetByVS(
		arg->flag,
		arg->membername,
		arg->param,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_PropSetByVS(iTJSDispatch2 * _this, tjs_uint32 flag, tTJSVariantString *membername, const tTJSVariant *param, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_PropSetByVS arg(
		_this,
		flag,
		membername,
		param,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_PropSetByVS, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_EnumMembers
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	tTJSVariantClosure *callback;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_EnumMembers(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			tTJSVariantClosure *callback_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		callback(callback_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_EnumMembers(void *data)
{
	t_iTJSDispatch2_EnumMembers * arg = (t_iTJSDispatch2_EnumMembers *)data;
	arg->_ret = 
	arg->_this->EnumMembers(
		arg->flag,
		arg->callback,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_EnumMembers(iTJSDispatch2 * _this, tjs_uint32 flag, tTJSVariantClosure *callback, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_EnumMembers arg(
		_this,
		flag,
		callback,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_EnumMembers, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_DeleteMember
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	const tjs_char *membername;
	tjs_uint32 *hint;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_DeleteMember(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			const tjs_char *membername_,
			tjs_uint32 *hint_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		membername(membername_),
		hint(hint_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_DeleteMember(void *data)
{
	t_iTJSDispatch2_DeleteMember * arg = (t_iTJSDispatch2_DeleteMember *)data;
	arg->_ret = 
	arg->_this->DeleteMember(
		arg->flag,
		arg->membername,
		arg->hint,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_DeleteMember(iTJSDispatch2 * _this, tjs_uint32 flag, const tjs_char *membername, tjs_uint32 *hint, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_DeleteMember arg(
		_this,
		flag,
		membername,
		hint,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_DeleteMember, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_DeleteMemberByNum
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	tjs_int num;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_DeleteMemberByNum(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			tjs_int num_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		num(num_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_DeleteMemberByNum(void *data)
{
	t_iTJSDispatch2_DeleteMemberByNum * arg = (t_iTJSDispatch2_DeleteMemberByNum *)data;
	arg->_ret = 
	arg->_this->DeleteMemberByNum(
		arg->flag,
		arg->num,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_DeleteMemberByNum(iTJSDispatch2 * _this, tjs_uint32 flag, tjs_int num, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_DeleteMemberByNum arg(
		_this,
		flag,
		num,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_DeleteMemberByNum, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_Invalidate
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	const tjs_char *membername;
	tjs_uint32 *hint;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_Invalidate(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			const tjs_char *membername_,
			tjs_uint32 *hint_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		membername(membername_),
		hint(hint_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_Invalidate(void *data)
{
	t_iTJSDispatch2_Invalidate * arg = (t_iTJSDispatch2_Invalidate *)data;
	arg->_ret = 
	arg->_this->Invalidate(
		arg->flag,
		arg->membername,
		arg->hint,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_Invalidate(iTJSDispatch2 * _this, tjs_uint32 flag, const tjs_char *membername, tjs_uint32 *hint, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_Invalidate arg(
		_this,
		flag,
		membername,
		hint,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_Invalidate, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_InvalidateByNum
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	tjs_int num;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_InvalidateByNum(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			tjs_int num_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		num(num_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_InvalidateByNum(void *data)
{
	t_iTJSDispatch2_InvalidateByNum * arg = (t_iTJSDispatch2_InvalidateByNum *)data;
	arg->_ret = 
	arg->_this->InvalidateByNum(
		arg->flag,
		arg->num,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_InvalidateByNum(iTJSDispatch2 * _this, tjs_uint32 flag, tjs_int num, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_InvalidateByNum arg(
		_this,
		flag,
		num,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_InvalidateByNum, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_IsValid
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	const tjs_char *membername;
	tjs_uint32 *hint;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_IsValid(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			const tjs_char *membername_,
			tjs_uint32 *hint_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		membername(membername_),
		hint(hint_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_IsValid(void *data)
{
	t_iTJSDispatch2_IsValid * arg = (t_iTJSDispatch2_IsValid *)data;
	arg->_ret = 
	arg->_this->IsValid(
		arg->flag,
		arg->membername,
		arg->hint,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_IsValid(iTJSDispatch2 * _this, tjs_uint32 flag, const tjs_char *membername, tjs_uint32 *hint, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_IsValid arg(
		_this,
		flag,
		membername,
		hint,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_IsValid, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_IsValidByNum
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	tjs_int num;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_IsValidByNum(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			tjs_int num_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		num(num_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_IsValidByNum(void *data)
{
	t_iTJSDispatch2_IsValidByNum * arg = (t_iTJSDispatch2_IsValidByNum *)data;
	arg->_ret = 
	arg->_this->IsValidByNum(
		arg->flag,
		arg->num,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_IsValidByNum(iTJSDispatch2 * _this, tjs_uint32 flag, tjs_int num, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_IsValidByNum arg(
		_this,
		flag,
		num,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_IsValidByNum, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_CreateNew
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	const tjs_char * membername;
	tjs_uint32 *hint;
	iTJSDispatch2 **result;
	tjs_int numparams;
	tTJSVariant **param;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_CreateNew(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			const tjs_char * membername_,
			tjs_uint32 *hint_,
			iTJSDispatch2 **result_,
			tjs_int numparams_,
			tTJSVariant **param_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		membername(membername_),
		hint(hint_),
		result(result_),
		numparams(numparams_),
		param(param_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_CreateNew(void *data)
{
	t_iTJSDispatch2_CreateNew * arg = (t_iTJSDispatch2_CreateNew *)data;
	arg->_ret = 
	arg->_this->CreateNew(
		arg->flag,
		arg->membername,
		arg->hint,
		arg->result,
		arg->numparams,
		arg->param,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_CreateNew(iTJSDispatch2 * _this, tjs_uint32 flag, const tjs_char * membername, tjs_uint32 *hint, iTJSDispatch2 **result, tjs_int numparams, tTJSVariant **param, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_CreateNew arg(
		_this,
		flag,
		membername,
		hint,
		result,
		numparams,
		param,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_CreateNew, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_CreateNewByNum
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	tjs_int num;
	iTJSDispatch2 **result;
	tjs_int numparams;
	tTJSVariant **param;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_CreateNewByNum(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			tjs_int num_,
			iTJSDispatch2 **result_,
			tjs_int numparams_,
			tTJSVariant **param_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		num(num_),
		result(result_),
		numparams(numparams_),
		param(param_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_CreateNewByNum(void *data)
{
	t_iTJSDispatch2_CreateNewByNum * arg = (t_iTJSDispatch2_CreateNewByNum *)data;
	arg->_ret = 
	arg->_this->CreateNewByNum(
		arg->flag,
		arg->num,
		arg->result,
		arg->numparams,
		arg->param,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_CreateNewByNum(iTJSDispatch2 * _this, tjs_uint32 flag, tjs_int num, iTJSDispatch2 **result, tjs_int numparams, tTJSVariant **param, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_CreateNewByNum arg(
		_this,
		flag,
		num,
		result,
		numparams,
		param,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_CreateNewByNum, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_Reserved1
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	t_iTJSDispatch2_Reserved1(
			iTJSDispatch2 * _this_
			) :
		_this(_this_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_Reserved1(void *data)
{
	t_iTJSDispatch2_Reserved1 * arg = (t_iTJSDispatch2_Reserved1 *)data;
	arg->_ret = 
	arg->_this->Reserved1(
		
		);
}
tjs_error Try_iTJSDispatch2_Reserved1(iTJSDispatch2 * _this)
{
	t_iTJSDispatch2_Reserved1 arg(
		_this
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_Reserved1, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_IsInstanceOf
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	const tjs_char *membername;
	tjs_uint32 *hint;
	const tjs_char *classname;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_IsInstanceOf(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			const tjs_char *membername_,
			tjs_uint32 *hint_,
			const tjs_char *classname_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		membername(membername_),
		hint(hint_),
		classname(classname_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_IsInstanceOf(void *data)
{
	t_iTJSDispatch2_IsInstanceOf * arg = (t_iTJSDispatch2_IsInstanceOf *)data;
	arg->_ret = 
	arg->_this->IsInstanceOf(
		arg->flag,
		arg->membername,
		arg->hint,
		arg->classname,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_IsInstanceOf(iTJSDispatch2 * _this, tjs_uint32 flag, const tjs_char *membername, tjs_uint32 *hint, const tjs_char *classname, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_IsInstanceOf arg(
		_this,
		flag,
		membername,
		hint,
		classname,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_IsInstanceOf, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_IsInstanceOfByNum
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	tjs_int num;
	const tjs_char *classname;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_IsInstanceOfByNum(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			tjs_int num_,
			const tjs_char *classname_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		num(num_),
		classname(classname_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_IsInstanceOfByNum(void *data)
{
	t_iTJSDispatch2_IsInstanceOfByNum * arg = (t_iTJSDispatch2_IsInstanceOfByNum *)data;
	arg->_ret = 
	arg->_this->IsInstanceOfByNum(
		arg->flag,
		arg->num,
		arg->classname,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_IsInstanceOfByNum(iTJSDispatch2 * _this, tjs_uint32 flag, tjs_int num, const tjs_char *classname, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_IsInstanceOfByNum arg(
		_this,
		flag,
		num,
		classname,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_IsInstanceOfByNum, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_Operation
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	const tjs_char *membername;
	tjs_uint32 *hint;
	tTJSVariant *result;
	const tTJSVariant *param;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_Operation(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			const tjs_char *membername_,
			tjs_uint32 *hint_,
			tTJSVariant *result_,
			const tTJSVariant *param_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		membername(membername_),
		hint(hint_),
		result(result_),
		param(param_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_Operation(void *data)
{
	t_iTJSDispatch2_Operation * arg = (t_iTJSDispatch2_Operation *)data;
	arg->_ret = 
	arg->_this->Operation(
		arg->flag,
		arg->membername,
		arg->hint,
		arg->result,
		arg->param,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_Operation(iTJSDispatch2 * _this, tjs_uint32 flag, const tjs_char *membername, tjs_uint32 *hint, tTJSVariant *result, const tTJSVariant *param, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_Operation arg(
		_this,
		flag,
		membername,
		hint,
		result,
		param,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_Operation, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_OperationByNum
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	tjs_int num;
	tTJSVariant *result;
	const tTJSVariant *param;
	iTJSDispatch2 *objthis;
	t_iTJSDispatch2_OperationByNum(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			tjs_int num_,
			tTJSVariant *result_,
			const tTJSVariant *param_,
			iTJSDispatch2 *objthis_
			) :
		_this(_this_),
		flag(flag_),
		num(num_),
		result(result_),
		param(param_),
		objthis(objthis_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_OperationByNum(void *data)
{
	t_iTJSDispatch2_OperationByNum * arg = (t_iTJSDispatch2_OperationByNum *)data;
	arg->_ret = 
	arg->_this->OperationByNum(
		arg->flag,
		arg->num,
		arg->result,
		arg->param,
		arg->objthis
		);
}
tjs_error Try_iTJSDispatch2_OperationByNum(iTJSDispatch2 * _this, tjs_uint32 flag, tjs_int num, tTJSVariant *result, const tTJSVariant *param, iTJSDispatch2 *objthis)
{
	t_iTJSDispatch2_OperationByNum arg(
		_this,
		flag,
		num,
		result,
		param,
		objthis
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_OperationByNum, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_NativeInstanceSupport
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	tjs_int32 classid;
	iTJSNativeInstance **pointer;
	t_iTJSDispatch2_NativeInstanceSupport(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			tjs_int32 classid_,
			iTJSNativeInstance **pointer_
			) :
		_this(_this_),
		flag(flag_),
		classid(classid_),
		pointer(pointer_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_NativeInstanceSupport(void *data)
{
	t_iTJSDispatch2_NativeInstanceSupport * arg = (t_iTJSDispatch2_NativeInstanceSupport *)data;
	arg->_ret = 
	arg->_this->NativeInstanceSupport(
		arg->flag,
		arg->classid,
		arg->pointer
		);
}
tjs_error Try_iTJSDispatch2_NativeInstanceSupport(iTJSDispatch2 * _this, tjs_uint32 flag, tjs_int32 classid, iTJSNativeInstance **pointer)
{
	t_iTJSDispatch2_NativeInstanceSupport arg(
		_this,
		flag,
		classid,
		pointer
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_NativeInstanceSupport, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_ClassInstanceInfo
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	tjs_uint32 flag;
	tjs_uint num;
	tTJSVariant *value;
	t_iTJSDispatch2_ClassInstanceInfo(
			iTJSDispatch2 * _this_,
			tjs_uint32 flag_,
			tjs_uint num_,
			tTJSVariant *value_
			) :
		_this(_this_),
		flag(flag_),
		num(num_),
		value(value_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_ClassInstanceInfo(void *data)
{
	t_iTJSDispatch2_ClassInstanceInfo * arg = (t_iTJSDispatch2_ClassInstanceInfo *)data;
	arg->_ret = 
	arg->_this->ClassInstanceInfo(
		arg->flag,
		arg->num,
		arg->value
		);
}
tjs_error Try_iTJSDispatch2_ClassInstanceInfo(iTJSDispatch2 * _this, tjs_uint32 flag, tjs_uint num, tTJSVariant *value)
{
	t_iTJSDispatch2_ClassInstanceInfo arg(
		_this,
		flag,
		num,
		value
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_ClassInstanceInfo, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_Reserved2
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	t_iTJSDispatch2_Reserved2(
			iTJSDispatch2 * _this_
			) :
		_this(_this_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_Reserved2(void *data)
{
	t_iTJSDispatch2_Reserved2 * arg = (t_iTJSDispatch2_Reserved2 *)data;
	arg->_ret = 
	arg->_this->Reserved2(
		
		);
}
tjs_error Try_iTJSDispatch2_Reserved2(iTJSDispatch2 * _this)
{
	t_iTJSDispatch2_Reserved2 arg(
		_this
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_Reserved2, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
struct t_iTJSDispatch2_Reserved3
{
	tjs_error _ret;
	iTJSDispatch2 * _this;
	t_iTJSDispatch2_Reserved3(
			iTJSDispatch2 * _this_
			) :
		_this(_this_)	{;}

};
static void TJS_USERENTRY _Try_iTJSDispatch2_Reserved3(void *data)
{
	t_iTJSDispatch2_Reserved3 * arg = (t_iTJSDispatch2_Reserved3 *)data;
	arg->_ret = 
	arg->_this->Reserved3(
		
		);
}
tjs_error Try_iTJSDispatch2_Reserved3(iTJSDispatch2 * _this)
{
	t_iTJSDispatch2_Reserved3 arg(
		_this
	);
	TVPDoTryBlock(_Try_iTJSDispatch2_Reserved3, _CatchFuncCall, NULL, &arg);
	return arg._ret;
}
