// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientUniversalPatchMakeChecked.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ClientUniversalPatchMakeChecked_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ClientUniversalPatchMakeChecked_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ClientUniversalPatchMakeChecked_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ClientUniversalPatchMakeChecked_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
class ClientUniversalPatchMakeChecked;
class ClientUniversalPatchMakeCheckedDefaultTypeInternal;
extern ClientUniversalPatchMakeCheckedDefaultTypeInternal _ClientUniversalPatchMakeChecked_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ClientUniversalPatchMakeChecked* Arena::CreateMaybeMessage<::ClientUniversalPatchMakeChecked>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ClientUniversalPatchMakeChecked :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:ClientUniversalPatchMakeChecked) */ {
 public:
  ClientUniversalPatchMakeChecked();
  virtual ~ClientUniversalPatchMakeChecked();

  ClientUniversalPatchMakeChecked(const ClientUniversalPatchMakeChecked& from);
  ClientUniversalPatchMakeChecked(ClientUniversalPatchMakeChecked&& from) noexcept
    : ClientUniversalPatchMakeChecked() {
    *this = ::std::move(from);
  }

  inline ClientUniversalPatchMakeChecked& operator=(const ClientUniversalPatchMakeChecked& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientUniversalPatchMakeChecked& operator=(ClientUniversalPatchMakeChecked&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ClientUniversalPatchMakeChecked& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClientUniversalPatchMakeChecked* internal_default_instance() {
    return reinterpret_cast<const ClientUniversalPatchMakeChecked*>(
               &_ClientUniversalPatchMakeChecked_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClientUniversalPatchMakeChecked& a, ClientUniversalPatchMakeChecked& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientUniversalPatchMakeChecked* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ClientUniversalPatchMakeChecked* New() const final {
    return CreateMaybeMessage<ClientUniversalPatchMakeChecked>(nullptr);
  }

  ClientUniversalPatchMakeChecked* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ClientUniversalPatchMakeChecked>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const ClientUniversalPatchMakeChecked& from);
  void MergeFrom(const ClientUniversalPatchMakeChecked& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ClientUniversalPatchMakeChecked* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ClientUniversalPatchMakeChecked";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSequenceIdFieldNumber = 1,
    kProtectFieldNumber = 2,
    kIconFieldNumber = 3,
  };
  // uint64 SequenceId = 1;
  void clear_sequenceid();
  ::PROTOBUF_NAMESPACE_ID::uint64 sequenceid() const;
  void set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_sequenceid() const;
  void _internal_set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 Protect = 2;
  void clear_protect();
  ::PROTOBUF_NAMESPACE_ID::uint32 protect() const;
  void set_protect(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_protect() const;
  void _internal_set_protect(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 Icon = 3;
  void clear_icon();
  ::PROTOBUF_NAMESPACE_ID::uint32 icon() const;
  void set_icon(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_icon() const;
  void _internal_set_icon(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:ClientUniversalPatchMakeChecked)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sequenceid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 protect_;
  ::PROTOBUF_NAMESPACE_ID::uint32 icon_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ClientUniversalPatchMakeChecked_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientUniversalPatchMakeChecked

// uint64 SequenceId = 1;
inline void ClientUniversalPatchMakeChecked::clear_sequenceid() {
  sequenceid_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalPatchMakeChecked::_internal_sequenceid() const {
  return sequenceid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalPatchMakeChecked::sequenceid() const {
  // @@protoc_insertion_point(field_get:ClientUniversalPatchMakeChecked.SequenceId)
  return _internal_sequenceid();
}
inline void ClientUniversalPatchMakeChecked::_internal_set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  sequenceid_ = value;
}
inline void ClientUniversalPatchMakeChecked::set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_sequenceid(value);
  // @@protoc_insertion_point(field_set:ClientUniversalPatchMakeChecked.SequenceId)
}

// uint32 Protect = 2;
inline void ClientUniversalPatchMakeChecked::clear_protect() {
  protect_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ClientUniversalPatchMakeChecked::_internal_protect() const {
  return protect_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ClientUniversalPatchMakeChecked::protect() const {
  // @@protoc_insertion_point(field_get:ClientUniversalPatchMakeChecked.Protect)
  return _internal_protect();
}
inline void ClientUniversalPatchMakeChecked::_internal_set_protect(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  protect_ = value;
}
inline void ClientUniversalPatchMakeChecked::set_protect(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_protect(value);
  // @@protoc_insertion_point(field_set:ClientUniversalPatchMakeChecked.Protect)
}

// uint32 Icon = 3;
inline void ClientUniversalPatchMakeChecked::clear_icon() {
  icon_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ClientUniversalPatchMakeChecked::_internal_icon() const {
  return icon_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ClientUniversalPatchMakeChecked::icon() const {
  // @@protoc_insertion_point(field_get:ClientUniversalPatchMakeChecked.Icon)
  return _internal_icon();
}
inline void ClientUniversalPatchMakeChecked::_internal_set_icon(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  icon_ = value;
}
inline void ClientUniversalPatchMakeChecked::set_icon(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_icon(value);
  // @@protoc_insertion_point(field_set:ClientUniversalPatchMakeChecked.Icon)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ClientUniversalPatchMakeChecked_2eproto
