// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientCancelTask.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ClientCancelTask_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ClientCancelTask_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ClientCancelTask_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ClientCancelTask_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
class ClientCancelTask;
class ClientCancelTaskDefaultTypeInternal;
extern ClientCancelTaskDefaultTypeInternal _ClientCancelTask_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ClientCancelTask* Arena::CreateMaybeMessage<::ClientCancelTask>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ClientCancelTask :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:ClientCancelTask) */ {
 public:
  ClientCancelTask();
  virtual ~ClientCancelTask();

  ClientCancelTask(const ClientCancelTask& from);
  ClientCancelTask(ClientCancelTask&& from) noexcept
    : ClientCancelTask() {
    *this = ::std::move(from);
  }

  inline ClientCancelTask& operator=(const ClientCancelTask& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientCancelTask& operator=(ClientCancelTask&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ClientCancelTask& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClientCancelTask* internal_default_instance() {
    return reinterpret_cast<const ClientCancelTask*>(
               &_ClientCancelTask_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClientCancelTask& a, ClientCancelTask& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientCancelTask* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ClientCancelTask* New() const final {
    return CreateMaybeMessage<ClientCancelTask>(nullptr);
  }

  ClientCancelTask* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ClientCancelTask>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const ClientCancelTask& from);
  void MergeFrom(const ClientCancelTask& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ClientCancelTask* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ClientCancelTask";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSequenceIdFieldNumber = 1,
  };
  // uint64 SequenceId = 1;
  void clear_sequenceid();
  ::PROTOBUF_NAMESPACE_ID::uint64 sequenceid() const;
  void set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_sequenceid() const;
  void _internal_set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:ClientCancelTask)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sequenceid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ClientCancelTask_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientCancelTask

// uint64 SequenceId = 1;
inline void ClientCancelTask::clear_sequenceid() {
  sequenceid_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientCancelTask::_internal_sequenceid() const {
  return sequenceid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientCancelTask::sequenceid() const {
  // @@protoc_insertion_point(field_get:ClientCancelTask.SequenceId)
  return _internal_sequenceid();
}
inline void ClientCancelTask::_internal_set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  sequenceid_ = value;
}
inline void ClientCancelTask::set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_sequenceid(value);
  // @@protoc_insertion_point(field_set:ClientCancelTask.SequenceId)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ClientCancelTask_2eproto
