// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientUniversalDumperModeChecked.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ClientUniversalDumperModeChecked_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ClientUniversalDumperModeChecked_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ClientUniversalDumperModeChecked_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ClientUniversalDumperModeChecked_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
class ClientUniversalDumperModeChecked;
class ClientUniversalDumperModeCheckedDefaultTypeInternal;
extern ClientUniversalDumperModeCheckedDefaultTypeInternal _ClientUniversalDumperModeChecked_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ClientUniversalDumperModeChecked* Arena::CreateMaybeMessage<::ClientUniversalDumperModeChecked>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ClientUniversalDumperModeChecked :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:ClientUniversalDumperModeChecked) */ {
 public:
  ClientUniversalDumperModeChecked();
  virtual ~ClientUniversalDumperModeChecked();

  ClientUniversalDumperModeChecked(const ClientUniversalDumperModeChecked& from);
  ClientUniversalDumperModeChecked(ClientUniversalDumperModeChecked&& from) noexcept
    : ClientUniversalDumperModeChecked() {
    *this = ::std::move(from);
  }

  inline ClientUniversalDumperModeChecked& operator=(const ClientUniversalDumperModeChecked& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientUniversalDumperModeChecked& operator=(ClientUniversalDumperModeChecked&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ClientUniversalDumperModeChecked& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClientUniversalDumperModeChecked* internal_default_instance() {
    return reinterpret_cast<const ClientUniversalDumperModeChecked*>(
               &_ClientUniversalDumperModeChecked_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClientUniversalDumperModeChecked& a, ClientUniversalDumperModeChecked& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientUniversalDumperModeChecked* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ClientUniversalDumperModeChecked* New() const final {
    return CreateMaybeMessage<ClientUniversalDumperModeChecked>(nullptr);
  }

  ClientUniversalDumperModeChecked* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ClientUniversalDumperModeChecked>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const ClientUniversalDumperModeChecked& from);
  void MergeFrom(const ClientUniversalDumperModeChecked& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ClientUniversalDumperModeChecked* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ClientUniversalDumperModeChecked";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSequenceIdFieldNumber = 1,
    kPsbModeFieldNumber = 2,
    kTextModeFieldNumber = 3,
    kPngModeFieldNumber = 4,
    kTjs2ModeFieldNumber = 5,
    kTlgModeFieldNumber = 6,
    kAmvModeFieldNumber = 7,
    kPdbModeFieldNumber = 8,
  };
  // uint64 SequenceId = 1;
  void clear_sequenceid();
  ::PROTOBUF_NAMESPACE_ID::uint64 sequenceid() const;
  void set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_sequenceid() const;
  void _internal_set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 PsbMode = 2;
  void clear_psbmode();
  ::PROTOBUF_NAMESPACE_ID::uint64 psbmode() const;
  void set_psbmode(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_psbmode() const;
  void _internal_set_psbmode(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 TextMode = 3;
  void clear_textmode();
  ::PROTOBUF_NAMESPACE_ID::uint64 textmode() const;
  void set_textmode(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_textmode() const;
  void _internal_set_textmode(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 PngMode = 4;
  void clear_pngmode();
  ::PROTOBUF_NAMESPACE_ID::uint64 pngmode() const;
  void set_pngmode(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_pngmode() const;
  void _internal_set_pngmode(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 Tjs2Mode = 5;
  void clear_tjs2mode();
  ::PROTOBUF_NAMESPACE_ID::uint64 tjs2mode() const;
  void set_tjs2mode(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_tjs2mode() const;
  void _internal_set_tjs2mode(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 TlgMode = 6;
  void clear_tlgmode();
  ::PROTOBUF_NAMESPACE_ID::uint64 tlgmode() const;
  void set_tlgmode(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_tlgmode() const;
  void _internal_set_tlgmode(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 AmvMode = 7;
  void clear_amvmode();
  ::PROTOBUF_NAMESPACE_ID::uint64 amvmode() const;
  void set_amvmode(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_amvmode() const;
  void _internal_set_amvmode(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 PdbMode = 8;
  void clear_pdbmode();
  ::PROTOBUF_NAMESPACE_ID::uint64 pdbmode() const;
  void set_pdbmode(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_pdbmode() const;
  void _internal_set_pdbmode(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:ClientUniversalDumperModeChecked)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sequenceid_;
  ::PROTOBUF_NAMESPACE_ID::uint64 psbmode_;
  ::PROTOBUF_NAMESPACE_ID::uint64 textmode_;
  ::PROTOBUF_NAMESPACE_ID::uint64 pngmode_;
  ::PROTOBUF_NAMESPACE_ID::uint64 tjs2mode_;
  ::PROTOBUF_NAMESPACE_ID::uint64 tlgmode_;
  ::PROTOBUF_NAMESPACE_ID::uint64 amvmode_;
  ::PROTOBUF_NAMESPACE_ID::uint64 pdbmode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ClientUniversalDumperModeChecked_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientUniversalDumperModeChecked

// uint64 SequenceId = 1;
inline void ClientUniversalDumperModeChecked::clear_sequenceid() {
  sequenceid_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::_internal_sequenceid() const {
  return sequenceid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::sequenceid() const {
  // @@protoc_insertion_point(field_get:ClientUniversalDumperModeChecked.SequenceId)
  return _internal_sequenceid();
}
inline void ClientUniversalDumperModeChecked::_internal_set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  sequenceid_ = value;
}
inline void ClientUniversalDumperModeChecked::set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_sequenceid(value);
  // @@protoc_insertion_point(field_set:ClientUniversalDumperModeChecked.SequenceId)
}

// uint64 PsbMode = 2;
inline void ClientUniversalDumperModeChecked::clear_psbmode() {
  psbmode_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::_internal_psbmode() const {
  return psbmode_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::psbmode() const {
  // @@protoc_insertion_point(field_get:ClientUniversalDumperModeChecked.PsbMode)
  return _internal_psbmode();
}
inline void ClientUniversalDumperModeChecked::_internal_set_psbmode(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  psbmode_ = value;
}
inline void ClientUniversalDumperModeChecked::set_psbmode(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_psbmode(value);
  // @@protoc_insertion_point(field_set:ClientUniversalDumperModeChecked.PsbMode)
}

// uint64 TextMode = 3;
inline void ClientUniversalDumperModeChecked::clear_textmode() {
  textmode_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::_internal_textmode() const {
  return textmode_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::textmode() const {
  // @@protoc_insertion_point(field_get:ClientUniversalDumperModeChecked.TextMode)
  return _internal_textmode();
}
inline void ClientUniversalDumperModeChecked::_internal_set_textmode(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  textmode_ = value;
}
inline void ClientUniversalDumperModeChecked::set_textmode(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_textmode(value);
  // @@protoc_insertion_point(field_set:ClientUniversalDumperModeChecked.TextMode)
}

// uint64 PngMode = 4;
inline void ClientUniversalDumperModeChecked::clear_pngmode() {
  pngmode_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::_internal_pngmode() const {
  return pngmode_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::pngmode() const {
  // @@protoc_insertion_point(field_get:ClientUniversalDumperModeChecked.PngMode)
  return _internal_pngmode();
}
inline void ClientUniversalDumperModeChecked::_internal_set_pngmode(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  pngmode_ = value;
}
inline void ClientUniversalDumperModeChecked::set_pngmode(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_pngmode(value);
  // @@protoc_insertion_point(field_set:ClientUniversalDumperModeChecked.PngMode)
}

// uint64 Tjs2Mode = 5;
inline void ClientUniversalDumperModeChecked::clear_tjs2mode() {
  tjs2mode_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::_internal_tjs2mode() const {
  return tjs2mode_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::tjs2mode() const {
  // @@protoc_insertion_point(field_get:ClientUniversalDumperModeChecked.Tjs2Mode)
  return _internal_tjs2mode();
}
inline void ClientUniversalDumperModeChecked::_internal_set_tjs2mode(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  tjs2mode_ = value;
}
inline void ClientUniversalDumperModeChecked::set_tjs2mode(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_tjs2mode(value);
  // @@protoc_insertion_point(field_set:ClientUniversalDumperModeChecked.Tjs2Mode)
}

// uint64 TlgMode = 6;
inline void ClientUniversalDumperModeChecked::clear_tlgmode() {
  tlgmode_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::_internal_tlgmode() const {
  return tlgmode_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::tlgmode() const {
  // @@protoc_insertion_point(field_get:ClientUniversalDumperModeChecked.TlgMode)
  return _internal_tlgmode();
}
inline void ClientUniversalDumperModeChecked::_internal_set_tlgmode(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  tlgmode_ = value;
}
inline void ClientUniversalDumperModeChecked::set_tlgmode(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_tlgmode(value);
  // @@protoc_insertion_point(field_set:ClientUniversalDumperModeChecked.TlgMode)
}

// uint64 AmvMode = 7;
inline void ClientUniversalDumperModeChecked::clear_amvmode() {
  amvmode_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::_internal_amvmode() const {
  return amvmode_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::amvmode() const {
  // @@protoc_insertion_point(field_get:ClientUniversalDumperModeChecked.AmvMode)
  return _internal_amvmode();
}
inline void ClientUniversalDumperModeChecked::_internal_set_amvmode(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  amvmode_ = value;
}
inline void ClientUniversalDumperModeChecked::set_amvmode(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_amvmode(value);
  // @@protoc_insertion_point(field_set:ClientUniversalDumperModeChecked.AmvMode)
}

// uint64 PdbMode = 8;
inline void ClientUniversalDumperModeChecked::clear_pdbmode() {
  pdbmode_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::_internal_pdbmode() const {
  return pdbmode_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientUniversalDumperModeChecked::pdbmode() const {
  // @@protoc_insertion_point(field_get:ClientUniversalDumperModeChecked.PdbMode)
  return _internal_pdbmode();
}
inline void ClientUniversalDumperModeChecked::_internal_set_pdbmode(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  pdbmode_ = value;
}
inline void ClientUniversalDumperModeChecked::set_pdbmode(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_pdbmode(value);
  // @@protoc_insertion_point(field_set:ClientUniversalDumperModeChecked.PdbMode)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ClientUniversalDumperModeChecked_2eproto
