// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientTaskCloseWindow.proto

#include "ClientTaskCloseWindow.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
class ClientTaskCloseWindowDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ClientTaskCloseWindow> _instance;
} _ClientTaskCloseWindow_default_instance_;
static void InitDefaultsscc_info_ClientTaskCloseWindow_ClientTaskCloseWindow_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_ClientTaskCloseWindow_default_instance_;
    new (ptr) ::ClientTaskCloseWindow();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ClientTaskCloseWindow::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ClientTaskCloseWindow_ClientTaskCloseWindow_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ClientTaskCloseWindow_ClientTaskCloseWindow_2eproto}, {}};


// ===================================================================

void ClientTaskCloseWindow::InitAsDefaultInstance() {
}
class ClientTaskCloseWindow::_Internal {
 public:
};

ClientTaskCloseWindow::ClientTaskCloseWindow()
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ClientTaskCloseWindow)
}
ClientTaskCloseWindow::ClientTaskCloseWindow(const ClientTaskCloseWindow& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  sequenceid_ = from.sequenceid_;
  // @@protoc_insertion_point(copy_constructor:ClientTaskCloseWindow)
}

void ClientTaskCloseWindow::SharedCtor() {
  sequenceid_ = PROTOBUF_ULONGLONG(0);
}

ClientTaskCloseWindow::~ClientTaskCloseWindow() {
  // @@protoc_insertion_point(destructor:ClientTaskCloseWindow)
  SharedDtor();
}

void ClientTaskCloseWindow::SharedDtor() {
}

void ClientTaskCloseWindow::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ClientTaskCloseWindow& ClientTaskCloseWindow::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ClientTaskCloseWindow_ClientTaskCloseWindow_2eproto.base);
  return *internal_default_instance();
}


void ClientTaskCloseWindow::Clear() {
// @@protoc_insertion_point(message_clear_start:ClientTaskCloseWindow)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sequenceid_ = PROTOBUF_ULONGLONG(0);
  _internal_metadata_.Clear();
}

const char* ClientTaskCloseWindow::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 SequenceId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          sequenceid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ClientTaskCloseWindow::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ClientTaskCloseWindow)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 SequenceId = 1;
  if (this->sequenceid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_sequenceid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields().data(),
        static_cast<int>(_internal_metadata_.unknown_fields().size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ClientTaskCloseWindow)
  return target;
}

size_t ClientTaskCloseWindow::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ClientTaskCloseWindow)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 SequenceId = 1;
  if (this->sequenceid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_sequenceid());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields().size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClientTaskCloseWindow::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const ClientTaskCloseWindow*>(
      &from));
}

void ClientTaskCloseWindow::MergeFrom(const ClientTaskCloseWindow& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ClientTaskCloseWindow)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sequenceid() != 0) {
    _internal_set_sequenceid(from._internal_sequenceid());
  }
}

void ClientTaskCloseWindow::CopyFrom(const ClientTaskCloseWindow& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ClientTaskCloseWindow)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientTaskCloseWindow::IsInitialized() const {
  return true;
}

void ClientTaskCloseWindow::InternalSwap(ClientTaskCloseWindow* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(sequenceid_, other->sequenceid_);
}

std::string ClientTaskCloseWindow::GetTypeName() const {
  return "ClientTaskCloseWindow";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ClientTaskCloseWindow* Arena::CreateMaybeMessage< ::ClientTaskCloseWindow >(Arena* arena) {
  return Arena::CreateInternal< ::ClientTaskCloseWindow >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
