// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientPackerChecked.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ClientPackerChecked_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ClientPackerChecked_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ClientPackerChecked_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ClientPackerChecked_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
class ClientPackerChecked;
class ClientPackerCheckedDefaultTypeInternal;
extern ClientPackerCheckedDefaultTypeInternal _ClientPackerChecked_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ClientPackerChecked* Arena::CreateMaybeMessage<::ClientPackerChecked>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ClientPackerChecked :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:ClientPackerChecked) */ {
 public:
  ClientPackerChecked();
  virtual ~ClientPackerChecked();

  ClientPackerChecked(const ClientPackerChecked& from);
  ClientPackerChecked(ClientPackerChecked&& from) noexcept
    : ClientPackerChecked() {
    *this = ::std::move(from);
  }

  inline ClientPackerChecked& operator=(const ClientPackerChecked& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientPackerChecked& operator=(ClientPackerChecked&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ClientPackerChecked& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClientPackerChecked* internal_default_instance() {
    return reinterpret_cast<const ClientPackerChecked*>(
               &_ClientPackerChecked_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClientPackerChecked& a, ClientPackerChecked& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientPackerChecked* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ClientPackerChecked* New() const final {
    return CreateMaybeMessage<ClientPackerChecked>(nullptr);
  }

  ClientPackerChecked* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ClientPackerChecked>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const ClientPackerChecked& from);
  void MergeFrom(const ClientPackerChecked& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ClientPackerChecked* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ClientPackerChecked";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBaseDirFieldNumber = 2,
    kOriginalArchiveNameFieldNumber = 3,
    kOutputArchiveNameFieldNumber = 4,
    kSequenceIdFieldNumber = 1,
  };
  // string BaseDir = 2;
  void clear_basedir();
  const std::string& basedir() const;
  void set_basedir(const std::string& value);
  void set_basedir(std::string&& value);
  void set_basedir(const char* value);
  void set_basedir(const char* value, size_t size);
  std::string* mutable_basedir();
  std::string* release_basedir();
  void set_allocated_basedir(std::string* basedir);
  private:
  const std::string& _internal_basedir() const;
  void _internal_set_basedir(const std::string& value);
  std::string* _internal_mutable_basedir();
  public:

  // string OriginalArchiveName = 3;
  void clear_originalarchivename();
  const std::string& originalarchivename() const;
  void set_originalarchivename(const std::string& value);
  void set_originalarchivename(std::string&& value);
  void set_originalarchivename(const char* value);
  void set_originalarchivename(const char* value, size_t size);
  std::string* mutable_originalarchivename();
  std::string* release_originalarchivename();
  void set_allocated_originalarchivename(std::string* originalarchivename);
  private:
  const std::string& _internal_originalarchivename() const;
  void _internal_set_originalarchivename(const std::string& value);
  std::string* _internal_mutable_originalarchivename();
  public:

  // string OutputArchiveName = 4;
  void clear_outputarchivename();
  const std::string& outputarchivename() const;
  void set_outputarchivename(const std::string& value);
  void set_outputarchivename(std::string&& value);
  void set_outputarchivename(const char* value);
  void set_outputarchivename(const char* value, size_t size);
  std::string* mutable_outputarchivename();
  std::string* release_outputarchivename();
  void set_allocated_outputarchivename(std::string* outputarchivename);
  private:
  const std::string& _internal_outputarchivename() const;
  void _internal_set_outputarchivename(const std::string& value);
  std::string* _internal_mutable_outputarchivename();
  public:

  // uint64 SequenceId = 1;
  void clear_sequenceid();
  ::PROTOBUF_NAMESPACE_ID::uint64 sequenceid() const;
  void set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_sequenceid() const;
  void _internal_set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:ClientPackerChecked)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr basedir_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr originalarchivename_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr outputarchivename_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sequenceid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ClientPackerChecked_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientPackerChecked

// uint64 SequenceId = 1;
inline void ClientPackerChecked::clear_sequenceid() {
  sequenceid_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientPackerChecked::_internal_sequenceid() const {
  return sequenceid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ClientPackerChecked::sequenceid() const {
  // @@protoc_insertion_point(field_get:ClientPackerChecked.SequenceId)
  return _internal_sequenceid();
}
inline void ClientPackerChecked::_internal_set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  sequenceid_ = value;
}
inline void ClientPackerChecked::set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_sequenceid(value);
  // @@protoc_insertion_point(field_set:ClientPackerChecked.SequenceId)
}

// string BaseDir = 2;
inline void ClientPackerChecked::clear_basedir() {
  basedir_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ClientPackerChecked::basedir() const {
  // @@protoc_insertion_point(field_get:ClientPackerChecked.BaseDir)
  return _internal_basedir();
}
inline void ClientPackerChecked::set_basedir(const std::string& value) {
  _internal_set_basedir(value);
  // @@protoc_insertion_point(field_set:ClientPackerChecked.BaseDir)
}
inline std::string* ClientPackerChecked::mutable_basedir() {
  // @@protoc_insertion_point(field_mutable:ClientPackerChecked.BaseDir)
  return _internal_mutable_basedir();
}
inline const std::string& ClientPackerChecked::_internal_basedir() const {
  return basedir_.GetNoArena();
}
inline void ClientPackerChecked::_internal_set_basedir(const std::string& value) {
  
  basedir_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ClientPackerChecked::set_basedir(std::string&& value) {
  
  basedir_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ClientPackerChecked.BaseDir)
}
inline void ClientPackerChecked::set_basedir(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  basedir_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ClientPackerChecked.BaseDir)
}
inline void ClientPackerChecked::set_basedir(const char* value, size_t size) {
  
  basedir_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ClientPackerChecked.BaseDir)
}
inline std::string* ClientPackerChecked::_internal_mutable_basedir() {
  
  return basedir_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ClientPackerChecked::release_basedir() {
  // @@protoc_insertion_point(field_release:ClientPackerChecked.BaseDir)
  
  return basedir_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ClientPackerChecked::set_allocated_basedir(std::string* basedir) {
  if (basedir != nullptr) {
    
  } else {
    
  }
  basedir_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), basedir);
  // @@protoc_insertion_point(field_set_allocated:ClientPackerChecked.BaseDir)
}

// string OriginalArchiveName = 3;
inline void ClientPackerChecked::clear_originalarchivename() {
  originalarchivename_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ClientPackerChecked::originalarchivename() const {
  // @@protoc_insertion_point(field_get:ClientPackerChecked.OriginalArchiveName)
  return _internal_originalarchivename();
}
inline void ClientPackerChecked::set_originalarchivename(const std::string& value) {
  _internal_set_originalarchivename(value);
  // @@protoc_insertion_point(field_set:ClientPackerChecked.OriginalArchiveName)
}
inline std::string* ClientPackerChecked::mutable_originalarchivename() {
  // @@protoc_insertion_point(field_mutable:ClientPackerChecked.OriginalArchiveName)
  return _internal_mutable_originalarchivename();
}
inline const std::string& ClientPackerChecked::_internal_originalarchivename() const {
  return originalarchivename_.GetNoArena();
}
inline void ClientPackerChecked::_internal_set_originalarchivename(const std::string& value) {
  
  originalarchivename_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ClientPackerChecked::set_originalarchivename(std::string&& value) {
  
  originalarchivename_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ClientPackerChecked.OriginalArchiveName)
}
inline void ClientPackerChecked::set_originalarchivename(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  originalarchivename_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ClientPackerChecked.OriginalArchiveName)
}
inline void ClientPackerChecked::set_originalarchivename(const char* value, size_t size) {
  
  originalarchivename_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ClientPackerChecked.OriginalArchiveName)
}
inline std::string* ClientPackerChecked::_internal_mutable_originalarchivename() {
  
  return originalarchivename_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ClientPackerChecked::release_originalarchivename() {
  // @@protoc_insertion_point(field_release:ClientPackerChecked.OriginalArchiveName)
  
  return originalarchivename_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ClientPackerChecked::set_allocated_originalarchivename(std::string* originalarchivename) {
  if (originalarchivename != nullptr) {
    
  } else {
    
  }
  originalarchivename_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), originalarchivename);
  // @@protoc_insertion_point(field_set_allocated:ClientPackerChecked.OriginalArchiveName)
}

// string OutputArchiveName = 4;
inline void ClientPackerChecked::clear_outputarchivename() {
  outputarchivename_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ClientPackerChecked::outputarchivename() const {
  // @@protoc_insertion_point(field_get:ClientPackerChecked.OutputArchiveName)
  return _internal_outputarchivename();
}
inline void ClientPackerChecked::set_outputarchivename(const std::string& value) {
  _internal_set_outputarchivename(value);
  // @@protoc_insertion_point(field_set:ClientPackerChecked.OutputArchiveName)
}
inline std::string* ClientPackerChecked::mutable_outputarchivename() {
  // @@protoc_insertion_point(field_mutable:ClientPackerChecked.OutputArchiveName)
  return _internal_mutable_outputarchivename();
}
inline const std::string& ClientPackerChecked::_internal_outputarchivename() const {
  return outputarchivename_.GetNoArena();
}
inline void ClientPackerChecked::_internal_set_outputarchivename(const std::string& value) {
  
  outputarchivename_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ClientPackerChecked::set_outputarchivename(std::string&& value) {
  
  outputarchivename_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ClientPackerChecked.OutputArchiveName)
}
inline void ClientPackerChecked::set_outputarchivename(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  outputarchivename_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ClientPackerChecked.OutputArchiveName)
}
inline void ClientPackerChecked::set_outputarchivename(const char* value, size_t size) {
  
  outputarchivename_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ClientPackerChecked.OutputArchiveName)
}
inline std::string* ClientPackerChecked::_internal_mutable_outputarchivename() {
  
  return outputarchivename_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ClientPackerChecked::release_outputarchivename() {
  // @@protoc_insertion_point(field_release:ClientPackerChecked.OutputArchiveName)
  
  return outputarchivename_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ClientPackerChecked::set_allocated_outputarchivename(std::string* outputarchivename) {
  if (outputarchivename != nullptr) {
    
  } else {
    
  }
  outputarchivename_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), outputarchivename);
  // @@protoc_insertion_point(field_set_allocated:ClientPackerChecked.OutputArchiveName)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ClientPackerChecked_2eproto
