// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerTaskEndAndEnableUI.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ServerTaskEndAndEnableUI_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ServerTaskEndAndEnableUI_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ServerTaskEndAndEnableUI_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ServerTaskEndAndEnableUI_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
class ServerTaskEndAndEnableUI;
class ServerTaskEndAndEnableUIDefaultTypeInternal;
extern ServerTaskEndAndEnableUIDefaultTypeInternal _ServerTaskEndAndEnableUI_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ServerTaskEndAndEnableUI* Arena::CreateMaybeMessage<::ServerTaskEndAndEnableUI>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ServerTaskEndAndEnableUI :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:ServerTaskEndAndEnableUI) */ {
 public:
  ServerTaskEndAndEnableUI();
  virtual ~ServerTaskEndAndEnableUI();

  ServerTaskEndAndEnableUI(const ServerTaskEndAndEnableUI& from);
  ServerTaskEndAndEnableUI(ServerTaskEndAndEnableUI&& from) noexcept
    : ServerTaskEndAndEnableUI() {
    *this = ::std::move(from);
  }

  inline ServerTaskEndAndEnableUI& operator=(const ServerTaskEndAndEnableUI& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerTaskEndAndEnableUI& operator=(ServerTaskEndAndEnableUI&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ServerTaskEndAndEnableUI& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerTaskEndAndEnableUI* internal_default_instance() {
    return reinterpret_cast<const ServerTaskEndAndEnableUI*>(
               &_ServerTaskEndAndEnableUI_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ServerTaskEndAndEnableUI& a, ServerTaskEndAndEnableUI& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerTaskEndAndEnableUI* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServerTaskEndAndEnableUI* New() const final {
    return CreateMaybeMessage<ServerTaskEndAndEnableUI>(nullptr);
  }

  ServerTaskEndAndEnableUI* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServerTaskEndAndEnableUI>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const ServerTaskEndAndEnableUI& from);
  void MergeFrom(const ServerTaskEndAndEnableUI& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ServerTaskEndAndEnableUI* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ServerTaskEndAndEnableUI";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDescriptionFieldNumber = 3,
    kSequenceIdFieldNumber = 1,
    kTaskCompleteStatusFieldNumber = 2,
  };
  // string Description = 3;
  void clear_description();
  const std::string& description() const;
  void set_description(const std::string& value);
  void set_description(std::string&& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  std::string* mutable_description();
  std::string* release_description();
  void set_allocated_description(std::string* description);
  private:
  const std::string& _internal_description() const;
  void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // uint64 SequenceId = 1;
  void clear_sequenceid();
  ::PROTOBUF_NAMESPACE_ID::uint64 sequenceid() const;
  void set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_sequenceid() const;
  void _internal_set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 TaskCompleteStatus = 2;
  void clear_taskcompletestatus();
  ::PROTOBUF_NAMESPACE_ID::uint32 taskcompletestatus() const;
  void set_taskcompletestatus(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_taskcompletestatus() const;
  void _internal_set_taskcompletestatus(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:ServerTaskEndAndEnableUI)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sequenceid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 taskcompletestatus_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ServerTaskEndAndEnableUI_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServerTaskEndAndEnableUI

// uint64 SequenceId = 1;
inline void ServerTaskEndAndEnableUI::clear_sequenceid() {
  sequenceid_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ServerTaskEndAndEnableUI::_internal_sequenceid() const {
  return sequenceid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ServerTaskEndAndEnableUI::sequenceid() const {
  // @@protoc_insertion_point(field_get:ServerTaskEndAndEnableUI.SequenceId)
  return _internal_sequenceid();
}
inline void ServerTaskEndAndEnableUI::_internal_set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  sequenceid_ = value;
}
inline void ServerTaskEndAndEnableUI::set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_sequenceid(value);
  // @@protoc_insertion_point(field_set:ServerTaskEndAndEnableUI.SequenceId)
}

// uint32 TaskCompleteStatus = 2;
inline void ServerTaskEndAndEnableUI::clear_taskcompletestatus() {
  taskcompletestatus_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ServerTaskEndAndEnableUI::_internal_taskcompletestatus() const {
  return taskcompletestatus_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ServerTaskEndAndEnableUI::taskcompletestatus() const {
  // @@protoc_insertion_point(field_get:ServerTaskEndAndEnableUI.TaskCompleteStatus)
  return _internal_taskcompletestatus();
}
inline void ServerTaskEndAndEnableUI::_internal_set_taskcompletestatus(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  taskcompletestatus_ = value;
}
inline void ServerTaskEndAndEnableUI::set_taskcompletestatus(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_taskcompletestatus(value);
  // @@protoc_insertion_point(field_set:ServerTaskEndAndEnableUI.TaskCompleteStatus)
}

// string Description = 3;
inline void ServerTaskEndAndEnableUI::clear_description() {
  description_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ServerTaskEndAndEnableUI::description() const {
  // @@protoc_insertion_point(field_get:ServerTaskEndAndEnableUI.Description)
  return _internal_description();
}
inline void ServerTaskEndAndEnableUI::set_description(const std::string& value) {
  _internal_set_description(value);
  // @@protoc_insertion_point(field_set:ServerTaskEndAndEnableUI.Description)
}
inline std::string* ServerTaskEndAndEnableUI::mutable_description() {
  // @@protoc_insertion_point(field_mutable:ServerTaskEndAndEnableUI.Description)
  return _internal_mutable_description();
}
inline const std::string& ServerTaskEndAndEnableUI::_internal_description() const {
  return description_.GetNoArena();
}
inline void ServerTaskEndAndEnableUI::_internal_set_description(const std::string& value) {
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ServerTaskEndAndEnableUI::set_description(std::string&& value) {
  
  description_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ServerTaskEndAndEnableUI.Description)
}
inline void ServerTaskEndAndEnableUI::set_description(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ServerTaskEndAndEnableUI.Description)
}
inline void ServerTaskEndAndEnableUI::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ServerTaskEndAndEnableUI.Description)
}
inline std::string* ServerTaskEndAndEnableUI::_internal_mutable_description() {
  
  return description_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ServerTaskEndAndEnableUI::release_description() {
  // @@protoc_insertion_point(field_release:ServerTaskEndAndEnableUI.Description)
  
  return description_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ServerTaskEndAndEnableUI::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:ServerTaskEndAndEnableUI.Description)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ServerTaskEndAndEnableUI_2eproto
