// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerCommandResultOutput.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ServerCommandResultOutput_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ServerCommandResultOutput_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ServerCommandResultOutput_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ServerCommandResultOutput_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
class ServerCommandResultOutput;
class ServerCommandResultOutputDefaultTypeInternal;
extern ServerCommandResultOutputDefaultTypeInternal _ServerCommandResultOutput_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ServerCommandResultOutput* Arena::CreateMaybeMessage<::ServerCommandResultOutput>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ServerCommandResultOutput :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:ServerCommandResultOutput) */ {
 public:
  ServerCommandResultOutput();
  virtual ~ServerCommandResultOutput();

  ServerCommandResultOutput(const ServerCommandResultOutput& from);
  ServerCommandResultOutput(ServerCommandResultOutput&& from) noexcept
    : ServerCommandResultOutput() {
    *this = ::std::move(from);
  }

  inline ServerCommandResultOutput& operator=(const ServerCommandResultOutput& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerCommandResultOutput& operator=(ServerCommandResultOutput&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ServerCommandResultOutput& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerCommandResultOutput* internal_default_instance() {
    return reinterpret_cast<const ServerCommandResultOutput*>(
               &_ServerCommandResultOutput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ServerCommandResultOutput& a, ServerCommandResultOutput& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerCommandResultOutput* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServerCommandResultOutput* New() const final {
    return CreateMaybeMessage<ServerCommandResultOutput>(nullptr);
  }

  ServerCommandResultOutput* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServerCommandResultOutput>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)
    final;
  void CopyFrom(const ServerCommandResultOutput& from);
  void MergeFrom(const ServerCommandResultOutput& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ServerCommandResultOutput* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ServerCommandResultOutput";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReplyFieldNumber = 3,
    kSequenceIdFieldNumber = 1,
    kStatusFieldNumber = 2,
  };
  // string Reply = 3;
  void clear_reply();
  const std::string& reply() const;
  void set_reply(const std::string& value);
  void set_reply(std::string&& value);
  void set_reply(const char* value);
  void set_reply(const char* value, size_t size);
  std::string* mutable_reply();
  std::string* release_reply();
  void set_allocated_reply(std::string* reply);
  private:
  const std::string& _internal_reply() const;
  void _internal_set_reply(const std::string& value);
  std::string* _internal_mutable_reply();
  public:

  // uint64 SequenceId = 1;
  void clear_sequenceid();
  ::PROTOBUF_NAMESPACE_ID::uint64 sequenceid() const;
  void set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_sequenceid() const;
  void _internal_set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 Status = 2;
  void clear_status();
  ::PROTOBUF_NAMESPACE_ID::uint64 status() const;
  void set_status(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_status() const;
  void _internal_set_status(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:ServerCommandResultOutput)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reply_;
  ::PROTOBUF_NAMESPACE_ID::uint64 sequenceid_;
  ::PROTOBUF_NAMESPACE_ID::uint64 status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ServerCommandResultOutput_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ServerCommandResultOutput

// uint64 SequenceId = 1;
inline void ServerCommandResultOutput::clear_sequenceid() {
  sequenceid_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ServerCommandResultOutput::_internal_sequenceid() const {
  return sequenceid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ServerCommandResultOutput::sequenceid() const {
  // @@protoc_insertion_point(field_get:ServerCommandResultOutput.SequenceId)
  return _internal_sequenceid();
}
inline void ServerCommandResultOutput::_internal_set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  sequenceid_ = value;
}
inline void ServerCommandResultOutput::set_sequenceid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_sequenceid(value);
  // @@protoc_insertion_point(field_set:ServerCommandResultOutput.SequenceId)
}

// uint64 Status = 2;
inline void ServerCommandResultOutput::clear_status() {
  status_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ServerCommandResultOutput::_internal_status() const {
  return status_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ServerCommandResultOutput::status() const {
  // @@protoc_insertion_point(field_get:ServerCommandResultOutput.Status)
  return _internal_status();
}
inline void ServerCommandResultOutput::_internal_set_status(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  status_ = value;
}
inline void ServerCommandResultOutput::set_status(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:ServerCommandResultOutput.Status)
}

// string Reply = 3;
inline void ServerCommandResultOutput::clear_reply() {
  reply_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ServerCommandResultOutput::reply() const {
  // @@protoc_insertion_point(field_get:ServerCommandResultOutput.Reply)
  return _internal_reply();
}
inline void ServerCommandResultOutput::set_reply(const std::string& value) {
  _internal_set_reply(value);
  // @@protoc_insertion_point(field_set:ServerCommandResultOutput.Reply)
}
inline std::string* ServerCommandResultOutput::mutable_reply() {
  // @@protoc_insertion_point(field_mutable:ServerCommandResultOutput.Reply)
  return _internal_mutable_reply();
}
inline const std::string& ServerCommandResultOutput::_internal_reply() const {
  return reply_.GetNoArena();
}
inline void ServerCommandResultOutput::_internal_set_reply(const std::string& value) {
  
  reply_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ServerCommandResultOutput::set_reply(std::string&& value) {
  
  reply_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ServerCommandResultOutput.Reply)
}
inline void ServerCommandResultOutput::set_reply(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  reply_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ServerCommandResultOutput.Reply)
}
inline void ServerCommandResultOutput::set_reply(const char* value, size_t size) {
  
  reply_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ServerCommandResultOutput.Reply)
}
inline std::string* ServerCommandResultOutput::_internal_mutable_reply() {
  
  return reply_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ServerCommandResultOutput::release_reply() {
  // @@protoc_insertion_point(field_release:ServerCommandResultOutput.Reply)
  
  return reply_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ServerCommandResultOutput::set_allocated_reply(std::string* reply) {
  if (reply != nullptr) {
    
  } else {
    
  }
  reply_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), reply);
  // @@protoc_insertion_point(field_set_allocated:ServerCommandResultOutput.Reply)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ServerCommandResultOutput_2eproto
